<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form name="frm" method=post action="/qtht/config/viewbussdate">
<div style="float: left;width: 600px;">
<table class=adminlist>
	<thead>
		<tr>
			<th><a href="/qtht/config/viewbussdate/month/<?=$this->curmonth-1?>">&lt;&lt;</a></th>
			<th colspan="5" style="text-align: left">
				Tháng <?=$this->curmonth?>
			</th>
			<th><a href="/qtht/config/viewbussdate/month/<?=$this->curmonth+1?>">&gt;&gt;</a></th>
		</tr>
		<tr>
			<th>Th2<input type=checkbox name=WDAY[] value="1" style="border-width: 0px;background: transparent;"></th>
			<th>Th3<input type=checkbox name=WDAY[] value="2" style="border-width: 0px;background: transparent;"></th>
			<th>Th4<input type=checkbox name=WDAY[] value="3" style="border-width: 0px;background: transparent;"></th>
			<th>Th5<input type=checkbox name=WDAY[] value="4" style="border-width: 0px;background: transparent;"></th>
			<th>Th6<input type=checkbox name=WDAY[] value="5" style="border-width: 0px;background: transparent;"></th>
			<th>Th7<input type=checkbox name=WDAY[] value="6" style="border-width: 0px;background: transparent;"></th>
			<th>CN<input type=checkbox name=WDAY[] value="0" style="border-width: 0px;background: transparent;"></th>
		</tr>
	</thead>
	<tbody>
<?php
	for($i=1;$i<=6;$i++){
?><tr>
<?php
		for($j=1;$j<=7;$j++){
?>
			<td <?=BussinessDateModel::IsNonWorkingDate($this->fromdate)==true?"class=row2":""?>>
				<?php
					if($this->fromdate['year']==QLVBDHCommon::getYear()){
				?>
				<input type=checkbox name=DAY[] value="<?=$this->fromdate['mon']."-".$this->fromdate['mday']."-".$this->fromdate['wday']?>" style="border-width: 0px;background: transparent;">
				<?=str_pad($this->fromdate['mday'],2,"0",STR_PAD_LEFT)?>
				<?=$this->fromdate['mon']!=$this->curmonth?"/".str_pad($this->fromdate['mon'],2,"0",STR_PAD_LEFT):""?>
				<?php
					}else{
						echo "&nbsp;";
					}
				?>
			</td>
<?php
			$this->fromdate['mday']++;
			$this->fromdate = mktime(0,0,0,$this->fromdate['mon'],$this->fromdate['mday'],$this->fromdate['year']);
			$this->fromdate = getdate($this->fromdate);
		}
?></tr>
<?php
	}
?>
	</tbody>
</table>
</div>
<div style="float: left;width:150px;margin-left:10px;">

	<span>Ngày được chọn</span>
	<table class=admintable style="padding:0;margin:0;">
		<tr>
			<td>
				<input type=radio value=1 name=scope>Ngày làm việc
			</td>
		</tr>
		<tr>
			<td>
				<input type=radio value=2 name=scope>Ngày nghỉ
			</td>
		</tr>
		<tr>
			<td>
				<input type=submit value="Cập nhật">
			</td>
		</tr>
	</table>

</div>
<input type=hidden name=month value="<?=$this->curmonth?>">
</form>
<div class=clr></div>
<p id=lasttext></p>
</body>
</html>
<script>
function resize(){
			var iframeElement = parent.document.getElementById('frmbussday');
			iframeElement.style.height = document.getElementById("lasttext").offsetTop + "px";
			iframeElement.width = "100%";
}
resize();
</script>