<?php require_once('qtht/models/DepartmentsModel.php');

$data_departs = DepartmentsModel::getAll();
?>

<!-- Khung lọc dữ liệu -->
<div>
<form name=frm action="/report/baocaolanhdao/reportview" method="POST" >
<div>
<label><b>Ngày bắt đầu:</b></label>
<?=QLVBDHCommon::calendar($this->fromdate,"fromdate","fromdate") ?>
>>
<?=QLVBDHCommon::calendar($this->todate,"todate","todate") ?>
</div>
<div class=clr></div>
	<div>
		<label><b>Thời gian giao trả:</b></label>
		<?=QLVBDHCommon::calendarFull($this->fromdategt,"fromdategt","fromdategt") ?>
		>>
		<?=QLVBDHCommon::calendarFull($this->todategt,"todategt","todategt") ?>
	</div>
<div class=clr></div>
<div>
<div>
<label><b>Tháng:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/1')">1
<?php 
$year = QLVBDHCommon::getYear();
$d = strtotime($year."-3-1") ;
$d = $d - 86400;
$str_cuoi2 =date('d/m',$d); 
 ?>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')" >2
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3','31/3')">3
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4','30/4')" >4
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5','31/5')">5
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6','30/6')">6
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','31/7')" >7
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8','31/8')" >8
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9','30/9')">9
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/10')">10
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11','30/11')">11
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12','31/12')">12
</div>
<div class=clr></div>
<div>
<label><b>Quí:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/3')">I
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4','30/6')">II
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','30/9')">III
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/12')">IV
</div>
<div class=clr></div>

<div>
<label><b>Năm:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/12')">
</div>
</div>
<div class=clr></div>
<br/>
<div>
<label><b>Chọn phòng ban:</b></label>
<select name="sel_pb[]" id="sel_pb" multiple="multiple" size=5>
	<?php DepartmentsModel::toComboName(); ?>
</select>
</div>
<?php
if($this->param['isphong']==1){
?>
<div class=clr></div>
<div style="float:left">
<label><b>Tình trạng:</b></label>
<select name="sel_tinhtrang" id="sel_tinhtrang" >
<option value="1">Đã tiếp nhận</option>
		<option value="2">Đang xử lý</option>
		<option value="3">Đang xử lý (Sắp trễ hạn)</option>
		<option value="4">Đang xử lý (trễ)</option>
		<option value="8">Đã hoàn thành (trễ)</option>
		<option value="9">Đã hoàn thành (đúng hẹn)</option>
		<option value="11">Đúng hẹn nhưng XL trễ</option>
		<option value="5">Đã thụ lý</option>
		<!--<option value="6">Đã chuyển trả</option>-->
		<option value="7">Đã hoàn thành (chờ công dân nhận)</option>
		<option value="10">Không thụ lý</option>
</select>
</div>
<?php } ?>
<div class="clr"></div>
<br/>
<div style="display:none">
<label><b>Chọn loại công việc:</b></label>
<select name="sel_lcv" id="sel_lcv" >
	<option value=3>Hồ sơ một cửa</option>
</select>
</div>
<div class="clr"></div>
<input type=hidden id=h_isexel name=h_isexel value=0>
<input type=hidden id=CHOICEALL_LOAI name=CHOICEALL_LOAI value=1>
<input type=hidden id=ID_LV_MC name=ID_LV_MC value=-1>
</form>


</div><div>
<?php
if($this->param['isphong']==1){
?>
<input type=button value="In" onclick="
//http://203.210.253.38/report/tiepnhanhosomotcua/reportviewexcel?ID_LV_MC=2&sel_tinhtrang=1&CHOICEALL_LOAI=1&h_isexel=0&ubnd=1&phong=1
document.frm.target='_blank';
document.frm.h_isexel.value =0;
document.frm.action = '/report/tiepnhanhosomotcua/reportviewexcel';
document.frm.submit();
return false;
">
<input type=button value="Excel" onclick="
//http://203.210.253.38/report/tiepnhanhosomotcua/reportviewexcel?ID_LV_MC=2&sel_tinhtrang=1&CHOICEALL_LOAI=1&h_isexel=0&ubnd=1&phong=1
document.frm.target='_self';
document.frm.h_isexel.value =1;
document.frm.action = '/report/tiepnhanhosomotcua/reportviewexcel';
document.frm.submit();
return false;
">
<?php } else {?>
<input type=button value="Hiển thị" onclick="
document.frm.submit();
return false;
">
<?php } ?>
</div>
<div class="clr"></div>

<iframe style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no 
id="list_report" 
name="list_report" >
</iframe>


<script>
function setvalueDateD(value_from,value_to){
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
}
</script>