<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
<form name=frmUpload enctype="multipart/form-data" action="/hscv/file/save" method="post" target="tftemp<?php echo $this->idObject?>">
	<input type="hidden" name="MAX_FILE_SIZE" value="100000000" />
	<table width=100% class="admintable" border=0>
		<tr>
			<td nowrap class=key>Chọn file đính kèm</td>
			<td nowrap><input name="uploadedfile" type="file" /> </td>
		</tr>
	</table>
	    
	<a href="#" onclick="window.parent.document.getElementById('tftemp<?php echo $this->idObject?>').style.display='none'
	return false;"> 
	[ Hủy ] </a>
	<a href="#" onclick="document.frmUpload.submit(); return false;">[ Đính kèm ]</a>
	<input type="hidden" name="idObject" value=<?php echo $this->idObject?> >
	<input type="hidden" name="isTemp" value=<?php echo $this->isTemp?>>
	<input type="hidden" name="year" value=<?php echo $this->year?>>
	<input type="hidden" name="iddiv" value=<?php echo $this->iddiv?>>
	<input type="hidden" name="type" value=<?php echo $this->type?>>
	<input type="hidden" name="from" value=<?php echo $this->from?>>
</form>
<p id=lasttext></p>
</body>
</html>
<script>
function SaveButtonClick(){
	
}
var iframeElement = window.parent.document.getElementById('tftemp<?php echo $this->idObject?>');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop+10)+"px";
iframeElement.width = "100%"; 
</script>