<?php
$this->dojo()->enable();
?>
<form name=frm method="post" action="/wf/activitypool">
	<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo htmlspecialchars($this->search) ?>" class="text_area" onchange="document.frm.page.value=1;document.frm.submit();" />
				<button onclick="document.frm.submit();">Tìm</button>
				<button onclick="document.frm.page.value=1;document.getElementById('search').value='';document.frm.submit();">Làm lại</button>
			</td>
			<td nowrap="nowrap">
				<select name="filter_object" id="filter_object" class="inputbox" size="1" onchange="document.frm.page.value=1;document.frm.submit();">
					<?php 
						echo ClassModel::ToCombo($this->class,$this->filter_object); 
					?>
				</select>
			</td>
		</tr>
	</table>
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>#</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th width="50%">Tên trạng thái mẫu</th>
			<th width="50%">URL</th>
			<th nowrap>Thuộc đối tượng</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="5">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frm.page.value = 1;document.frm.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="50">50</option>
								<option value="100">100</option>
								<script>
									document.frm.limit.value='<?php echo $this->limit ?>';
								</script>
							</select>
						</div>
						<div style="float:right;"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row ){
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row['IP_AP'] ?>'>
			</td>
			<td width=50%>
				<a href="#" onclick = "ItemClick(<?php echo $row['IP_AP'] ?>);">
				<?php echo htmlspecialchars($row['NAME']) ?>
				</a>
			</td>
			<td width=50%>
				<a href="#" onclick = "ItemClick(<?php echo $row['IP_AP'] ?>);">
				<?php echo htmlspecialchars($row['LINK']) ?>
				</a>
			</td>
			<td nowrap>
<?php
	foreach($this->class as $rowc){
		if($rowc['ID_C']==$row['ID_C']){
			echo htmlspecialchars($rowc['NAME']);
			break;	
		}
	}
?>
			</td>
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>
<script>
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","<?=ERR11001002?>");
	if(mess){
		if(confirm("<?=MSG11001002?>")){
			document.frm.action = "/wf/ActivityPool/Delete";
			document.frm.submit();
		}
	}else{
		alert("<?=ERR11001002?>");
	}
}
function AddNewButtonClick(){
	document.frm.action = "/wf/ActivityPool/input";
	document.frm.submit();
}
function ItemClick(id){
	document.frm.action = "/wf/ActivityPool/input/id/"+id;
	document.frm.submit();
}
</script>