<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl65
	{mso-style-parent:style0;
	vertical-align:top;}
.xl66
	{mso-style-parent:style0;
	vertical-align:top;
	white-space:normal;}
.xl67
	{mso-style-parent:style0;
	font-style:italic;}
.xl68
	{mso-style-parent:style0;
	font-style:italic;
	white-space:normal;}
.xl69
	{mso-style-parent:style0;
	mso-number-format:"Short Date";
	vertical-align:top;}
.xl70
	{mso-style-parent:style0;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#D8D8D8;
	mso-pattern:black none;}
.xl71
	{mso-style-parent:style0;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#D8D8D8;
	mso-pattern:black none;
	white-space:normal;}
.xl72
	{mso-style-parent:style0;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border:.5pt solid windowtext;}
.xl73
	{mso-style-parent:style0;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	vertical-align:top;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl74
	{mso-style-parent:style0;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border:.5pt solid windowtext;}
.xl75
	{mso-style-parent:style0;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	vertical-align:top;
	border:.5pt solid windowtext;
	white-space:normal;}

</style>


</head>
<body style="background-color:transparent">
<table border=0 cellpadding=0 cellspacing=0 width=1200 style='border-collapse:
 collapse;table-layout:fixed;width:901pt'>
 <col width=52 style='mso-width-source:userset;mso-width-alt:1901;width:39pt'>
 <col width=88 style='mso-width-source:userset;mso-width-alt:3218;width:66pt'>
 <col width=167 style='mso-width-source:userset;mso-width-alt:6107;width:125pt'>
 <col width=130 style='mso-width-source:userset;mso-width-alt:4754;width:98pt'>
 <col width=137 style='mso-width-source:userset;mso-width-alt:5010;width:103pt'>
 <col width=409 style='mso-width-source:userset;mso-width-alt:14957;width:307pt'>
 <col width=60 style='mso-width-source:userset;mso-width-alt:2194;width:45pt'>
 <col width=157 style='mso-width-source:userset;mso-width-alt:5741;width:118pt'>
 <col width=157 style='mso-width-source:userset;mso-width-alt:5741;width:118pt'>

 <tr height=20 style='height:15.0pt'>
  <td height=20 width=52 style='height:15.0pt;width:39pt'></td>
  <td width=88 style='width:66pt'></td>
  <td width=167 style='width:125pt'></td>
  <td width=130 style='width:98pt'></td>
  <td width=137 style='width:103pt'></td>
  <td width=409 style='width:307pt'></td>
  <td width=60 style='width:45pt'></td>
  <td width=157 style='width:118pt'></td>
  <td width=157 style='width:118pt'></td>
 </tr>
 
 <tr height=60 style='height:45.0pt;mso-xlrowspan:3'>
  <td height=60 colspan=8 style='height:45.0pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl70 style='height:30.0pt'>S&#7889;
  &#273;&#7871;n</td>
  <td rowspan=2 class=xl70>Ngày tháng</td>

  <td rowspan=2 class=xl71 width=167 style='width:125pt'>C&#417; quan ban hành</td>
  <td colspan=2 class=xl70 style='border-left:none'>V&#259;n b&#7843;n
  &#273;&#7871;n</td>
  <td rowspan=2 class=xl71 width=409 style='width:307pt'>Trích y&#7871;u
  n&#7897;i dung</td>
  <td rowspan=2 class=xl70>S&#7889; l&#432;&#7907;ng</td>

  <td rowspan=2 class=xl71 width=157 style='width:118pt'>Chuy&#7875;n cho ai</td>
  <td rowspan=2 class=xl71 width=157 style='width:118pt'>Kết quả</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl70 style='height:15.0pt;border-top:none;border-left:
  none'>S&#7889;</td>
  <td class=xl70 style='border-top:none;border-left:none'>Ngày</td>
 </tr>
<?php foreach($this->data as $row){  ?>
 <tr height=40 style='height:30.0pt'>
  <td height=40 class=xl72 style='height:30.0pt;border-top:none'><?=$row["SODEN"]?></td>
  <td class=xl72 style='border-top:none;border-left:none'><?=QLVBDHCommon::MysqlDateToVnDateNoneZero($row["NGAYDEN"])?></td>
  <td class=xl73 width=167 style='border-top:none;border-left:none;width:125pt'><?=$row["COQUANBANHANH_TEXT"]?></td>
  <td class=xl72 style='border-top:none;border-left:none'><?=$row["SOKYHIEU"]?></td>

  <td class=xl72 style='border-top:none;border-left:none'><?=QLVBDHCommon::MysqlDateToVnDateNoneZero($row["NGAYBANHANH"])?></td>
  <td class=xl73 width=409 style='border-top:none;border-left:none;width:307pt'><?=$row["TRICHYEU"]?></td>
<!--<td nowrap valign=top rowspan=>Quy&#7871;t &#273;&#7883;nh</td>
 	<td nowrap valign=top rowspan=>&#272;inh Th&#7883; Minh Ph&#432;&#417;ng</td>-->
  <td class=xl74 style='border-top:none;border-left:none'><?=$row["SOBAN"]?></td>
  <td class=xl75 width=157 style='border-top:none;border-left:none;width:118pt'><?php 
 	if($row["IS_KHONGXULY"] == 1)
 		echo "Văn bản không xử lý";
 	else{
 		
		$idhscvs = VanbandenreportModel::getHscvsByIdVbd($row["ID_VBD"]);
		
		foreach($idhscvs as $id_hs)
			echo VanbandenreportModel::getNguoiXulyFromVban($id_hs["ID_HSCV"]);
	} ?><span
  style='mso-spacerun:yes'> </span></td>
   <td class=xl75 width=157 style='border-top:none;border-left:none;width:118pt'><?php 
 	if($row["ID_HSCV"] != ""){
		
		$list_vbdi = Ad_XulyvanbandenModel::getListVanbandiByIdHSCV($row["ID_HSCV"]);
		if(count($list_vbdi) > 0){
			foreach($list_vbdi as $vbdi){
				echo $vbdi["SOKYHIEU"]."<br/>";
			}
		}else{
			echo $row["KQ_DEXUAT"] ;
		}
		
	} ?><span
  style='mso-spacerun:yes'> </span></td>
<?php }  ?>
<!--<td nowrap valign=top>""</td> -->
 
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>

 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>

 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>

  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>

  <td class=xl66></td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td class=xl65></td>
  <td class=xl69></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td class=xl65></td>
  <td class=xl69></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td class=xl65></td>
  <td class=xl69></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td class=xl65></td>
  <td class=xl69></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td class=xl65></td>
  <td class=xl69></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td class=xl65></td>
  <td class=xl69></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td class=xl65></td>
  <td class=xl69></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>

  <td class=xl66></td>
  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 colspan=2 class=xl65 style='height:15.0pt;mso-ignore:colspan'></td>
  <td class=xl66></td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl66></td>

  <td class=xl67></td>
  <td class=xl68></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=52 style='width:39pt'></td>
  <td width=88 style='width:66pt'></td>
  <td width=167 style='width:125pt'></td>
  <td width=130 style='width:98pt'></td>

  <td width=137 style='width:103pt'></td>
  <td width=409 style='width:307pt'></td>
  <td width=60 style='width:45pt'></td>
  <td width=157 style='width:118pt'></td>
 </tr>
 <![endif]>
</table>


<p id=lasttext></p>
</body>
</html>
<script>
var iframeElement = window.parent.document.getElementById('reportview');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 

</script>