<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
<link rel=Stylesheet href=stylesheet.css>



</head>
<body style="background-color:transparent">

<table class=adminlist width="100%">
 <thead>
 	<tr>
 		<th nowrap rowspan=2>Số đến</th>
		<th nowrap rowspan=2>Ngày tháng</th>
 		<th  rowspan=2>Cơ quan ban hành</th>
 		<th nowrap colspan=2 style="text-align:center">Văn bản đến</th>
 		<th  rowspan=2 >Trích yếu nội dung</th>
		<th nowrap rowspan=2>Số lượng</th>
		<th  rowspan=2>Chuyển cho ai</th>
		<th  rowspan=2>Kết quả</th>
		<!--<th  rowspan=2>Ghi chú</th> -->
 	</tr>
 	<tr>
 		<th nowrap>Số</th>
 		<th nowrap>Ngày</th>
 		
 	</tr>
 </thead>
 <tbody>
<?php require_once 'qtht/models/LoaiVanBanModel.php';
require_once 'qtht/models/CoquanModel.php'; 
require_once 'qtht/models/DepartmentsModel.php';
require_once 'qtht/models/UsersModel.php';
?>
<?php $nguoixuly ; $phongban; $stt=1; 
$num = count($this->data);

foreach($this->data as $row){ 
 //dem so cot gion nhau
 //if($stt == 1 || $row['ID_HSCV'] != $this->data[$stt-2]['ID_HSCV']){
 
 ?>
	
	<tr>
 	<td nowrap valign=top ><?=$row["SODEN"]?></td>
 	<td nowrap valign=top ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYDEN"]) ?></td>
	<td  width="30%" valign=top ><?=$row["COQUANBANHANH_TEXT"]?> <?php //echo CoquanModel::getNameById($row["ID_CQ"]) ?></td>
 	<td nowrap  valign=top ><?php echo $row["SOKYHIEU"] ?></td>
 	<td nowrap valign=top ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYBANHANH"]) ?></td>
	<td  valign=top width=50% ><?php echo $row["TRICHYEU"] ?></td>
 	
	<!--<td nowrap valign=top rowspan=<?php echo $d ?>><?php echo LoaiVanBanModel::getNameById($row["ID_LVB"]) ?></td>
 	<td nowrap valign=top rowspan=<?php echo $d ?>><?php echo UsersModel::getEmloyeeNameByIdUser($row["NGUOITAO"]) ?></td>-->
 	<td nowrap ><i><?php echo $row["SOBAN"] ?></i></td>
 	<td width="30%">
 	<i><?php 
 	if($row["IS_KHONGXULY"] == 1)
 		echo "Văn bản không xử lý";
 	else{
 		
		$idhscvs = VanbandenreportModel::getHscvsByIdVbd($row["ID_VBD"]);
		
		foreach($idhscvs as $id_hs)
			echo VanbandenreportModel::getNguoiXulyFromVban($id_hs["ID_HSCV"]);
	}
		 ?>
 		
 	</i></td>
 	
	
	<td nowrap valign=top>
	<?php 
	if($row["ID_HSCV"] != ""){
		
		$list_vbdi = Ad_XulyvanbandenModel::getListVanbandiByIdHSCV($row["ID_HSCV"]);
		if(count($list_vbdi) > 0){
			foreach($list_vbdi as $vbdi){
				echo $vbdi["SOKYHIEU"]."<br/>";
			}
		}else{
			echo $row["KQ_DEXUAT"] ;
		}
		
	}
	?>
	</td>
	</tr>
 

<?php  	


	
	
 /*	
 }
 $nguoixuly .= "<br/>".$row["U_SEND"]."(".$row["NAME_DEP"].")"."--".$row['TR_NAME'];
 //$phongban .="<br/>".$row["NAME_DEP"];
 	
 if($row['ID_HSCV'] != $this->data[$stt]['ID_HSCV']){
 	echo "<td>".$nguoixuly."</td>";
 	//echo "<td>".$phongban."</td>";
 	echo "</tr>";
 	$nguoixuly ="";
 	$phongban = "";
 }

 */
  $stt++ ; } ?>
 </tbody>
 <tfoot>
 </tfoot>
</table>


<p id=lasttext></p>
</body>
</html>
<script>
var iframeElement = window.parent.document.getElementById('reportview');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 

</script>