<form enctype="multipart/form-data" name="frmAddLoai"  method="<?php echo $this->form->getAttrib('method');?>" action="/motcua/loai/input">
<fieldset>
	<div style="text-align:right;width:100%">
		Trường có dấu <font color="red">*</font> là bắt buộc nhập
	</div>
	<div align="center"><span class="box_erro_area"><?php echo $this->error; ?></span></div>
	<div class="required">
		<label id="lblTextIput">Mã loại<font color="red">*</font></label>
		<?php echo $this->form->getElement('CODE');?>
    	<span class="box_erro_area">
        	<?php
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('CODE'));
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="required">
		<label id="lblTextIput">Tên loại<font color="red">*</font></label>
		<?php echo $this->form->getElement('TENLOAI');?>
    	<span class="box_erro_area">
        	<?php
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('TENLOAI'));
            ?>
        </span>
	</div>
	<div class="clr"></div>
    <div>
        <div class="required" style="float:left;">
            <label id="lblTextIput">Số ngày xử lý <font color="red">*</font></label>
            <?php echo $this->form->getElement('SONGAYXULY');?>
            <span class="box_erro_area">
                <?php
                    echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('SONGAYXULY'));
                ?>
            </span>
        </div>

        <div class="required" style="float:left;">
            <label id="lblTextIput">Lệ phí <font color="red">*</font></label>
            <?php echo $this->form->getElement('LEPHI');?>
            <span class="box_erro_area">
                <?php
                    echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('LEPHI'));
                ?>
            </span>
        </div>
    </div>
	<div class="clr"></div>
	<div class="required">
		<label id="lblTextIput">Lĩnh vực <font color="red">*</font></label>
		<select NAME=ID_LV_MC>
			<?=linhvucmotcuaModel::ToCombo($this->data,$this->formdata->ID_LV_MC)?>
		</select>
	</div>
	<div class="clr"></div>

    <div>
    <div class="required" style="float:left; display: none;">
		<label id="lblTextIput">Là quy trình UBND <font color="red">*</font></label>
		<input type=checkbox name=ISUBND value=1 <?=($this->formdata->ISUBND==1?"checked":"")?>>
	</div>

	<div class="required" style="float:left;">
		<label id="lblTextIput">Báo trễ khi còn <font color="red">*</font></label>
		<input type=text size=3 name=SAPTRE value=<?=$this->formdata->SAPTRE?>> ngày
	</div>
    </div>

	<div class="clr"></div>
	<div class="optional">
		<label for="ID_DEP_PARENT" id="lblTextIput">Gán vào quy trình</label>
		<?php echo $this->form->getElement('ID_LOAIHSCV');?>
        <span class="box_erro_area">
        	<?php
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('ID_LOAIHSCV'));
            ?>
        </span>
	</div>
	<div class="clr"></div>
    <div class="optional">
		<label id="lblTextIput">Tên viết tắt</label>
		<input type=text name=BUILDNAME value="<?=$this->formdata->BUILDNAME?>" style="width:300px" />
	</div>
	<div class="clr"></div>

	<div class="optional">
		<label id="lblTextIput">Cách thức thực hiện</label>
		<?php echo $this->form->getElement('CACHTHUC_THUCHIEN');?>
        <span class="box_erro_area">
        	<?php
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('CACHTHUC_THUCHIEN'));
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="optional">
		<label id="lblTextIput">Kết quả thực hiện</label>
		<?php echo $this->form->getElement('KETQUA');?>
        <span class="box_erro_area">
        	<?php
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('KETQUA'));
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="optional">
		<label id="lblTextIput">Yêu cầu</label>
		<?php echo $this->form->getElement('YEUCAU');?>
        <span class="box_erro_area">
        	<?php
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('YEUCAU'));
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="optional">
		<label id="lblTextIput">Căn cứ pháp lý</label>
		<?php echo $this->form->getElement('CANCU_PHAPLY');?>
        <span class="box_erro_area">
        	<?php
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('CANCU_PHAPLY'));
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="optional">
		<label id="lblTextIput">Trình tự thực hiện</label>
		<?php echo $this->form->getElement('TRINHTU_THUCHIEN');?>
        <span class="box_erro_area">
        	<?php
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('TRINHTU_THUCHIEN'));
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="optional">
		<label for="ID_DEP_PARENT" id="lblTextIput">Chú thích</label>
		<?php echo $this->form->getElement('CHUTHICH');?>
        <span class="box_erro_area">
        	<?php
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('CHUTHICH'));
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div>
		<label id="lblTextIput">Sao chép thủ tục từ</label>
		<select name=ID_LOAI_MC style="width:300px">
		<?=LoaiModel::ToCombo($this->dataloai,0)?>
		</select>
	</div>
</fieldset>
<input type=hidden name="id" value=<?php echo $this->id?> >
</form>

<script>
	function SaveButtonClick()
	{
		document.frmAddLoai.submit();
	}
	function BackButtonClick()
	{
		document.frmAddLoai.action = "/motcua/loai/";
		document.frmAddLoai.submit();
	}
</script>