<script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
<form name=frmListCustomers method="post" action="/qtht/customers">
	<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo $this->search ?>" class="text_area" onchange="document.frmListCustomers.submit();" />
				<button onclick="document.frmListCustomers.submit();">Tìm</button>
				<button onclick="document.getElementById('search').value='';document.frmListCustomers.submit();">Làm lại</button>
			</td>
			<td nowrap="nowrap" style="display: none">
				<select style="width: 300px;" id="ID_LOAIHOSO" name="ID_LOAIHOSO" onchange="getHoSoCanCo(this.value)">
				<option value="">--------Chọn loại hồ sơ--------</option>
				<?php
					if(count($this->dataloai))
					{
						foreach($this->dataloai as $row)
						{
				?>
				<option label="<?php echo $row["TENLOAI"]; ?>" value="<?php echo $row["ID_LOAIHOSO"]; ?>"><?php echo $row["TENLOAI"]; ?></option>
				<?php
						}
					}
				?>
				</select>
                <select style="width:300px"  name="filter_object" id="filter_object" class="inputbox" size="1" onchange="document.frmListCustomers.submit();">
                    <?php
                        echo ThuTucModel::ToCombo($this->loais,$this->filter_object);
                    ?>
                </select>
            </td>
		</tr>
	</table>
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>#</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th nowrap>Tên</th>
			<th nowrap>Địa chỉ</th>
			<th nowrap>Email</th>
			<th nowrap>Điện thoại</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="7">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frmListCustomers.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="50">50</option>
								<option value="100">100</option>
								<script>
									document.frmListCustomers.limit.value='<?php echo $this->limit ?>';
								</script>
							</select>
						</div>
						<div style="float:right;"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row )
	{
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right" width="10"><?php echo $stt ?></td>
			<td nowrap align="center" width="10">
				<input type=checkbox name=DEL[] value='<?php echo $row['ID'] ?>'>
			</td>
			<td>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID'] ?>);">
				<?php echo htmlspecialchars($row['NAME']) ?></a>
			</td>
			<td><?php echo $row['ADDRESS'];?></td>
			<td><?php echo $row['EMAIL'];?></td>
			<td><?=$row['PHONE']?></td>
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
<input type="hidden" name="comeFrom" value="listForm">
</form>
<script>
jQuery.noConflict();
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","Chọn ít nhất một mục để xoá.");
	if(mess){
		if(confirm("<?php echo 'Bạn muốn xóa mục này!'; ?>")){
			document.frmListCustomers.action = "/qtht/customers/delete";
			document.frmListCustomers.submit();
		}
	}else{
		alert("Chọn ít nhất một mục để xoá.");
	}
}
function AddNewButtonClick()
{
	document.frmListCustomers.action = "/qtht/customers/input";
	document.frmListCustomers.submit();
}
function ItemClick(id)
{
	document.frmListCustomers.action = "/qtht/customers/input/id/"+id;
	document.frmListCustomers.submit();
}
function getHoSoCanCo(idhoso)
{
	(function($) {
		postObject = new Object;
		postObject.id = idhoso;
		$("#filter_object").html('<option value="">--------Chọn thủ tục--------</option>');
		$("#loading_message").html("<div class=fbloading>Cập nhật...</div>");
		$.post("/qtht/customers/gethoso", postObject, function(data)
		{
			if (data.isValid)
			{
				$("#loading_message").html("<div class='fbloading_success'>"+data.message+"...</div>");
				var data=data.data;
				if(data.length>0)
				{
					for(i=0;i<data.length;i++)
					{
						str="<option value='"+data[i]['ID_THUTUC']+"'>"+data[i]['TENTHUTUC']+"</option>";
						$("#filter_object").append(str);
					}	
				}
				else
				{
						str="";
						$("#filter_object").append(str);
				}
											
			}
			else
			{
				$("#loading_message").html("<div class='fbloading_error'>"+data.message+"...</div>");		
			}
		}, "json");	
	})(jQuery);
}
</script>