<table class=adminlist>
	<thead>
		<tr>
			<th nowrap="nowrap">STT</th>
			<th width="100%">File hướng dẫn</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td nowrap="nowrap">1</td>
			<td width="100%"><a href="/images/QLVBDH_v1.5.pdf" target="_blank">Hướng dẫn sử dụng hệ thống Quản lý văn bản điều hành v1.5</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">2</td>
			<td width="100%"><a href="/images/VBDH_LanhDaoCoQuan.pdf" target="_blank">Hướng dẫn sử dụng dành cho Lãnh đạo cơ quan</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">3</td>
			<td width="100%"><a href="/images/VBDH_LanhDaoPhong.pdf" target="_blank">Hướng dẫn sử dụng dành cho Lãnh đạo phòng</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">4</td>
			<td width="100%"><a href="/images/VBDH_ChuyenVien.pdf" target="_blank">Hướng dẫn sử dụng dành cho Chuyên viên</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">5</td>
			<td width="100%"><a href="/images/VBDH_VanThu.pdf" target="_blank">Hướng dẫn sử dụng dành cho Văn thư</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">6</td>
			<td width="100%"><a href="/images/VBDH_ToMotCua.pdf" target="_blank">Hướng dẫn sử dụng dành cho Tổ một cửa</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">7</td>
			<td width="100%"><a href="/images/VBDH_QuanTriHeThong.pdf" target="_blank">Hướng dẫn sử dụng dành cho QTHT</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">8</td>
			<td width="100%"><a href="/images/QLVBDH_Setup.exe" target="_blank">File cài đặt trao đổi, thông báo, nhắc nhở</a></td>
		</tr>
	</tbody>
</table>