<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
.font5
	{color:blue;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.font6
	{color:red;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl65
	{mso-style-parent:style0;
	color:blue;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl66
	{mso-style-parent:style0;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl67
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#D8D8D8;
	mso-pattern:black none;
	white-space:normal;}
.xl68
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	background:#D8D8D8;
	mso-pattern:black none;
	white-space:normal;}
.xl69
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;}
.xl70
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:left;
	vertical-align:top;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl71
	{mso-style-parent:style0;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\[$-1010000\]d\/m\/yy\;\@";}
.xl72
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\[$-1010000\]d\/m\/yy\;\@";
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#D8D8D8;
	mso-pattern:black none;
	white-space:normal;}
.xl73
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\[$-1010000\]d\/m\/yy\;\@";
	text-align:left;
	vertical-align:top;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl74
	{mso-style-parent:style0;
	mso-number-format:"\[$-1010000\]d\/m\/yy\;\@";}

</style>


</head>
<body style="background-color:transparent">
<table border=0 cellpadding=0 cellspacing=0 width=1140 style='border-collapse:
 collapse;table-layout:fixed;width:855pt'>
 <col width=55 style='mso-width-source:userset;mso-width-alt:2011;width:41pt'>
 <col width=107 style='mso-width-source:userset;mso-width-alt:3913;width:80pt'>
 <col width=104 style='mso-width-source:userset;mso-width-alt:3803;width:78pt'>
 <col width=341 style='mso-width-source:userset;mso-width-alt:12470;width:256pt'>
 <col width=191 style='mso-width-source:userset;mso-width-alt:6985;width:143pt'>
 <col width=190 style='mso-width-source:userset;mso-width-alt:6948;width:143pt'>
 <col width=152 style='mso-width-source:userset;mso-width-alt:5558;width:114pt'>
 <tr height=20 style='height:15.0pt'>

  <td height=20 width=55 style='height:15.0pt;width:41pt'></td>
  <td width=107 style='width:80pt'></td>
  <td width=104 style='width:78pt'></td>
  <td width=341 style='width:256pt'></td>
  <td width=191 style='width:143pt'></td>
  <td width=190 style='width:143pt'></td>
  <td width=152 style='width:114pt'></td>
 </tr>
 <tr height=80 style='height:60.0pt;mso-xlrowspan:4'>

  <td height=80 colspan=7 style='height:60.0pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl65 colspan=5 style='height:15.75pt;mso-ignore:colspan'>
  <div style='padding-bottom:20px;padding-top:20px'>
  <?php  
  $arr_thongke = $this->arr_thongke;
  $str_thongke = "Đã xử lý &nbsp;".$arr_thongke["dem_ktxl"] . ($arr_thongke["dem_ktxl_tre"]>0?"(<font color=red> trễ: ".$arr_thongke["dem_ktxl_tre"].")</font>": "");
  $str_thongke .= "&nbsp;( ra VB đi:&nbsp;".$arr_thongke["ktxuly_ravbdi"];
  $str_thongke .=", không ra VB đi:&nbsp;" .$arr_thongke["dem_ktxlluutheodoi"];
  $str_thongke .=", không chuyển xử lý:&nbsp;". $arr_thongke["dem_khongxuly"];
  $str_thongke  .= "; Đang xử lý:&nbsp;".$arr_thongke["dem_dangxl"]."&nbsp;".($arr_thongke["dem_dangxl_tre"]>0?"(<font color=red> trễ : ".$arr_thongke["dem_dangxl_tre"].")</font>":"" ) ;
echo $str_thongke;
  ?>
  <span
  style='mso-spacerun:yes'> </span></div>

  </td>
  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=40 style='height:30.0pt;mso-xlrowspan:2'>
  <td height=40 colspan=7 style='height:30.0pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl67 width=55 style='height:15.75pt;width:41pt'>#</td>

  <td colspan=3 class=xl67 width=552 style='border-left:none;width:414pt'>X&#7917;
  lý v&#259;n b&#7843;n &#273;&#7871;n</td>
  <td colspan=3 class=xl67 width=533 style='border-left:none;width:400pt'>Tình
  hình x&#7917; lý</td>
 </tr>
 <tr height=20 style='height:15.0pt'>

  <td rowspan=2 height=40 class=xl67 width=55 style='height:30.0pt;border-top:
  none;width:41pt'>&nbsp;</td>
  <td rowspan=2 class=xl67 width=107 style='border-top:none;width:80pt'>S&#7889;
  ký hi&#7879;u</td>
  <td rowspan=2 class=xl67 width=104 style='border-top:none;width:78pt'>Cơ quan
  ban hành</td>
  <td rowspan=2 class=xl67 width=341 style='border-top:none;width:256pt'>Trích
  y&#7871;u</td>
  <td rowspan=2 class=xl67 width=191 style='border-top:none;width:143pt'>Ng&#432;&#7901;i
  &#273;ang x&#7917; lý</td>

  <td rowspan=2 class=xl67 width=190 style='border-top:none;width:143pt'>Tr&#7841;ng
  thái</td>
  <td rowspan=2 class=xl68 width=152 style='border-bottom:.5pt solid black;
  border-top:none;width:114pt'>Kết quả xử lý<span
  style='mso-spacerun:yes'>  </span></td>
 </tr>

 <tr height=20 style='height:15.0pt'>
 </tr>
 <?php $stt=1;foreach($this->data as $item){ ?>
 <tr height=63 style='height:47.25pt'>
  <td height=63 class=xl70 width=55 style='height:47.25pt;border-top:none;
  width:41pt'><?=$stt?></td>
  <td class=xl70 width=107 style='border-top:none;border-left:none;width:80pt'>
  <?=$item["SOKYHIEU"]?><br/>
  <i><?=QLVBDHCommon::MysqlDateToVnDate($item["NGAYBANHANH"])?></i>
  </td>
  <td class=xl73 width=104 style='border-top:none;border-left:none;width:78pt'><?=$item["COQUANBANHANH_TEXT"]?></td>
  <td class=xl70 width=341 style='border-top:none;border-left:none;width:256pt'><?=$item["TRICHYEU"]?></td>
  <td class=xl70 width=191 style='border-top:none;border-left:none;width:143pt'><?=$item["NAME_U"]==""?"không có":$item["NAME_U"]."<br/>"."(<i>".$item["NAME_DEP"].")</i>"?></td>
  <td class=xl70 width=190 style='border-top:none;border-left:none;width:143pt'><?php 
		if($item["ID_HSCV"]=="")
		{
			if($item["IS_KHONGXULY"] == 1)
					echo "văn bản không xử lý";
		}
		else if($item["IS_THEODOI"]==1){
			echo "Đang lưu theo dõi";
		}else{
		if($item["IS_FINISH"]==1){
			echo "Đã kết thúc";
		}else{
		
		$dis_hour = QLVBDHCommon::getTreHan($item["DATESEND"],$item["HANXULY"]);
				if($dis_hour > 0){
					
					if($this->id_u == $item_luanchuyen["ID_U_RECEIVE"])
						echo '<font color="Red">đang xử lý (trễ '. (int)($dis_hour/8) .' ngày '.($dis_hour%8).' giờ)</font>';
					else 
						echo 'đang xử lý (trễ '. (int)($dis_hour/8) .' ngày '.($dis_hour%8).' giờ)';
				}
				else{ 
					$con = 0- $dis_hour;
					echo 'đang xử lý (còn '. (int)($con/8) .' ngày '.($con%8).' giờ)';
				}
		}}
		?></td>
  <td class=xl70 width=152 style='border-top:none;border-left:none;width:114pt'><?
		if($item["ID_HSCV"] != "")	{
			$list_vbdi = Ad_XulyvanbandenModel::getListVanbandiByIdHSCV($item["ID_HSCV"]);
			if(count($list_vbdi) > 0){
				//if($item["IS_FINISH"] == 1)
					//$ktxuly_ravbdi++;
				//else
					//$dangxuly_ravbdi++;
				foreach($list_vbdi as $vbdi){
					echo  $vbdi["SOKYHIEU"]."<br/>";
				}
			}
			
			if($item["IS_THEODOI"]==1){
				echo $item["KQ_DEXUAT"];
			}
			
		}


	?></td>

 </tr>
 <?php $stt++;} ?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=55 style='width:41pt'></td>
  <td width=107 style='width:80pt'></td>
  <td width=104 style='width:78pt'></td>
  <td width=341 style='width:256pt'></td>
  <td width=191 style='width:143pt'></td>
  <td width=190 style='width:143pt'></td>

  <td width=152 style='width:114pt'></td>
 </tr>
 <![endif]>
</table>





<p id=lasttext></p>
</body>
</html>
<script>
var iframeElement = window.parent.document.getElementById('reportview');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 

</script>