<?php
$this->dojo()->enable();
?>
<form name=frm method="post" action="/wf/Class/Save" enctype="multipart/form-data" >
<fieldset>
	<legend>Đối tượng</legend>
	<div class="required">
		<label>Tên trạng thái(*)</label>
		<input type=text class=inputbox name=NAME value="<?=$this->data->NAME?>" class="inputText" size="50" maxlength="100">
    	<span class="box_erro_area" id="ERRname"></span>
	</div>
    <div class="required">
		<label>Mã số(*)</label>
		<input type=text class=inputbox name=ALIAS value="<?=$this->data->ALIAS?>" class="inputText" size="50" maxlength="100">
    	<span class="box_erro_area" id="ERRALIAS"></span>
	</div>
	<div class="optional">
		<label>(*) Bắt buộc nhập liệu.</label>
	</div>
</fieldset>
<fieldset>
<legend>Trạng thái thuộc đối tượng</legend>
<table class=adminlist>
	<thead>
		<tr>
			<th nowrap>STT</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DELAP')"></th>
			<th width="100%">Tên trạng thái</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan=3 class=error>Chú ý: bên cạnh tên trạng thái là tên đối tượng của nó.</td>
		</tr>
	</tfoot>
	<tbody>
<?php
	$stt=0;
	$i=0;
	foreach($this->activity as $row){
		$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td>
				<?=$stt?>
			</td>
			<td>
				<input type=checkbox name=DELAP[] value='<?=$row['IP_AP']?>' <?=$row["SEL"]==1?"checked":"" ?>>
			</td>
			<td>
				<?=htmlspecialchars($row["NAME"])?> <i>(<?=$row["CLASS_NAME"]!=""?htmlspecialchars($row["CLASS_NAME"]):"Chưa sử dụng"?>)</i>
			</td>
		</tr>
<?php
		$i = (-1+$i)*-1;
	}
?>
	</tbody>
</table>
</fieldset>
<fieldset>
<legend>Hành động thuộc đối tượng</legend>
<table class=adminlist>
	<thead>
		<tr>
			<th nowrap>STT</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DELTP')"></th>
			<th width="100%">Tên hành động</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan=3 class=error>Chú ý: bên cạnh tên hành động là tên đối tượng của nó.</td>
		</tr>
	</tfoot>
	<tbody>
<?php
	$stt=0;
	$i=0;
	foreach($this->transition as $row){
		$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td>
				<?=$stt?>
			</td>
			<td>
				<input type=checkbox name=DELTP[] value='<?=$row['ID_TP']?>' <?=$row["SEL"]==1?"checked":"" ?>>
			</td>
			<td>
				<?=htmlspecialchars($row["NAME"])?> <i>(<?=$row["CLASS_NAME"]!=""?htmlspecialchars($row["CLASS_NAME"]):"Chưa sử dụng"?>)</i>
			</td>
		</tr>
<?php
		$i = (-1+$i)*-1;
	}
?>
	</tbody>
</table>
</fieldset>
<input type=hidden name=ID_C value="<?php echo $this->data->ID_C; ?>">
<input type=hidden name=page value="<?php echo $this->page; ?>">
<input type=hidden name=limit value="<?php echo $this->limit; ?>">
<input type=hidden name=search value="<?php echo $this->search; ?>">
</form>
<script>
	function SaveButtonClick(){
		var err = true;
		err = err & validateInput("req",document.frm.NAME,"<?=ERR11003003?>");
		err = err & err==true?validateInput("maxlen=50",document.frm.NAME,"<?=ERR11003004?>"):false;
		err = err & validateInput("req",document.frm.ALIAS,"<?=ERR11003005?>");
		err = err & err==true?validateInput("maxlen=20",document.frm.ALIAS,"<?=ERR11003006?>"):false;
		err = err & err==true?validateInput("alnum",document.frm.ALIAS,"<?=ERR11003007?>"):false;
		if(err==true){
			document.frm.submit();
		}
	}
	function BackButtonClick(){
		document.frm.action = "/wf/Class";
		document.frm.submit();
	}
</script>