<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form name="frm" method=post action="/vbdi/banhanh/savesend">
<table class=admintable width=100%>
	<tr>
		<td colspan="2"><span style="margin-left:7px"><b>Ý kiến</b>&nbsp;&nbsp;<textarea rows="2" cols="60" name=NOIDUNG></textarea></span></td>
	</tr>
	<tr>
		<td valign="top" nowrap="nowrap">
			<?php echo QLVBDHCommon::writeMultiSelectDepartmentUser('DEP_NGUOIGUI','NGUOIGUI')?>
			<input type="button" value="Chọn" onclick="InsertIntoArr()" style='margin-left:50px;' /></td>
		<td valign="top" width=100%><div id="listuser"></div></td>
	</tr>
</table>
<input type=hidden name=id value="<?=$this->id?>">
<input type=hidden name=year value="<?=$this->year?>">
</form>
<p id=lasttext></p>
</body>
</html>
<script>
	var arr_user = new Array();
	var arr1 = new Array();
	var arr_user_temp = new Array();
	function SaveButtonClick(){
		var err = true;
		if(err==true){
			document.frm.submit();
		}
	}
	function InsertIntoArr(){
		var opt = document.frm.NGUOIGUI.options;
		for(var i=0;i<opt.length;i++){
			if(opt[i].selected){
				arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,opt[i].value,opt[i].text);
				arr_user_temp[arr_user_temp.length] = new Array(opt[i].value);
			}
		}
	    //arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,document.frm.NGUOIGUI.value,document.frm.NGUOIGUI[document.frm.NGUOIGUI.selectedIndex].innerHTML);
	    arr1[0] = new Array(100,'Tên');
	    arr1[1] = new Array(0,'Xóa');
	    ShowArr('listuser',arr1,arr_user);
	    FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
	}
    /**
	 * Tạo lưới từ 2 mảng
	 * 
	 * @param String idDiv id div hoặc khung chứa lưới
	 * @param int Arr1 mảng chứa tên trường và độ rộng tính theo % của trường
	 * @param int Arr2 mảng chứa dữ liệu của các trường trên
	 * @return html code
	 */
    function ShowArr(idDiv,Arr1,Arr2){
        var html;
	    html = '<table class="adminlist">';
	    html += '<thead>';
	    html += '<tr>';
	    html += '<th nowrap>#</td>';
	    for(i=0;i<Arr1.length;i++)
	    	html += '<th width="' + Arr1[i][0] + '%">' + Arr1[i][1] + '</td>';
	    html += '</tr>';
	    html += '</thead>';
	    html += '<tfoot><tr><th colspan=3 align=left>';
	    html += '<input type=button name=SEND value="Chuyển" onclick="SaveButtonClick();">';
	    html += '</th></tr></tfoot>';
	    html += '<tbody>';
	    	for(i=0;i<Arr2.length;i++){
	    		html += '<tr>';
	    		html += '<td nowrap align="right">' + (i + 1) + '</td>';
	    		html += '<td nowrap>';
	    		html += Arr2[i][2];
	    		html += "<input type=hidden name=ID_U[] value="+Arr2[i][1]+">";
	    		html += '</td>';
	    		html += '<td nowrap>';
	    		html += '<a href="javascript:;" onclick="arr_user_temp.splice('+i+',1);arr_user.splice('+i+',1);ShowArr(\'listuser\',arr1,arr_user);FastReload();return false;">Xóa</a>';
	    		html += '</td>';
	    		html += '</tr>';
	        }
	    	html += '</tbody>';
	    	html += '</table>';
	    //
		    //alert(html);
	    document.getElementById(idDiv).innerHTML = html;
	    resize();    	
	}
	function FastReload(){
	    FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
	}
	function resize(){
		var iframeElement = parent.document.getElementById('iframesend<?=$this->id?>');
		iframeElement.style.height = "" + document.getElementById("lasttext").offsetTop + "px";
		iframeElement.width = "100%";
	}
	resize();
</script>