<form name=frm method="post" action="/auth/user/changepassword">
<table class=admintable>
	<tr>
		<td>Mật khẩu cũ</td>
		<td><input type=password name=oldpass size=30></td>
		<td class=error id=ERRoldpass></td>
	</tr>
	<tr>
		<td>Mật khẩu mới</td>
		<td><input type=password name=newpass size=30></td>
		<td class=error id=ERRnewpass></td>
	</tr>
	<tr>
		<td>Nhập lại mật khẩu mới</td>
		<td><input type=password name=renewpass size=30></td>
		<td class=error id=ERRrenewpass></td>
	</tr>
	<tr>
		<td>Ủy quyền cho</td>
		<td>
			<?= QLVBDHCommon::writeSelectDepartmentUserWithSel("ID_DEP","ID_U",$this->uq['ID_U_UQ'], 1) ?>
		</td>
		<td class=error id=ERRrenewpass></td>
	</tr>
	<tr>
		<td colspan="3"  class=error><?=$this->message?></td>
	</tr>
</table>
<input type=hidden name=ok value=1>
</form>
<script>
function SaveButtonClick(){
	var err = true;
	err = err & validateInput("equ="+document.frm.newpass.value,document.frm.renewpass,"Mật khẩu mới không hợp lệ.");
	if(err==true){
		if(confirm("Bạn có muốn thay đổi các thiết lập không?. Sau khi thay đổi thành công sẽ phải đăng nhập lại.")){
			document.frm.submit();
		}
	}
}
</script>