<form id="containerID" action="/qtht/DanhMucLoaiVanBan/save" method="post" enctype="multipart/form-data" name="datacdform" >
<fieldset>
     <div class="required clearfix">
		<label>Ký hiệu</label>
        <input type="text" name="kyhieu" maxlength="128" value="<?php echo htmlspecialchars($this->kyhieu);?>" class="inputText" size="10" >
    	<span class="box_erro_area" id="ERRkyhieu"></span>
	</div>
	<div class="required clearfix">
		<label>Tên</label>
        <input type="text" name="name" maxlength="128" value="<?php echo htmlspecialchars($this->namebefore);?>" class="inputText" size="10" >
    	<span class="box_erro_area" id="ERRname"></span>
	</div>
	<div class="required clearfix">
		<label>Mã số</label>
        <input type="text" name="code" maxlength="3" value="<?php echo htmlspecialchars($this->codebefore);?>" class="inputText" size="10" >
    	<span class="box_erro_area" id="ERRcode"></span>
	</div>
	<div class="required clearfix">
		<label>Đã được sử dụng</label>
        <?php
            if($this->activeselect == 1){
                echo '<input type="checkbox" value=1 class="inputCheckbox" name="active" checked=checked>';
            }
            else {
                echo '<input type="checkbox" value=1 class="inputCheckbox" name="active">';
            }
        ?>
	</div>
</fieldset>
<input type=hidden name="InputIDLVB" value=<?php echo $this->id?> >
<input type=hidden name="limit" value=<?php echo $this->limit?> >
<input type=hidden name="filter_object" value=<?php echo $this->filter_object?> >
<input type=hidden name="search" value=<?php echo $this->search?> >
<input type=hidden name="page" value=<?php echo $this->page?> >
</form>
<script>
function checkFormData(){
	var str = "Bạn phải nhập tên lĩnh vực văn bản";
	var strerr = validateInput("required",document.datacdform.name,str);
	if(!strerr){
		document.datacdform.name.focus();
		return false;
	}
	str="Tên lĩnh vực không được quá 128 ký tự";
	strerr = validateInput("maxlen=128",document.datacdform.name,str);
	if(!strerr){
		
		document.datacdform.name.focus();
		return false;
	}
	str="Mã Loại văn bản là một chuỗi có đúng 2 ký tự";
	strerr = validateInput("maxlen=2",document.datacdform.code,str);
	if(!strerr){
		document.datacdform.code.focus();
		return false;
	}
	str="Mã Loại văn bản là một chuỗi có đúng 2 ký tự";
	strerr = validateInput("minlen=2",document.datacdform.code,str);
	if(!strerr){
		document.datacdform.code.focus();
		return false;
	}
	return true;
}

function SaveButtonClick(){
	
	//window.showModalDialog( '/DialogTemplate/QueryDialog.html',document);
	if(checkFormData())
		document.datacdform.submit();
}

function BackButtonClick(){
	document.datacdform.action = '/qtht/danhmucloaivanban/index';
	document.datacdform.submit();
}
</script>