<?php/**
      * @author trunglv
      * @version 1.0
      * Lop view the hien khung nhap lieu cho van ban du thao
      */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/calendar.js"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">

<form name=frmUpload enctype="multipart/form-data" action="/hscv/ketquaxuly/save" method="post" target="addKetquaxulyFrm<?php echo $this->idHSCV?>">
	<input type="hidden" name="idHSCV" value=<?php echo $this->idHSCV?> >
	<input type="hidden" name="isTemp" value=<?php echo 1//cho id tam?>>
	<input type="hidden" name="year" value=<?php echo $this->year?>>
	<input type="hidden" name="idOldFile" value=<?php echo $this->idOldFile?>>
	<input type="hidden" name="type" value=2 >
	<input type="hidden" name="idKetqua" value=<?php echo $this->idKetqua?>>
	<input type="hidden" name="iddivParent" value=<?php echo $this->iddivParent ?> >
	
<table width="100%">
	<tr>
		<td nowrap class=key>Ngày Ký:</td>
		<td width="100%"><?=QLVBDHCommon::calendarFull($this->ngayky,"ngayky","ngayky") ?><span class="box_erro_area" ></span></td>
		
	</tr>
	<tr>
		<td nowrap class=key>Người Ký:</td>
		<td width="100%">
		<select name='nguoiky' id='nguoiky'>
			<?=Vb_nguoikyModel::ToCombo($this->datank,0)?>
		</select>
		<span class="box_erro_area" id=ERRnguoiky></span></td>
		
	</tr>
	<tr>
		<td nowrap class=key>Số Ký Hiệu:</td>
		<td width="100%"><input type=text class=inputbox name='sokyhieu' id='sokyhieu' ><span class="box_erro_area" id=ERRsokyhieu></span></td>
		
	</tr>
</table>
</form>


<a href="#" onclick="
	
	var str = 'Bạn phải nhập tên người ký.';
	var strerr = validateInput('required',document.getElementById('nguoiky'),str);
	if(!strerr){
		document.getElementById('nguoiky').focus();
		return false;
	}
	
	var str1 = 'Bạn phải nhập số ký hiệu.';
	var strerr1 = validateInput('required',document.getElementById('sokyhieu'),str1);
	if(!strerr1){
		document.getElementById('sokyhieu').focus();
		return false;
	}
		
	var oData = new Object();
	oData.NGAYKY = getValueById('ngayky');
	oData.NGUOIKY = getValueById('nguoiky');
	oData.SOKYHIEU = getValueById('sokyhieu');
	sendDataToServer(oData,'/hscv/ketquaxuly/save?idHSCV=<?php echo $this->idHSCV ?>&iddivParent=<?php echo $this->iddivParent ?>&year=<?php echo $this->year ?>&idKetqua=<?php echo $this->idKetqua ?>&ngayky='+encodeURI(oData.NGAYKY)+'&nguoiky='+encodeURI(oData.NGUOIKY)+'&sokyhieu='+encodeURI(oData.SOKYHIEU));
	return false;
"
>[ Lưu ]</a>
<a href="javascript:;" onclick="window.parent.document.getElementById('addKetquaxulyFrm<?php echo $this->idHSCV?>').style.display='none';">[ Hủy ]</a>
<br>
<br>
<br>
<br>
<br>
<br>
<p id=lasttext></p>
</body>
</html>
<script>

function checkNhapketquaxuly(){
	var str = "Bạn phải nhập tên .";
	var strerr = validateInput("required",document.frmUpload.nhapketqua,str);
	if(!strerr){
		document.frmUpload.nhapketqua.focus();
		return false;
	}
	return true;
}
function checkFormDataAndSubmit(){

	var str = "Bạn phải nhập người kí.";
	var strerr = validateInput("required",document.frmUpload.nguoiky,str);
	if(!strerr){
		document.frmUpload.nguoiky.focus();
		return false;
	}
	
	var str = "Bạn phải nhập số kí hiệu.";
	var strerr = validateInput("required",document.frmUpload.sokyhieu,str);
	if(!strerr){
		document.frmUpload.sokyhieu.focus();
		return false;
	}
	document.frmUpload.submit();
	return true;
}

function SaveButtonClick(){
	
}
var iframeElement = window.parent.document.getElementById("addKetquaxulyFrm<?php echo $this->idHSCV?>");
iframeElement.style.height = "" +(document.getElementById("lasttext").offsetTop+30)+ "px";
iframeElement.width = "100%";
</script>