<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><?php echo $this->title ?></title>
<script type="text/javascript" src= "<?php echo $this->baseUrl();?>/js/common.js"></script>
</head>
<body>


<?php echo $this->layout()->content; ?>

<!-- My layout , cho danh muc loai van ban , module qtht-->



</body>
</html>