<?php require_once('qtht/models/DepartmentsModel.php');

$data_departs = DepartmentsModel::getAll();
//echo QLVBDHCommon::getTreHan('2009-09-0709:55:35',2);
?>

<!-- Khung lọc dữ liệu -->
<div>
<form name=frm action="/report/baocaolanhdao/indextke" method="POST">
<div>
<label><b>Ngày bắt đầu:</b></label>
<?=QLVBDHCommon::calendar($this->fromdate,"fromdate","fromdate") ?>
>>
<?=QLVBDHCommon::calendar($this->todate,"todate","todate") ?>
</div>
<div class=clr></div>
<div>
<div>
<label><b>Tháng:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/1')">1
<?php 
$year = QLVBDHCommon::getYear();
$d = strtotime($year."-3-1") ;
$d = $d - 86400;
$str_cuoi2 =date('d/m',$d); 
 ?>
<input type="radio" name='sel_timedis' value="2" onclick="setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')" >2
<input type="radio" name='sel_timedis' value="3" onclick="setvalueDateD('1/3','31/3')">3
<input type="radio" name='sel_timedis' value="4" onclick="setvalueDateD('1/4','30/4')" >4
<input type="radio" name='sel_timedis' value="5" onclick="setvalueDateD('1/5','31/5')">5
<input type="radio" name='sel_timedis' value="6" onclick="setvalueDateD('1/6','30/6')">6
<input type="radio" name='sel_timedis' value="7" onclick="setvalueDateD('1/7','31/7')" >7
<input type="radio" name='sel_timedis' value="8" onclick="setvalueDateD('1/8','31/8')" >8
<input type="radio" name='sel_timedis' value="9" onclick="setvalueDateD('1/9','30/9')">9
<input type="radio" name='sel_timedis' value="10"onclick="setvalueDateD('1/10','31/10')">10
<input type="radio" name='sel_timedis' value="11" onclick="setvalueDateD('1/11','30/11')">11
<input type="radio" name='sel_timedis' value="12" onclick="setvalueDateD('1/12','31/12')">12
</div>
<div class=clr></div>
<div>
<label><b>Quý:</b></label>
<input type="radio" name='sel_timedis' value="I" onclick="setvalueDateD('1/1','31/3')">I
<input type="radio" name='sel_timedis' value="II" onclick="setvalueDateD('1/4','30/6')">II
<input type="radio" name='sel_timedis' value="III" onclick="setvalueDateD('1/7','30/9')">III
<input type="radio" name='sel_timedis' value="IV" onclick="setvalueDateD('1/10','31/12')">IV
</div>
<div class=clr></div>

<div>
<label><b>Năm:</b></label>
<input type="radio" name='sel_timedis' value="year" onclick="setvalueDateD('1/1','31/12')">
</div>
</div>
<div class=clr></div>
<br/>
<div>
<label><b>Chọn lĩnh vực:</b></label>
<select name="sel_lv[]" id="sel_lv" multiple="multiple" size=7>
	<option value=0 <?=$this->param['sel_lv'][0]==0?"selected":""?>>[Tất cả lĩnh vực]</option>
	<?php DepartmentsModel::toComboNamelinhvuc($this->param['sel_lv'])?>
</select>
</div>
<div class="clr"></div>
<br/>
<div style="display:none">

</div>
<div class="clr"></div>
<input type=hidden id=h_isexel name=h_isexel value=0>
<input type=button value="Thống kê" onclick="thongke();"><input type=button value="In" onclick="In();"><input type=button value="Xuất excel" onclick="Excel();">
</form>

</div>
<div class="clr"></div>
<?php
global $db;
if(count($this->param['sel_lv'])>=0){
?>
<table class=adminlist>
	<thead>
		<tr>
			<th>Lĩnh vực</th>
			<th>Tiếp nhận</th>
			<th>Đang xử lý</th>
			<th>Đang xử lý (sắp trễ)</th>
			<th>Đang xử lý (trễ)</th>
			<th>Đã hoàn thành (trễ)</th>
			<th>Đã hoàn thành (đúng hẹn)</th>
			<th>Đã thụ lý</th>
			<th>Đã hoàn thành (chờ công dân nhận)</th>
			<th>Không thụ lý</th>
		</tr>
	</thead>
	<tbody>
<?php

if($this->param['sel_lv'][0]==0){
	$r = $db->query("SELECT ID_LV_MC FROM MOTCUA_LINHVUC");
	$row = $r->fetchAll();
	$this->param['sel_lv'] = array();
	foreach($row as $lv){
		$this->param['sel_lv'][] = $lv['ID_LV_MC'];
	}
}

foreach($this->param['sel_lv'] as $lv){
	$r = $db->query("SELECT * FROM MOTCUA_LINHVUC WHERE ID_LV_MC = $lv");
	$row = $r->fetch();
?>
		<tr>
			<td>
				<?=$row['NAME']?>
			</td>
			<td nowrap>
					<?php
						$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(1,$lv,$this->xfromdate,$this->xtodate);
					?>
				<a href="#" onclick="Detail(<?=$lv?>,1,1,1)">
					<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,1,1,0)">
					<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,1,0,1)">
					<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
				</a>
			</td>
			<td nowrap>
					<?php
						$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(2,$lv,$this->xfromdate,$this->xtodate);
					?>
				<a href="#" onclick="Detail(<?=$lv?>,2,1,1)">
					<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,2,1,0)">
					<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,2,0,1)">
					<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
				</a>
			</td>
			<td nowrap>
					<?php
						$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(3,$lv,$this->xfromdate,$this->xtodate);
					?>
				<a href="#" onclick="Detail(<?=$lv?>,3,1,1)">
					<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,3,1,0)">
					<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,3,0,1)">
					<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
				</a>
			</td>
			<td nowrap>
					<?php
						$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(4,$lv,$this->xfromdate,$this->xtodate);
					?>
				<a href="#" onclick="Detail(<?=$lv?>,4,1,1)">
					<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,4,1,0)">
					<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,4,0,1)">
					<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
				</a>
			</td>
			<td nowrap>
					<?php
						$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(8,$lv,$this->xfromdate,$this->xtodate);
					?>
				<a href="#" onclick="Detail(<?=$lv?>,8,1,1)">
					<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,8,1,0)">
					<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,8,0,1)">
					<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
				</a>
			</td>
			<td nowrap>
					<?php
						$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(9,$lv,$this->xfromdate,$this->xtodate);
					?>
				<a href="#" onclick="Detail(<?=$lv?>,9,1,1)">
					<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,9,1,0)">
					<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,9,0,1)">
					<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
				</a>
			</td>
			<td nowrap>
					<?php
						$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(5,$lv,$this->xfromdate,$this->xtodate);
					?>
				<a href="#" onclick="Detail(<?=$lv?>,5,1,1)">
					<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,5,1,0)">
					<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,5,0,1)">
					<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
				</a>
			</td>
			<td nowrap>
					<?php
						$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(7,$lv,$this->xfromdate,$this->xtodate);
					?>
				<a href="#" onclick="Detail(<?=$lv?>,7,1,1)">
					<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,7,1,0)">
					<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,7,0,1)">
					<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
				</a>
			</td>
			<td nowrap>
					<?php
						$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(10,$lv,$this->xfromdate,$this->xtodate);
					?>
				<a href="#" onclick="Detail(<?=$lv?>,10,1,1)">
					<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,10,1,0)">
					<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
				</a>
				<a href="#" onclick="Detail(<?=$lv?>,10,0,1)">
					<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
				</a>
			</td>
		</tr>
<?php
}
?>
	</tbody>
</table>
<?php
}
?>

<script>
function setvalueDateD(value_from,value_to){
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
}
function thongke(){
	document.frm.action = "/report/baocaolanhdao/indextke";
	document.frm.target = "_self";
	document.frm.submit();
}
function In(){
	document.frm.action = "/report/baocaolanhdao/xuatwebtke";
	document.frm.target = "_blank";
	document.frm.submit();
}
function Excel(){
	document.frm.action = "/report/baocaolanhdao/xuatexceltke";
	document.frm.target = "_self";
	document.frm.submit();
}
function Detail(ID_LV_MC,sel_tinhtrang,ubnd,phong){
	document.frm.action = "/report/tiepnhanhosomotcua/reportviewexcel?ID_LV_MC="+ID_LV_MC+"&sel_tinhtrang="+sel_tinhtrang+"&CHOICEALL_LOAI=1&h_isexel=0&ubnd="+ubnd+"&phong="+phong;
	document.frm.target = "_blank";
	document.frm.submit();
}
/*
array(11) { ["baocao_thuong"]=> string(1) "1" ["ngaybaocao"]=> string(0) "" ["fromdate"]=> string(0) "" ["todate"]=> string(0) "" ["fromdategt"]=> string(0) "" ["todategt"]=> string(0) "" ["sel_tinhtrang"]=> string(1) "4" ["ID_LV_MC"]=> string(1) "5" ["CHOICEALL_LOAI"]=> string(1) "1" ["h_isexel"]=> string(1) "0" ["time"]=> string(0) "" 
*/
</script>