<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<?php 
$year = QLVBDHCommon::getYear();
$ktxuly_ravbdi = 0;
$dangxuly_ravbdi = 0;
?>
<div id="div_thongke" style="padding-bottom:20px;padding-top:20px;padding-left:0px" ></div>

<form name="frm">




</form>
</body>

</html>


<script>
var div_thongke = document.getElementById("div_thongke");
var str_thongke ="<font color=blue size=3 ><b>";
str_thongke += "Đã xử lý:&nbsp <?=$arr_thongke["dem_ktxl"]?> <?=$arr_thongke["dem_ktxl_tre"]>0?"(<font color=red> trễ: ".$this->arr_thongke["dem_ktxl_tre"].")</font>":""  ?> " ;
str_thongke+="( ra VB đi:&nbsp <?=$arr_thongke["ktxuly_ravbdi"]?>";
str_thongke+=", không ra VB đi:&nbsp <?=$arr_thongke["dem_ktxlluutheodoi"]?>";
str_thongke+=", không chuyển xử lý:&nbsp <?=$arr_thongke["dem_khongxuly"]?> )";

str_thongke += "; Đang xử lý:&nbsp;<?=$arr_thongke["dem_dangxl"]?>&nbsp;<?=$arr_thongke["dem_dangxl_tre"]>0?"(<font color=red> trễ : ".$arr_thongke["dem_dangxl_tre"].")</font>":""  ?> " ;

str_thongke +="</b></font>";
div_thongke.innerHTML = str_thongke;


var iframeElement = window.parent.document.getElementById('reportview');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 

</script>