<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="tke_files/filelist.xml">
<link rel=Edit-Time-Data href="tke_files/editdata.mso">
<link rel=OLE-Object-Data href="tke_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>nguyennd</o:Author>
  <o:LastAuthor>nguyennd</o:LastAuthor>
  <o:LastPrinted>2009-08-23T03:29:44Z</o:LastPrinted>
  <o:Created>2009-08-23T03:21:24Z</o:Created>
  <o:LastSaved>2009-08-23T03:30:33Z</o:LastSaved>
  <o:Company>Hewlett-Packard</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:1.0in .75in 1.0in .75in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl25
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl26
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl27
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl28
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:right;}
.xl29
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
.xl30
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl31
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:left;
	vertical-align:middle;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl32
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	border:.5pt solid windowtext;
	white-space:normal;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:Scale>73</x:Scale>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>100</x:PageBreakZoom>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>20</x:ActiveRow>
       <x:ActiveCol>2</x:ActiveCol>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>10770</x:WindowHeight>
  <x:WindowWidth>18195</x:WindowWidth>
  <x:WindowTopX>120</x:WindowTopX>
  <x:WindowTopY>75</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]-->
</head>

<body link=blue vlink=purple>

<table x:str border=0 cellpadding=0 cellspacing=0 width=834 style='border-collapse:
 collapse;table-layout:fixed;width:627pt'>
 <col width=173 style='mso-width-source:userset;mso-width-alt:6326;width:130pt'>
 <col width=142 style='mso-width-source:userset;mso-width-alt:5193;width:107pt'>
 <col width=157 style='mso-width-source:userset;mso-width-alt:5741;width:118pt'>
 <col width=149 style='mso-width-source:userset;mso-width-alt:5449;width:112pt'>
 <col width=213 style='mso-width-source:userset;mso-width-alt:7789;width:160pt'>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl24 width=315 style='height:15.75pt;
  width:237pt;line-height:16px'><?=mb_strtoupper($this->config->sys_info->company,"utf-8"). " ".mb_strtoupper($this->config->sys_info->city,"utf-8") ?></td>
  <td class=xl25 width=157 style='width:118pt'></td>
  <td class=xl25 width=157 style='width:118pt'></td>
  <td class=xl25 width=157 style='width:118pt'></td>
  <td class=xl25 width=157 style='width:118pt'></td>
  <td class=xl25 width=157 style='width:118pt'></td>
  <td class=xl25 width=157 style='width:118pt'></td>
  <td colspan=2 class=xl26 width=362 style='width:272pt;line-height:16px'>C&#7896;NG
  HÒA XÃ H&#7896;I CH&#7910; NGH&#296;A VI&#7878;T NAM</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl26 style='height:15.75pt;line-height:16px'><?=mb_strtoupper($this->config->sys_info->motcuaname,"utf-8")?></td>
  <td class=xl25></td>
  <td class=xl25></td>
  <td class=xl25></td>
  <td class=xl25></td>
  <td class=xl25></td>
  <td class=xl25></td>
  <td colspan=2 class=xl27 style='line-height:16px'>&#272;&#7897;c l&#7853;p –
  T&#7921; do – H&#7841;nh phúc</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=3 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td height=21 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td height=21 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td height=21 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td height=21 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td height=21 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td colspan=2 class=xl28 style='line-height:16px'><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=10 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=10 height=21 class=xl26 style='height:15.75pt'>TH&#7888;NG KÊ
  H&#7890; S&#416;</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=10 height=21 class=xl29 style='height:15.75pt'>Từ ngày <?=$this->fromdate?> đến ngày <?=$this->todate?> năm <?=QLVBDHCommon::getYear()?></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
	<td height=21 class=xl30 width=173 style='height:15.75pt;border-top:1px;
  width:130pt'>Lĩnh vực</td>
	<td class=xl30 width=142 style='border-top:1px;border-left:none;width:107pt'>Tiếp nhận</td>
	<td class=xl30 width=142 style='border-top:1px;border-left:none;width:107pt'>Đang xử lý</td>
	<td class=xl30 width=142 style='border-top:1px;border-left:none;width:107pt'>Đang xử lý (sắp trễ)</td>
	<td class=xl30 width=142 style='border-top:1px;border-left:none;width:107pt'>Đang xử lý (trễ)</td>
	<td class=xl30 width=142 style='border-top:1px;border-left:none;width:107pt'>Đã hoàn thành (trễ)</td>
	<td class=xl30 width=142 style='border-top:1px;border-left:none;width:107pt'>Đã hoàn thành (đúng hẹn)</td>
	<td class=xl30 width=142 style='border-top:1px;border-left:none;width:107pt'>Đã thụ lý (đã trả)</td>
	<td class=xl30 width=142 style='border-top:1px;border-left:none;width:107pt'>Đã hoàn thành (chờ công dân nhận)</td>
	<td class=xl30 width=142 style='border-top:1px;border-left:none;width:107pt'>Không thụ lý</td>
 </tr>
 <?php
 global $db;
 if($this->param['sel_lv'][0]==0){
	$r = $db->query("SELECT ID_LV_MC FROM MOTCUA_LINHVUC");
	$row = $r->fetchAll();
	$this->param['sel_lv'] = array();
	foreach($row as $lv){
		$this->param['sel_lv'][] = $lv['ID_LV_MC'];
	}
}

foreach($this->param['sel_lv'] as $lv){
	$r = $db->query("SELECT * FROM MOTCUA_LINHVUC WHERE ID_LV_MC = $lv");
	$row = $r->fetch();
?>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl31 width=173 style='height:15.75pt;border-top:none;
  width:130pt'><?=$row['NAME']?></td>
  <td class=xl32 align=right style='border-top:none;border-left:none' x:num>
	<?php
		$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(1,$lv,$this->xfromdate,$this->xtodate);
	?>
	<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
	<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
	<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
</td>
  <td class=xl32 align=right style='border-top:none;border-left:none' x:num>
	<?php
		$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(2,$lv,$this->xfromdate,$this->xtodate);
	?>
	<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
	<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
	<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
</td>
  <td class=xl32 align=right style='border-top:none;border-left:none' x:num>
	<?php
		$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(3,$lv,$this->xfromdate,$this->xtodate);
	?>
	<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
	<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
	<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
</td>
<td class=xl32 align=right style='border-top:none;border-left:none' x:num>
	<?php
		$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(4,$lv,$this->xfromdate,$this->xtodate);
	?>
	<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
	<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
	<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
</td>
<td class=xl32 align=right style='border-top:none;border-left:none' x:num>
	<?php
		$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(8,$lv,$this->xfromdate,$this->xtodate);
	?>
	<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
	<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
	<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
</td>
<td class=xl32 align=right style='border-top:none;border-left:none' x:num>
	<?php
		$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(9,$lv,$this->xfromdate,$this->xtodate);
	?>
	<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
	<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
	<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
</td>
<td class=xl32 align=right style='border-top:none;border-left:none' x:num>
	<?php
		$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(5,$lv,$this->xfromdate,$this->xtodate);
	?>
	<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
	<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
	<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
</td>
<td class=xl32 align=right style='border-top:none;border-left:none' x:num>
	<?php
		$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(7,$lv,$this->xfromdate,$this->xtodate);
	?>
	<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
	<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
	<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
</td>
<td class=xl32 align=right style='border-top:none;border-left:none' x:num>
	<?php
		$arrkq = TiepnhanhosomotcuaModel::CountHosoByLinhVuc(10,$lv,$this->xfromdate,$this->xtodate);
	?>
	<?php echo "<B>Tổng:</B> ".$arrkq[0]."<br>"; ?>
	<?php echo "<B>UBND:</B> ".(0+$arrkq[1])."<br>"; ?>
	<?php echo "<B>Phòng:</B> ".$arrkq[2]; ?>
</td>
</tr>
 <?php } ?>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=5 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=9 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td class=xl26>Ng&#432;&#7901;i l&#7853;p</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=9 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td class=xl26></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=9 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td class=xl26></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=9 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td class=xl26><?=$this->user->FULLNAME?></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=173 style='width:130pt'></td>
  <td width=142 style='width:107pt'></td>
  <td width=157 style='width:118pt'></td>
  <td width=149 style='width:112pt'></td>
  <td width=213 style='width:160pt'></td>
 </tr>
 <![endif]>
</table>

</body>

</html>
