<?php require_once('qtht/models/DepartmentsModel.php');

$data_departs = DepartmentsModel::getAll();
?>

<!-- Khung lọc dữ liệu -->
<div>
<form name=frm action="/report/tamnghivanghihan/index" method="POST" target="reportview">
<div>
<label><b>Ngày bắt đầu:</b></label>
<?=QLVBDHCommon::calendar($this->fromdate,"fromdate","fromdate") ?>
<script> function ChangeDate(){
	document.getElementById('ngaygio').value ="";
}  </script>
>>
<?=QLVBDHCommon::calendar($this->todate,"todate","todate") ?>
<script> function ChangeDate(){
	document.getElementById('ngaygio').value ="";
}  </script>
</div>
<div class=clr></div>
<div>
<div>
<label><b>Tháng:</b></label>
<input type="radio" name='sel_timedis' onclick="document.getElementById('ngaygio').value= 'THÁNG 1';setvalueDateD('1/1','31/1')">1
<?php 
$year = QLVBDHCommon::getYear();
$d = strtotime($year."-3-1") ;
$d = $d - 86400;
$str_cuoi2 =date('d/m',$d); 
 ?>
<input type="radio" name='sel_timedis' value="2" onclick="document.getElementById('ngaygio').value= 'THÁNG 2';setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')" >2
<input type="radio" name='sel_timedis' value="3" onclick="document.getElementById('ngaygio').value= 'THÁNG 3';setvalueDateD('1/3','31/3')">3
<input type="radio" name='sel_timedis' value="4" onclick="document.getElementById('ngaygio').value= 'THÁNG 4';setvalueDateD('1/4','30/4')" >4
<input type="radio" name='sel_timedis' value="5" onclick="document.getElementById('ngaygio').value= 'THÁNG 5';setvalueDateD('1/5','31/5')">5
<input type="radio" name='sel_timedis' value="6" onclick="document.getElementById('ngaygio').value= 'THÁNG 6';setvalueDateD('1/6','30/6')">6
<input type="radio" name='sel_timedis' value="7" onclick="document.getElementById('ngaygio').value= 'THÁNG 7';setvalueDateD('1/7','31/7')" >7
<input type="radio" name='sel_timedis' value="8" onclick="document.getElementById('ngaygio').value= 'THÁNG 8';setvalueDateD('1/8','31/8')" >8
<input type="radio" name='sel_timedis' value="9" onclick="document.getElementById('ngaygio').value= 'THÁNG 9';setvalueDateD('1/9','30/9')">9
<input type="radio" name='sel_timedis' value="10"onclick="document.getElementById('ngaygio').value= 'THÁNG 10';setvalueDateD('1/10','31/10')">10
<input type="radio" name='sel_timedis' value="11" onclick="document.getElementById('ngaygio').value= 'THÁNG 11';setvalueDateD('1/11','30/11')">11
<input type="radio" name='sel_timedis' value="12" onclick="document.getElementById('ngaygio').value= 'THÁNG 12';setvalueDateD('1/12','31/12')">12
</div>
<div class=clr></div>
<div>
<label><b>Quý:</b></label>
<input type="radio" name='sel_timedis' value="I" onclick="document.getElementById('ngaygio').value= 'QUÝ 1';setvalueDateD('1/1','31/3')">I
<input type="radio" name='sel_timedis' value="II" onclick="document.getElementById('ngaygio').value= 'QUÝ 2';setvalueDateD('1/4','30/6')">II
<input type="radio" name='sel_timedis' value="III" onclick="document.getElementById('ngaygio').value= 'QUÝ 3';setvalueDateD('1/7','30/9')">III
<input type="radio" name='sel_timedis' value="IV" onclick="document.getElementById('ngaygio').value= 'QUÝ 4';setvalueDateD('1/10','31/12')">IV
</div>
<div class=clr></div>
<div>
<label><b>Năm:</b></label>
<input type="radio" name='sel_timedis' value="year" onclick="document.getElementById('ngaygio').value= 'TRONG';setvalueDateD('1/1','31/12')">
</div>
</div>
<div style="display:none">
</div>
<div class="clr"></div>
<input type=hidden id=h_isexel name=h_isexel value=0>
<input type=hidden id=ngaygio name=ngaygio value="">
<div>
<div title="Hiện thị báo cáo" style="float:left;background-color:#C0C0C0;border:1px solid #888888;cursor:pointer;margin:2px;
padding:2px 2px;position:relative;white-space:nowrap;width:100px;height:25px" 
onclick="
document.frm.target='reportview';
document.frm.h_isexel.value = 0;
document.frm.action = '/report/tamnghivanghihan/reportview';
document.frm.submit();
return false;">
<img src="/images/report_show.jpg" width="20" height="20"></img>
<b>Hiển thị</b>
</div>
<div title="Hiện thị báo cáo" style="float:left;background-color:#C0C0C0;border:1px solid #888888;cursor:pointer;margin:2px;
padding:2px 2px;position:relative;white-space:nowrap;width:100px;height:25px" 
onclick="
document.frm.target='_blank';
document.frm.h_isexel.value = 0;
document.frm.action = '/report/tamnghivanghihan/reporttnnhexcel';
document.frm.submit();
return false;">
<img src="/images/report_show.jpg" width="20" height="20"></img>
<b>In</b>
</div>
<div title="Hiện thị báo cáo" style="float:left;background-color:#C0C0C0;border:1px solid #888888;cursor:pointer;margin:2px;
padding:2px 2px;position:relative;white-space:nowrap;width:100px;height:25px" 
onclick="
document.frm.target='reportview';
document.frm.h_isexel.value = 1;
document.frm.action = '/report/tamnghivanghihan/reporttnnhexcel';
document.frm.submit();
return false;">
<img src="/images/report_show.jpg" width="20" height="20"></img>
<b>Xuất ra Excel</b>
</div>

</div>
</form>
</div>
<div class=clr></div>
<br>
<div>
<iframe style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no id="reportview" name="reportview" >
</iframe>
</div>
<script>
function setvalueDateD(value_from,value_to){
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
}
</script>