<?php 
require_once 'qtht/models/gen_masoModel.php';
?>
<form name="frm" action="<?echo $this->baseUrl()?>/qtht/DanhMucMaSo" method="post"> 
<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>STT</th>
			<th nowrap>Loại mã số</th>
			<th width=100%>Định dạng</th>
			<th nowrap>Độ dài</th>
		</tr>
	</thead>
	
	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row ){
	$stt++;
?>
	<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap >
				<?php if($stt == 1){echo'Mã số Văn bản đến';}else{
				if($stt == 2 ){
					echo "Mã số văn bản đi";}else{
					echo 'Mã số Hồ sơ một cửa';} } ?>				
			</td>
			<td width=100%>
		<?php $len = 0; for($i = 0 ; $i < count($row); $i++){ 
				$len += $row[$i]['LENGTH'];
			?>
			<input type=checkbox name=DEL[] value='<?php echo $row[$i]["ID_MASO"] ?>'>
			--<a href=# onclick = "ItemClick(<?php echo $row[$i]["ID_MASO"]?>);"> 
			<?php echo $row[$i]['TEN'];?>(<?php echo "độ dài:".$row[$i]['LENGTH'].',thứ tự:'.$row[$i]['ORDER'] ?>)<a> --
		<?php }?>
			</td>
			<td nowrap> <?php echo $len ?></td>
		</tr>
<?php
	
}
?>	
	</tbody>
</table>					

</form>

<script>
function DeleteButtonClick()
{
	var ln = 0;
	var arr = document.getElementsByName('DEL[]');
	for(var i = 0 ; i < arr.length ;i++ )
	{
		
		if(arr[i].checked == true)
		{
			ln = 1;
		}
	}
	if(ln == 1)
	{
		if(confirm("<?php echo "Bạn có muốn xóa không"; ?>")){
			//document.URL=
			document.frm.action="/qtht/DanhMucMaSo/delete";
			document.frm.method="post";
			document.frm.submit();
		}
	}
	else
	{
		alert("Bạn phải một dòng chọn để xóa");
	}
}

function AddNewButtonClick(){
	//document.URL = "/qtht/DanhMucCoQuan/input";
	document.frm.action="/qtht/DanhMucMaSo/input";
	document.frm.method="post";
	document.frm.submit();
	
}
function ItemClick(id){
	//document.URL = "/qtht/DanhMucCoQuan/input/idCoQuan/"+id;
	document.frm.action="/qtht/DanhMucMaSo/input/id/"+id;;
	document.frm.method="post";
	document.frm.submit();
}
</script>
