<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script type="text/javascript" src="/js/calendar.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<table>
	<tr>
		<td valign="top">Công việc</td>
		<td valign="top"><?=$this->NOIDUNG?></td>
	</tr>
	<tr>
		<td valign="top">Thời gian</td>
		<td valign="top"><?=$this->NGAY?></td>
	</tr>
	<tr>
		<td valign="top">Nhắc nhở</td>
		<td valign="top">Ngày <?=QLVBDHCommon::calendarFull("","ENDDAY","ENDDAY")?> Giờ<input type=text name=ENDTIME size=5 value="<?=$this->ENDTIME?>" onblur="getFullTime(this)"></td>
	</tr>
</table>
</body>
</html>