<?php
$weekday = array("Chủ nhật","Thứ hai","Thứ ba","Thứ tư","Thứ năm","Thứ sáu","Thứ bảy");
?>
<form name=frm method=post action="/lichcttext/index/savep" onmousedown="document.getElementById('car_alarm').style.display='none'">
<div>

<span style="float:left;margin-bottom:5px;width:100%">
	Chọn ngày <?=QLVBDHCommon::calendar($this->BEGINDATE,"BEGINDATE","BEGINDATE")?><span style="">
<?=QLVBDHCommon::writeSelectDepartmentUserWithSelAndAction("ID_DEP","ID_U",$this->ID_U,1,'document.frm.action="/lichcttext/index/index";document.frm.submit();')?>
<script>document.frm.ID_DEP.value="<?=$this->ID_DEP?>";
FillComboByComboWithSel(document.frm.ID_DEP,document.getElementById("ID_U"),ARR_ID_U,<?=$this->ID_U?>);
</script>
</span>
    <img src="/images/icon/tuantiep.png" style="float:right;padding: 5px 5px 5px 5px; cursor: pointer;" href="#" onclick="document.frm.action='/lichcttext/index/index';document.frm.target='';document.frm.BEGINDATE.value='<?=$this->nextweek?>';document.frm.submit();" />
    <img src="/images/icon/tuantruoc.png" style="float:right;margin-right:3px;padding: 5px 0px 5px 5px; cursor: pointer;" onclick="document.frm.action='/lichcttext/index/index';document.frm.target='';document.frm.BEGINDATE.value='<?=$this->preweek?>';document.frm.submit();" />
</span>
</div>
<div class=clr></div>
<div id=car_container></div>
<div id=car_alarm style="position:absolute;background-color: white;display:none">
<table width="300" border=1 style="border-collapse: collapse" onmousedown='cancelEvent(event)'>
	<tr>
		<td valign="top" nowrap="nowrap"><b>Công việc</b></td>
		<td valign="top" width="100%"><span id=car_alarm_noidung></span></td>
	</tr>
	<tr>
		<td valign="middle" nowrap="nowrap"><b>Ngày</b></td>
		<td valign="middle" width="100%">
		<span id=car_alarm_ngay></span>
		&nbsp;lúc <input type=text name=NHACNHO_TIME_HOUR size=1 maxlength="2" value="" onkeypress="return isNumberKey(event)"> giờ
		<input type=text name=NHACNHO_TIME_MINUTE size=1 maxlength="2" value="" onkeypress="return isNumberKey(event)"> phút
		</td>
	</tr>
	<tr>
		<td nowrap="nowrap"><b>Báo trước</b></td>
		<td valign="top" width="100%"><input type=text name=BEFORE size=2> Phút</td>
	</tr>
<?php
	$actidsms = ResourceUserModel::getActionByUrl("qtht","danhmucnguoidung","sms");
	$actidemail = ResourceUserModel::getActionByUrl("qtht","danhmucnguoidung","email");
	if(ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actidemail[0])||ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actidsms[0])){
?>
	<tr>
<?php 
	}else{
?>
	<tr style="display:none">
<?php
	} 
?>		
		<td nowrap="nowrap"><b>Nhắc nhở qua</b></td>
		<td valign="top" width="100%">
		<?php if(ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actidsms[0])){ ?><input type=checkbox name=SMS value=1>SMS <?php } ?>
		<?php if(ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actidemail[0])){ ?><input type=checkbox name=EMAIL value=1>Email</td> <?php } ?>
	</tr>

	<tr>
		<td colspan="2" class="error" id=car_alarm_error></td>
	</tr>
	<tr>
		<td colspan="2" align="center">
			<input type=button value="Đồng ý" onclick="if(checkalarm()){document.frm.action='/lichcttext/index/alarm/code/accept';document.frm.submit();}"><input id="car_button_cancel" type=button value="Hủy nhắc nhở" onclick="document.frm.action='/lichcttext/index/alarm/code/delete';document.frm.submit();">
		</td>
	</tr>
</table>
<input type=hidden name=ID_LCT_P_ALARM>
<input type=hidden name=NHACNHO>
</div>
</form>
<div id="test" contenteditable="true"></div>
<script>
	var issave=false;
	HasEvent = false;
	var data = new Array();
	<?php 
		for($i=0;$i<7;$i++){
	?>
	data[<?=$i?>] = new Array();
	data[<?=$i?>][0] = new Array("<?=$weekday[$this->data[$i][0][0]]?>","<?=$this->data[$i][0][1]?>","<?=$this->data[$i][0][2]?>");
	<?php
			for($k=1;$k<=3;$k++){
	?>
	data[<?=$i?>][<?=$k?>]  = new Array();
	<?php
				if(count($this->data[$i][$k])==0){
	?>
	data[<?=$i?>][<?=$k?>][0] = new Array(
			"","","","","","","","","","","<?=$this->autoaddcq==1?"1":"0"?>","","",""
	);
	<?php
				}else{
					for($j=0;$j<count($this->data[$i][$k]);$j++){
	?>
	data[<?=$i?>][<?=$k?>][<?=$j?>] = new Array(
		<?=$this->data[$i][$k][$j]["ID_LCT_P"]?>,						//id
		"<?=str_replace(chr(13).chr(10),'\n',htmlspecialchars($this->data[$i][$k][$j]['NOIDUNG']))?>",												//noi dung
		"<?=str_replace(chr(13).chr(10),'\n',htmlspecialchars($this->data[$i][$k][$j]['THANHPHAN']))?>",												//thanh phan
		"<?=str_replace(chr(13).chr(10),'\n',htmlspecialchars($this->data[$i][$k][$j]['DIADIEM']))?>",												//dia diem
		"<?=$this->data[$i][$k][$j]['IS_TONGHOP']?>",
		"<?=$this->data[$i][$k][$j]['NHACNHO']?>",
		"<?=QLVBDHCommon::MysqlDateToVnDate($this->data[$i][$k][$j]['NGAY'])?>",
		"<?=date("d/m/Y",strtotime($this->data[$i][$k][$j]['NHACNHO']))?>",
		"<?=date("H:i",strtotime($this->data[$i][$k][$j]['NHACNHO']))?>",
		"<?=$this->data[$i][$k][$j]['BEFORE']?>",
		"<?=$this->data[$i][$k][$j]['IS_UPTOCQ']?>",
		"<?=$this->data[$i][$k][$j]['SMS']?>",
		"<?=$this->data[$i][$k][$j]['EMAIL']?>",
		"<?=str_replace(chr(13).chr(10),'\n',htmlspecialchars($this->data[$i][$k][$j]['GHICHU']))?>"
	);
	<?php
					}
				}
			}
		}
	?>
	function DrawGrid(){
		//var oldheight = document.
		var html="";
		html += '<table width="100%" border=1 class=car2_table>';
			html += '<tr class=car2_header>';
				html += '<td colspan="2" nowrap>Ngày</td>';
				<?php if($this->isuptocq==1){ ?>
				html += '<td nowrap><img src="/images/chuyenlencq.gif"></td>';
				<?php } ?>
				html += '<td width=50%>Nội dung</td>';
				html += '<td width=15%>Thành phần</td>';
				html += '<td width=15%>Địa điểm</td>';
				html += '<td width=20%>Ghi chú</td>';
				<?php if($this->lock==0){ ?>
				html += '<td nowrap>&nbsp;</td>';
				<?php } ?>
				<?php if($this->lock==0){ ?>
				html += '<td align=center nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,\'DELETE\')"></td>';
				<?php } ?>
			html += '</tr>';
		for(var i=0;i<data.length;i++){
			var rowspan_sang = data[i][1].length==0?1:data[i][1].length;
			var rowspan_chieu = data[i][2].length==0?1:data[i][2].length;
			var rowspan_toi = 0;
			<?php if($this->config->lct->bandem==1){?>
			var rowspan_toi =  data[i][3].length==0?1:data[i][3].length;
			<?php } ?>
			var rowspan_thu = rowspan_sang+rowspan_chieu+rowspan_toi;
			var j=0;

			//in buoi sang
			html += '<tr>';
				html += '<td rowspan="'+rowspan_thu+'" nowrap class=car2_day>'+data[i][0][0]+'<br>'+data[i][0][1]+'</td>';
				html += '<td rowspan="'+rowspan_sang+'" class=car2_content_1>S</td>';
			if(data[i][1].length==0){
				html += DrawOneCarlendar(i,1,j,true);
			}else{
				html += DrawOneCarlendar(i,1,j,false);
			}
			html += '</tr>';
			for(j=1;j<data[i][1].length;j++){
				html += '<tr>';
				html += DrawOneCarlendar(i,1,j,false);
				html += '</tr>';
			}

			//buoi chieu
			j = 0;
			html += '<tr>';
				html += '<td rowspan="'+rowspan_chieu+'" class=car2_content_2>C</td>';
			if(data[i][2].length==0){
				html += DrawOneCarlendar(i,2,j,true);
			}else{
				html += DrawOneCarlendar(i,2,j,false);
			}
			html += '</tr>';
			for(j=1;j<data[i][2].length;j++){
				html += '<tr>';
				html += DrawOneCarlendar(i,2,j,false);
				html += '</tr>';
			}
			<?php if($this->config->lct->bandem==1){?>
			//buoi toi
			j = 0;
			html += '<tr>';
				html += '<td rowspan="'+rowspan_toi+'" class=car2_content_3>T</td>';
			if(data[i][3].length==0){
				html += DrawOneCarlendar(i,3,j,true);
			}else{
				html += DrawOneCarlendar(i,3,j,false);
			}
			html += '</tr>';
			for(j=1;j<data[i][3].length;j++){
				html += '<tr>';
				html += DrawOneCarlendar(i,3,j,false);				
				html += '</tr>';
			}
			<?php } ?>
		}
		html += '</table>';
		document.getElementById("car_container").innerHTML = html;
		var objtextarea = document.getElementsByTagName("textarea");
		for(var i=0;i<objtextarea.length;i++){
			fitToText(objtextarea[i]);
		}
	}
	DrawGrid();
	
	function fitToText(obj)
	{
		//if(document.layers){
			var text = obj;
			if ( !text )      return;     
			text.style.height = "15px";
			text.style.height = text.scrollHeight + "px";
		//}
	}
	function setCaretPosition(ctrl, pos){
		if(ctrl.setSelectionRange)
		{
			ctrl.focus();
			ctrl.setSelectionRange(pos,pos);
		}
		else if (ctrl.createTextRange) {
			var range = ctrl.createTextRange();
			range.collapse(true);
			range.moveEnd('character', pos);
			range.moveStart('character', pos);
			range.select();
		}
	}
	function SaveButtonClick(){
		if(issave==false){
			issave=true;
			document.frm.submit();
		}
	}
	function DrawOneCarlendar(i,buoi,j,isnew){
		var html="";
		if(isnew){
			
			<?php 
			
			if($this->isuptocq==1){ ?>
			html += '<td valign=top><input title="Chuyển thành lịch cơ quan" type=checkbox <?=$this->autoaddcq==1?"checked":""?> onclick="checkuptocq(this,'+i+','+buoi+','+j+')"><input type=hidden name=CHECK[] id=CHECK_'+i+'_'+buoi+'_'+j+' value="<?=$this->autoaddcq==1?"1":"0"?>"></td>';
			<?php } ?>
			html += '<td valign=top width=50% class=car2_content_'+buoi+' onclick="if(window.DIV_'+"NOIDUNG_"+i+"_"+buoi+"_"+j+')window.DIV_'+"NOIDUNG_"+i+"_"+buoi+"_"+j+'.focus();">'+createTextArea("NOIDUNG_"+i+"_"+buoi+"_"+j,"NOIDUNG[]","Update("+i+","+buoi+","+j+",1)","",data[i][buoi][j][4]==1?"lcttextarea_tonghop":"lcttextarea")+'</td>';
			html += '<td valign=top  width=15% class=car2_content_'+buoi+' onclick="if(window.DIV_'+"THANHPHAN_"+i+"_"+buoi+"_"+j+')window.DIV_'+"THANHPHAN_"+i+"_"+buoi+"_"+j+'.focus();">'+createTextArea("THANHPHAN_"+i+"_"+buoi+"_"+j,"THANHPHAN[]","Update("+i+","+buoi+","+j+",2)","",data[i][buoi][j][4]==1?"lcttextarea_tonghop":"lcttextarea")+'</td>';
			html += '<td valign=top  width=15% class=car2_content_'+buoi+' onclick="if(window.DIV_'+"DIADIEM_"+i+"_"+buoi+"_"+j+')window.DIV_'+"DIADIEM_"+i+"_"+buoi+"_"+j+'.focus();">'+createTextArea("DIADIEM_"+i+"_"+buoi+"_"+j,"DIADIEM[]","Update("+i+","+buoi+","+j+",3)","",data[i][buoi][j][4]==1?"lcttextarea_tonghop":"lcttextarea")+'</td>';
			html += '<td valign=top  width=20% class=car2_content_'+buoi+' onclick="if(window.DIV_'+"GHICHU_"+i+"_"+buoi+"_"+j+')window.DIV_'+"GHICHU_"+i+"_"+buoi+"_"+j+'.focus();">'+createTextArea("GHICHU_"+i+"_"+buoi+"_"+j,"GHICHU[]","Update("+i+","+buoi+","+j+",13)","",data[i][buoi][j][4]==1?"lcttextarea_tonghop":"lcttextarea")+'</td>';
			<?php if($this->lock==0){ ?>
			html += '<td valign=top nowrap class=car2_content_'+buoi+'><div style="width:80px;"><input type=hidden name=NGAY[] value="'+data[i][0][2]+'"><input type=hidden name=BUOI[] value='+buoi+'><input type=hidden name=ID_LCT_P[] value=""><img src="/images/alarm_add_above.gif" onclick="AddAbove('+i+','+buoi+','+j+')" style="cursor:pointer" title="Thêm dưới"><img src="/images/alarm_add_top.gif" onclick="AddAbove('+i+','+buoi+','+(j-1)+')" style="cursor:pointer" title="Thêm trên"></div></td>';
			<?php } ?>
			<?php if($this->lock==0){ ?>
			html += '<td valign=top align=center class=car2_content_'+buoi+'><input type=checkbox name=DELETE[] value=""></td>';
			<?php } ?>
		}else{
			<?php if($this->isuptocq==1){ ?>
			html += '<td valign=top><input title="Chuyển thành lịch cơ quan" type=checkbox '+(data[i][buoi][j][10]=="1"?"checked":"")+' onclick="checkuptocq(this,'+i+','+buoi+','+j+')"><input type=hidden name=CHECK[] id=CHECK_'+i+'_'+buoi+'_'+j+' value="'+data[i][buoi][j][10]+'"></td>';
			<?php } ?>
			html += '<td valign=top width=50% class=car2_content_'+buoi+' onclick="if(window.DIV_'+"NOIDUNG_"+i+"_"+buoi+"_"+j+')window.DIV_'+"NOIDUNG_"+i+"_"+buoi+"_"+j+'.focus();">'+createTextArea("NOIDUNG_"+i+"_"+buoi+"_"+j,"NOIDUNG[]",data[i][buoi][j][1],"Update("+i+","+buoi+","+j+",1)",data[i][buoi][j][4]==1?"lcttextarea_tonghop":"lcttextarea")+'</td>';
			html += '<td valign=top  width=15% class=car2_content_'+buoi+' onclick="if(window.DIV_'+"THANHPHAN_"+i+"_"+buoi+"_"+j+')window.DIV_'+"THANHPHAN_"+i+"_"+buoi+"_"+j+'.focus();">'+createTextArea("THANHPHAN_"+i+"_"+buoi+"_"+j,"THANHPHAN[]",data[i][buoi][j][2],"Update("+i+","+buoi+","+j+",2)",data[i][buoi][j][4]==1?"lcttextarea_tonghop":"lcttextarea")+'</td>';
			html += '<td valign=top  width=15% class=car2_content_'+buoi+' onclick="if(window.DIV_'+"DIADIEM_"+i+"_"+buoi+"_"+j+')window.DIV_'+"DIADIEM_"+i+"_"+buoi+"_"+j+'.focus();">'+createTextArea("DIADIEM_"+i+"_"+buoi+"_"+j,"DIADIEM[]",data[i][buoi][j][3],"Update("+i+","+buoi+","+j+",3)",data[i][buoi][j][4]==1?"lcttextarea_tonghop":"lcttextarea")+'</td>';
			html += '<td valign=top  width=20% class=car2_content_'+buoi+' onclick="if(window.DIV_'+"GHICHU_"+i+"_"+buoi+"_"+j+')window.DIV_'+"GHICHU_"+i+"_"+buoi+"_"+j+'.focus();">'+createTextArea("GHICHU_"+i+"_"+buoi+"_"+j,"GHICHU[]",data[i][buoi][j][13],"Update("+i+","+buoi+","+j+",13)",data[i][buoi][j][4]==1?"lcttextarea_tonghop":"lcttextarea")+'</td>';
			<?php if($this->lock==0){ ?>
			var isalarm="";
			if(data[i][buoi][j][0]!=""){
				if(data[i][buoi][j][5]!=""){
					isalarm = "<img onmousedown='cancelEvent(event)' src='/images/alarm.gif' onclick='Alarm(event,"+i+","+buoi+","+j+")' style='cursor:pointer' title='Nhắc nhở'>";
				}else{
					isalarm = "<img onmousedown='cancelEvent(event)' src='/images/alarm_disable.gif' onclick='Alarm(event,"+i+","+buoi+","+j+")' style='cursor:pointer' title='Nhắc nhở'>";
				}
			}
			html += '<td valign=top nowrap class=car2_content_'+buoi+'><div style="width:85px;"><input type=hidden name=NGAY[] value="'+data[i][0][2]+'"><input type=hidden name=BUOI[] value='+buoi+'><input type=hidden name=ID_LCT_P[] value="'+data[i][buoi][j][0]+'"><img src="/images/alarm_add_above.gif" onclick="AddAbove('+i+','+buoi+','+j+')" style="cursor:pointer" title="Thêm dưới"><img src="/images/alarm_add_top.gif" onclick="AddAbove('+i+','+buoi+','+(j-1)+')" style="cursor:pointer" title="Thêm trên">'+isalarm+'</div></td>';			
			<?php } ?>
			<?php if($this->lock==0){ ?>
			html += '<td valign=top align=center class=car2_content_'+buoi+'><input type=checkbox name=DELETE[] value="'+data[i][buoi][j][0]+'"></td>';
			<?php } ?>
		}
		//alert(html);
		return html;
	}
	function AddAbove(i,buoi,j){
		var arr_bak = data[i][buoi];
		data[i][buoi] = new Array();
		for(var k=0;k<=j;k++){
			data[i][buoi][k] = arr_bak[k];
		}
		data[i][buoi][j+1] = new Array("","","","","","","","","","","<?=$this->autoaddcq==1?"1":"0"?>","","","");
		for(var k=j+1;k<arr_bak.length;k++){
			data[i][buoi][k+1] = arr_bak[k];
		}
		//alert(data[i][buoi].length);
		DrawGrid();
	}
	function Delete(i,buoi,j){
		var isdelete=true;
		if(data[i][buoi][j][0]>0){
			if(confirm("Bạn có muốn xóa lịch "+data[i][buoi][j][1]+" không?")){
				execfunction("lichcttext","index","deletep","ID_LCT_P/"+data[i][buoi][j][0]);
				isdelete=true;
			}else{
				isdelete=false;
			}
		}
		if(isdelete){
			data[i][buoi].splice(j,1);
			if(data[i][buoi].length==0)data[i][buoi][0] = new Array("","","","","");
			DrawGrid();
		}
	}
	function DeleteAll(){
		var obj = document.getElementsByName("DELETE[]");
		var objnd = document.getElementsByName("NOIDUNG[]");
		var objid = document.getElementsByName("ID_LCT_P[]");
		for(var i=0;i<objnd.length;i++){
			if(objnd[i].value != "" && objid[i].value==""){
				alert("Vui lòng lưu lịch công tác mới trước khi xóa.");
				return;
			}
		}
		if(confirm("Bạn có muốn xóa lịch được chọn không?")){
			for(var i=0;i<obj.length;i++){
				if(obj[i].checked && obj[i].value!=""){
					execfunction("lichcttext","index","deletep","ID_LCT_P/"+obj[i].value);
				}
			}
			setTimeout("alert('Đã xóa thành công');document.location.href = '/lichcttext/index/index?BEGINDATE='+document.frm.BEGINDATE.value",2000);
			//document.location.href = "/lichcttext/index/index";
		}
	}
	function Update(i,buoi,j,tt){
		//alert(tt);
		if(tt==1){
			data[i][buoi][j][tt] = document.getElementById("NOIDUNG_"+i+"_"+buoi+"_"+j).value;
		}
		if(tt==2){
			data[i][buoi][j][tt] = document.getElementById("THANHPHAN_"+i+"_"+buoi+"_"+j).value;
		}
		if(tt==3){
			data[i][buoi][j][tt] = document.getElementById("DIADIEM_"+i+"_"+buoi+"_"+j).value;
		}
		if(tt==13){
			data[i][buoi][j][tt] = document.getElementById("GHICHU_"+i+"_"+buoi+"_"+j).value;
		}
	}
	function ChangeDate(){
		document.frm.action="/lichcttext/index/index";
		document.frm.submit();
	}
	function Addnew(){
		document.frm.action="/lichcttext/index/inputp";document.frm.submit();
	}
	function getScrollY() {
		  var scrOfY = 0;
		  if( typeof( window.pageYOffset ) == 'number' ) {
		    scrOfY = 0;
		  } else if( document.body && ( document.body.scrollLeft || document.body.scrollTop ) ) {
		    scrOfY = 0;
		  } else if( document.documentElement && ( document.documentElement.scrollLeft || document.documentElement.scrollTop ) ) {
		    scrOfY = document.documentElement.scrollTop;
		  }
		  //alert(scrOfY);
		  return scrOfY;
	}
	function mouseCoords(ev){
		if(ev.pageX || ev.pageY){
			return {x:ev.pageX, y:ev.pageY};
		}
		return {
			x:ev.clientX + document.body.scrollLeft - document.body.clientLeft,
			y:ev.clientY + document.body.scrollTop  - document.body.clientTop
		};
	}
	function Alarm(ev,i,buoi,j){
		var scrolly = getScrollY();
		ev = ev || window.event;
		temp = mouseCoords(ev);
		tooltip = document.getElementById("car_alarm");
		noidung = document.getElementById("car_alarm_noidung");
		ngay = document.getElementById("car_alarm_ngay");
		document.getElementById("car_button_cancel").style.display='none';
		document.frm.NHACNHO.value = data[i][buoi][j][6];
		if(data[i][buoi][j][5]!=""){
			var strtime = (data[i][buoi][j][8]).split(":");
			document.frm.NHACNHO_TIME_HOUR.value = strtime[0];
			document.frm.NHACNHO_TIME_MINUTE.value = strtime[1];
			document.getElementById("car_button_cancel").style.display='';
		}else{
			document.frm.NHACNHO_TIME_HOUR.value = "";
			document.frm.NHACNHO_TIME_MINUTE.value = "";
		}
		document.frm.BEFORE.value = data[i][buoi][j][9];
		document.frm.ID_LCT_P_ALARM.value = data[i][buoi][j][0];
		if(document.frm.SMS)document.frm.SMS.checked = (data[i][buoi][j][11]=="1"?true:false);
		if(document.frm.EMAIL)document.frm.EMAIL.checked = (data[i][buoi][j][12]=="1"?true:false);
		ngay = document.getElementById("car_alarm_ngay");
		noidung.innerHTML = data[i][buoi][j][1];
		ngay.innerHTML = data[i][buoi][j][6];
		tooltip.style.top = ((temp.y - 130) + scrolly)+ "px";
		tooltip.style.left = (temp.x - 360) + "px";
		tooltip.style.display = "block";
		tooltip.style.paddingTop = "5px";
		document.getElementById("car_alarm_error").innerText = "";
	}
	function checkuptocq(obj,i,buoi,j){
		document.getElementById("CHECK_"+i+"_"+buoi+"_"+j).value=(obj.checked?"1":"0");
		data[i][buoi][j][10] = (obj.checked?"1":"0");
	}
	//document.write(createTextArea("aaa","aaa","a\naa","aaa"));
	function checkalarm(){
		if(isInteger(document.frm.NHACNHO_TIME_HOUR.value)){
			if(parseInt(document.frm.NHACNHO_TIME_HOUR.value,10)>23 || parseInt(document.frm.NHACNHO_TIME_HOUR.value,10)<0){
				document.frm.NHACNHO_TIME_HOUR.value = "";
				document.frm.NHACNHO_TIME_HOUR.focus();
				document.getElementById("car_alarm_error").innerText = "Giờ không hợp lệ.";
				return false;
			}else{
				if(isInteger(document.frm.NHACNHO_TIME_MINUTE.value)){
					if(parseInt(document.frm.NHACNHO_TIME_MINUTE.value,10)>59 || parseInt(document.frm.NHACNHO_TIME_MINUTE.value,10)<0){
						document.frm.NHACNHO_TIME_MINUTE.value = "";
						document.frm.NHACNHO_TIME_MINUTE.focus();
						document.getElementById("car_alarm_error").innerText = "Phút không hợp lệ.";
						return false;
					}else{
						if(isInteger(document.frm.BEFORE.value)){
							if(parseInt(document.frm.BEFORE.value,10)<0){
								document.frm.BEFORE.value = "15";
								document.frm.BEFORE.focus();
								document.getElementById("car_alarm_error").innerText = "Báo trước không hợp lệ.";
								return false;
							}else{
								return true;
							}
						}else{
							document.frm.BEFORE.value = "15";
							document.frm.BEFORE.focus();
							document.getElementById("car_alarm_error").innerText = "Báo trước không hợp lệ.";
							return false;
						}
					}
				}else{
					document.frm.NHACNHO_TIME_MINUTE.value = "";
					document.frm.NHACNHO_TIME_MINUTE.focus();
					document.getElementById("car_alarm_error").innerText = "Phút không hợp lệ.";
					return false;
				}
			}
		}else{
			document.frm.NHACNHO_TIME_HOUR.value = "";
			document.frm.NHACNHO_TIME_HOUR.focus();
			document.getElementById("car_alarm_error").innerText = "Giờ không hợp lệ.";
			return false;
		}
	}
</script>
