<form id="containerID" action="/qtht/DanhMucMaSo/save" method="post" enctype="multipart/form-data" name="datacdform" >
<fieldset>
	<div class="required clearfix">
		<label>Tên</label>
        <input type="text" name="ten" maxlength="128" value="<?php echo htmlspecialchars($this->ten_b);?>" class="inputText" size="10" >
    	<span class="box_erro_area" id="ERRten"></span>
	</div>
	<div class="required clearfix">
		<label>Loại</label>
        <select id='loai' name=loai onchange='sel_loai_onchange();'>
        <option value=1>Mã số Văn bản đến</option>
        <option value=2>Mã số Văn bản đi</option>
        <option value=3>Mã số Hồ sơ một cửa</option>
        </select>
    	
	</div>
	<div class="required clearfix">
		<label>Chiều dài</label>
        <input type="text" name="length" size="2"  style="width:30px"   maxlength="2" value="<?php echo htmlspecialchars($this->length_b);?>" class="inputText" >
    	<span class="box_erro_area" id="ERRlength"></span>
	</div>
	<div class="required clearfix">
		<label>Thứ tự</label>
        <input type="text" name="order" size="2"  style="width:30px"   maxlength="2" value="<?php echo htmlspecialchars($this->order_b);?>" class="inputText" >
    	<span class="box_erro_area" id="ERRorder"></span>
	</div>
	<div class="required clearfix">
		<label>Kiểu</label>
        <select id=kieu name=kieu onchange="sel_kieu_onchange();" >
        <option value=1>Năm</option>
        <option value=2>Mã Cơ quan nội bộ</option>
        <option value=3>Mã thành phố/tỉnh nội bộ</option>
        <option value=4>Số cố định</option>
        <option value=5>Số không cố định</option>
        <option value=6>Chuỗi cố định</option>
        <option value=7>Chuỗi không cố định</option>
        <option value=8>Đã có trong cơ sở dữ liệu</option>
        </select>
    	
	</div>
	<div class="required clearfix">
		<label id='lbl_value' style="display:none">Giá trị cố định</label>
        <input style="display:none" id=value type="text" name="value" size="2"  style="width:30px"   maxlength="2" value="<?php echo htmlspecialchars($this->value_b);?>" class="inputText" >
    	<span class="box_erro_area" id="ERRlength"></span>
	</div>
	<div class="required clearfix">
		<label style="display:none" id=lbl_php_func >Hàm PHP tạo giá trị</label>
        <input style="display:none" id =php_func type="text" name="php_func"      maxlength="100" value="<?php echo htmlspecialchars($this->php_func_b);?>" class="inputText" >
    	<span class="box_erro_area" id="ERRlength"></span>
	</div>
	<div class="required clearfix">
		<label id='lbl_kieu' style="display:none">Lấy mã số trong CSDL</label>
        <hidden name=table value="vb_vbden"/>
        <select id=field name=field style="display:none">
      	</select>
	</div>
	
</fieldset>
<input type=hidden name="id" value=<?php echo $this->id?> >
</form>
<script>
function checkFormData(){
	/*var str = "Bạn phải nhập tên lĩnh vực văn bản";
	var strerr = validateInput("required",document.datacdform.name,str);
	if(!strerr){
		document.datacdform.name.focus();
		return false;
	}
	str="Tên lĩnh vực không được quá 128 ký tự";
	strerr = validateInput("maxlen=128",document.datacdform.name,str);
	if(!strerr){
		
		document.datacdform.name.focus();
		return false;
	}
	str="Mã Loại văn bản là một chuỗi có đúng 2 ký tự";
	strerr = validateInput("maxlen=2",document.datacdform.code,str);
	if(!strerr){
		document.datacdform.code.focus();
		return false;
	}
	str="Mã Loại văn bản là một chuỗi có đúng 2 ký tự";
	strerr = validateInput("minlen=2",document.datacdform.code,str);
	if(!strerr){
		document.datacdform.code.focus();
		return false;
	}*/
	return true;
}

function SaveButtonClick(){
	
	//window.showModalDialog( '/DialogTemplate/QueryDialog.html',document);
	if(checkFormData())
		document.datacdform.submit();
}

function BackButtonClick(){
	document.datacdform.action = '/qtht/danhmucmaso/index';
	document.datacdform.submit();
}

//Xu ly giao dien
function get_sel_loai(){
	var loaic = document.getElementById("loai");
	var se = loaic.options[loaic.selectedIndex].value;
	return se;
}
function sel_loai_onchange(){
	//var loaic = document.getElementById("loai");
	//var se = loaic.options[loaic.selectedIndex].value;
	sel_field_init();
}

function sel_field_init(){
	var loaic = document.getElementById("loai");
	var fieldc = document.getElementById("field");
	var arr = new Array();
//van ban den : coquan/so ban
	arr[0] = new Array();
	arr[0][0] = 1;
	arr[0][2] = 'Cơ quan/Sở ban hành';
	arr[0][1] = 1;
	arr[1] = new Array();
	arr[1][0] = 1;
	arr[1][2] = 'Mã Loại Văn Bản';
	arr[1][1] = 2;
	arr[2] = new Array();
	arr[2][0] = 1;
	arr[2][2] = 'Độ mật';
	arr[2][1] = 3;
	arr[3] = new Array();
	arr[3][0] = 1;
	arr[3][2] = 'Độ khẩn';
	arr[3][1] = 4;
	arr[4] = new Array();
	arr[4][0] = 1;
	arr[4][2] = 'Số đến';
	arr[4][1] = 5;
	//van ban di
	arr[5] = new Array();
	arr[5][0] = 2;
	arr[5][2] = 'Mã Loại Văn Bản';
	arr[5][1] = 1;
	arr[6] = new Array();
	arr[6][0] = 2;
	arr[6][2] = 'Độ mật';
	arr[6][1] = 2;
	arr[7] = new Array();
	arr[7][0] = 2;
	arr[7][2] = 'Độ khẩn';
	arr[7][1] = 3;
	arr[8] = new Array();
	arr[8][0] = 2;
	arr[8][2] = 'Số đi';
	arr[8][1] = 4;
//ho so mot cua
	arr[9] = new Array();
	arr[9][0] = 3;
	arr[9][2] = 'Mã Loại Hồ sơ';
	arr[9][1] = 1;
	arr[10] = new Array();
	arr[10][0] = 3;
	arr[10][2] = 'Mã Phòng Ban';
	arr[10][1] = 2;
	arr[11] = new Array();
	arr[11][0] = 3;
	arr[11][2] = 'Số thứ tự';
	arr[11][1] = 3;
	
	FillComboByCombo(loaic,fieldc,arr);
}

function sel_kieu_onchange(){
	initForm();
}

function initForm(){
	
		
	var kieuc = document.getElementById("kieu");
	var se = kieuc.options[kieuc.selectedIndex].value;
	var fieldc = document.getElementById("field");
	var lbl_kieu = document.getElementById("lbl_kieu");
	var value = document.getElementById("value");
	var lbl_value = document.getElementById("lbl_value");
	var php_func = document.getElementById("php_func");
	var lbl_php_func = document.getElementById("lbl_php_func");
	if(se == 1 || se == 2 || se==3){
		value.style.display = "none";
		lbl_value.style.display = "none";
		php_func.style.display = "none";
		lbl_php_func.style.display = "none";
		fieldc.style.display="none";
		lbl_kieu.style.display="none";
		return;
	}
	
	if(se == 8){
		fieldc.style.display="block";
		lbl_kieu.style.display="";
		value.style.display = "none";
		lbl_value.style.display = "none";
		php_func.style.display = "none";
		lbl_php_func.style.display = "none";
		sel_field_init();
		
		
	}else{
		if(se==4 || se==6){
			value.style.display = "";
			lbl_value.style.display = "";
			php_func.style.display = "none";
			lbl_php_func.style.display = "none";
			fieldc.style.display="none";
			lbl_kieu.style.display="none";
		}
		if(se==7 || se==5){
			php_func.style.display = "";
			lbl_php_func.style.display = "";
			value.style.display = "none";
			lbl_value.style.display = "none";
			fieldc.style.display="none";
			lbl_kieu.style.display="none";
		}
		
	}
}
initForm();
var kieuc = document.getElementById("kieu");
var fieldc = document.getElementById("field");
var lbl_kieu = document.getElementById("lbl_kieu");
var loaic = document.getElementById("loai");
var loaic_se = 0<?php echo $this->loai_b ?>;
loaic.options[loaic_se-1].selected = "selected";
var kieu_se = 0<?php echo $this->kieu_b ?>;
kieuc.options[kieu_se-1].selected = "selected";
initForm();
/*lbl_kieu.style.display="";
fieldc.style.display="block";*/
var field_se = 0<?php echo $this->field_b ?>;
fieldc.options[field_se-1].selected = "selected";

</script>