<?php
$phuong = new DanhMucPhuongModel();
$phuong = $phuong->SelectAll(0,0,"");
$loai = new LoaiModel();
$loai->_linhvuc = $this->param['sel_lv'];
$loai = $loai->SelectAll(0,0,"");
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="Book1_files/filelist.xml">
<link rel=Edit-Time-Data href="Book1_files/editdata.mso">
<link rel=OLE-Object-Data href="Book1_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>nguyennd</o:Author>
  <o:LastAuthor>nguyennd</o:LastAuthor>
  <o:Created>2009-07-21T08:19:03Z</o:Created>
  <o:LastSaved>2009-07-21T08:37:39Z</o:LastSaved>
  <o:Company>Hewlett-Packard</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.25in .25in 1.0in .25in;
	mso-header-margin:.25in;
	mso-footer-margin:.5in;
	mso-page-orientation:landscape;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:left;
	vertical-align:middle;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl25
	{mso-style-parent:style0;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;}
.xl26
	{mso-style-parent:style0;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;}
.xl27
	{mso-style-parent:style0;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl28
	{mso-style-parent:style0;
	color:white;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	border:.5pt solid windowtext;
	mso-diagonal-down:.5pt solid windowtext;
	background:gray;
	mso-pattern:auto none;
	white-space:normal;}
.xl29
	{mso-style-parent:style0;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#C1C1C1;
	mso-pattern:auto none;
	white-space:normal;}
.xl30
	{mso-style-parent:style0;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	border:.5pt solid windowtext;}
.xl31
	{mso-style-parent:style0;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl32
	{mso-style-parent:style0;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl33
	{mso-style-parent:style0;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl34
	{mso-style-parent:style0;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:left;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>16</x:ActiveRow>
       <x:ActiveCol>4</x:ActiveCol>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
    <x:PublishObjects>
     <x:PublishObject>
      <x:Id>18782</x:Id>
      <x:DivID>Book1_18782</x:DivID>
      <x:SourceType>SourceSheet</x:SourceType>
      <x:HtmlType>HtmlStatic</x:HtmlType>
      <x:Location HRef="C:\Users\nguyennd\Documents\thongkeexcel.htm"/>
     </x:PublishObject>
    </x:PublishObjects>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>6945</x:WindowHeight>
  <x:WindowWidth>12435</x:WindowWidth>
  <x:WindowTopX>240</x:WindowTopX>
  <x:WindowTopY>150</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]-->
</head>

<body link=blue vlink=purple class=xl27>

<table x:str border=0 cellpadding=0 cellspacing=0 width=990 style='border-collapse:
 collapse;table-layout:fixed;width:743pt'>
 <col class=xl27 width=189 style='mso-width-source:userset;mso-width-alt:6912;
 width:142pt'>
 <col class=xl27 width=49 style='mso-width-source:userset;mso-width-alt:1792;
 width:37pt'>
 <col class=xl27 width=48 style='mso-width-source:userset;mso-width-alt:1755;
 width:36pt'>
 <col class=xl27 width=64 span=11 style='width:48pt'>
 <tr height=17 style='height:12.75pt'>
  <td colspan=4 height=17 class=xl32 width=350 style='height:12.75pt;
  width:263pt'><?=DepartmentsModel::getNameById($this->user->ID_DEP)?></td>
  <td class=xl27 width=64 style='width:48pt'></td>
  <td class=xl27 width=64 style='width:48pt'></td>
  <td class=xl27 width=64 style='width:48pt'></td>
  <td class=xl27 width=64 style='width:48pt'></td>
  <td class=xl27 width=64 style='width:48pt'></td>
  <td colspan=5 class=xl32 width=320 style='width:240pt'>CỘNG HOÀ XÃ
  HỘI CHỦ NGHĨA VIỆT NAM</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=9 class=xl27 style='height:12.75pt;mso-ignore:colspan'></td>
  <td colspan=5 class=xl33>Độc lập - Tự do - Hạnh
  phúc</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=14 class=xl27 style='height:12.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td colspan=7 height=17 class=xl34 style='height:12.75pt'><span
  style='mso-spacerun:yes'>                </span>BẢNG THỐNG KÊ:
  DIỆN TÍCH ĐẤT </td>
  <td colspan=7 class=xl27 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl27 colspan=3 style='height:12.75pt;mso-ignore:colspan'><span
  style='mso-spacerun:yes'> </span>- Khoảng thời gian tiếp nhận từ: <?=$this->fromdate."/".QLVBDHCommon::getYear()?> đến <?=$this->todate."/".QLVBDHCommon::getYear()?></td>
  <td colspan=11 class=xl27 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=14 class=xl27 style='height:12.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=56 style='mso-height-source:userset;height:42.0pt'>
  <td height=56 class=xl28 width=189 style='height:42.0pt;width:142pt'><span
  style='mso-spacerun:yes'>                        </span>XÃ
  PHƯỜNG<br>
    <br>
    <span style='mso-spacerun:yes'>   </span>HỒ SƠ</td>
	<?php
	foreach($phuong as $itemphuong){
	?>
	<td class=xl29 width=40 style='border-left:none;width:30pt'><?=$itemphuong["TENPHUONG"]?></td>
	<?php
	}
	?>
	<td class=xl29 width=40 style='border-left:none;width:30pt'>Không rõ</td>
  <td class=xl29 width=48 style='border-left:none;width:36pt'>TỔNG DIỆN TÍCH</td>
  <td colspan=11 class=xl27 style='mso-ignore:colspan'></td>
 </tr>
<?php
	$cntallphuong = array();
	$cntall = 0;
	foreach($loai as $itemloai){
		$tong = 0;
?>
 <tr height=34 style='height:25.5pt'>
  <td height=34 class=xl24 width=189 style='height:25.5pt;border-top:none;
  width:142pt'><?=$itemloai["TENLOAI"]?></td>
<?php
$stt=0;
foreach($phuong as $itemphuong){
	$cntphuong = DientichdatModel::CountDientich($itemloai["ID_LOAIHOSO"],$itemphuong["ID_PHUONG"],$this->xfromdate,$this->xtodate);
	$cntallphuong[$stt] += $cntphuong;
	$stt++;
	$tong += $cntphuong;
	$cntall += $cntphuong;
?>
  <td class=xl25 style='border-top:none;border-left:none' x:num><?=$cntphuong?></td>
<?php
}
$cntphuong = DientichdatModel::CountDientich($itemloai["ID_LOAIHOSO"],0,$this->xfromdate,$this->xtodate);
$tong += $cntphuong;
$cntallphuong[$stt] += $cntphuong;
$cntall += $cntphuong;
?>
  <td class=xl25 style='border-top:none;border-left:none' x:num><?=$cntphuong?></td>
  <td class=xl26 style='border-top:none;border-left:none' x:num><?=$tong?></td>
  <td colspan=11 class=xl27 style='mso-ignore:colspan'></td>
 </tr>
<?php
	}
?>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl30 style='height:12.75pt;border-top:none'>TỔNG DIỆN TÍCH</td>
<?php
$stt=0;
foreach($phuong as $itemphuong){
?>
<td class=xl26 style='border-top:none;border-left:none' x:num><?=$cntallphuong[$stt]?></td>
<?php
	$stt++;
}
?>
  <td class=xl26 style='border-top:none;border-left:none' x:num><?=$cntallphuong[$stt]?></td>
  <td class=xl26 style='border-top:none;border-left:none' x:num><?=$cntall?></td>
  <td colspan=11 class=xl27 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=10 class=xl27 style='height:12.75pt;mso-ignore:colspan'></td>
  <td colspan=3 class=xl31>NGƯỜI LẬP</td>
 </tr>
 
 
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=14 class=xl27 style='height:12.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=10 class=xl27 style='height:12.75pt;mso-ignore:colspan'></td>
  <td colspan=3 class=xl32><i><?=$this->user->FULLNAME?></i></td>
  <td class=xl27></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=189 style='width:142pt'></td>
  <td width=49 style='width:37pt'></td>
  <td width=48 style='width:36pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</body>

</html>
