<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:st1="urn:schemas-microsoft-com:office:smarttags"
xmlns="http://www.w3.org/TR/REC-html40"
xmlns:ns1="http://schemas.microsoft.com/office/2004/12/omml"
xmlns:ns0="urn:schemas-microsoft-com:office:smarttags">
<?php
   global $config ;
?>
<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 11">
<meta name=Originator content="Microsoft Word 11">
<link rel=File-List href="phieutrahoso%5b7%5d_files/filelist.xml">
<title>VĂN PHÒNG UBND</title>
<o:SmartTagType namespaceuri="urn:schemas-microsoft-com:office:smarttags"
 name="country-region"/>
<o:SmartTagType namespaceuri="urn:schemas-microsoft-com:office:smarttags"
 name="place"/>
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>longtv</o:Author>
  <o:LastAuthor>longtv</o:LastAuthor>
  <o:Revision>2</o:Revision>
  <o:TotalTime>1</o:TotalTime>
  <o:Created>2010-06-02T07:31:00Z</o:Created>
  <o:LastSaved>2010-06-02T07:31:00Z</o:LastSaved>
  <o:Pages>1</o:Pages>
  <o:Words>131</o:Words>
  <o:Characters>753</o:Characters>
  <o:Company>USER</o:Company>
  <o:Lines>6</o:Lines>
  <o:Paragraphs>1</o:Paragraphs>
  <o:CharactersWithSpaces>883</o:CharactersWithSpaces>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <w:WordDocument>
  <w:Zoom>90</w:Zoom>
  <w:SpellingState>Clean</w:SpellingState>
  <w:GrammarState>Clean</w:GrammarState>
  <w:ValidateAgainstSchemas/>
  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>
  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
  <w:BrowserLevel>MicrosoftInternetExplorer4</w:BrowserLevel>
 </w:WordDocument>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <w:LatentStyles DefLockedState="false" LatentStyleCount="156">
 </w:LatentStyles>
</xml><![endif]--><!--[if !mso]><object
 classid="clsid:38481807-CA0E-42D2-BF39-B33AF135CC4D" id=ieooui></object>
<style>
st1\:*{behavior:url(#ieooui) }
</style>
<![endif]-->
<style>
<!--
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-parent:"";
	margin:0cm;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:12.0pt;
	font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";}
p
	{font-size:12.0pt;
	font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";}
span.SpellE
	{mso-style-name:"";
	mso-spl-e:yes;}
@page Section1
	{size:612.0pt 792.0pt;
	margin:72.0pt 90.0pt 72.0pt 90.0pt;
	mso-header-margin:35.4pt;
	mso-footer-margin:35.4pt;
	mso-paper-source:0;}
div.Section1
	{page:Section1;}
-->
</style>
<!--[if gte mso 10]>
<style>
 /* Style Definitions */
 table.MsoNormalTable
	{mso-style-name:"Table Normal";
	mso-tstyle-rowband-size:0;
	mso-tstyle-colband-size:0;
	mso-style-noshow:yes;
	mso-style-parent:"";
	mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
	mso-para-margin:0cm;
	mso-para-margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:10.0pt;
	font-family:"Times New Roman";
	mso-ansi-language:#0400;
	mso-fareast-language:#0400;
	mso-bidi-language:#0400;}
</style>
<![endif]-->
</head>

<body lang=EN-US style='tab-interval:36.0pt'>

<div class=Section1>

<table class=MsoNormalTable border=1 cellpadding=0 style='mso-cellspacing:1.5pt;
 border:solid white 1.0pt;mso-border-alt:solid white .5pt;mso-border-insideh:
 .5pt solid white;mso-border-insidev:.5pt solid white'>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><b><?=$config->sys_info->company?></b></p>
  </td>
  <td width="100%" style='width:100.0%;border:solid white 1.0pt;mso-border-alt:
  solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><b>CỘNG
  HÒA XÃ HỘI CHỦ NGHĨA VIỆT <st1:country-region w:st="on"><st1:place w:st="on">NAM</st1:place></st1:country-region></b></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><b></b></p>
  </td>
  <td width="100%" style='width:100.0%;border:solid white 1.0pt;mso-border-alt:
  solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><span
  class=SpellE><b><u>Độc</u></b></span><b><u> <span class=SpellE>lập</span> – <span
  class=SpellE>Tự</span> do – <span class=SpellE>Hạnh</span> <span
  class=SpellE>phúc</span></u></b></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:2'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'>----------</p>
  </td>
  <td width="100%" style='width:100.0%;border:solid white 1.0pt;mso-border-alt:
  solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'>----------------------</p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:3'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><b>TỔ
  TIẾP NHẬN VÀ TRẢ HỒ SƠ</b></p>
  </td>
  <td width="100%" style='width:100.0%;border:solid white 1.0pt;mso-border-alt:
  solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=right style='text-align:right;line-height:13.4pt'><span
  class=SpellE><i><?=$config->sys_info->city?></span>, <span
  class=SpellE>ngày</span> <?=date("d")?> <span class=SpellE>tháng</span> <?=date("m")?> <span
  class=SpellE>năm</span> <?=date("Y")?></i></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:4;mso-yfti-lastrow:yes'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'><o:p>&nbsp;</o:p></span></p>
  </td>
  <td style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'><o:p>&nbsp;</o:p></span></p>
  </td>
 </tr>
</table>

<p align=center style='text-align:center'><b>PHIẾU TRẢ HỒ SƠ</b></p>

<table class=MsoNormalTable border=1 cellpadding=0 width="100%"
 style='width:100.0%;mso-cellspacing:1.5pt;border:solid white 1.0pt;mso-border-alt:
 solid white .5pt;mso-border-insideh:.5pt solid white;mso-border-insidev:.5pt solid white'>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt 192.55pt'>
 <?php foreach($this->data as $item){?>
  <p class=MsoNormal><span style='mso-spacerun:yes'>             </span><span style='font-size:14.0pt'><span
  class=SpellE>Văn</span> <span class=SpellE>phòng</span> <span class=SpellE>nhận</span>
  <span class=SpellE>được</span> <span class=SpellE>hồ</span> <span
  class=SpellE>sơ</span>: <?=$item["TENLOAI"]?><br>
  <span style='mso-spacerun:yes'>             </span><span class=SpellE>của</span>
  <span class=SpellE>đơn</span> <span class=SpellE>vị</span> <span
  class=SpellE>trình</span> : <span class=SpellE><?=$item["TENTOCHUCCANHAN"]?></span> </p>
  <?php } ?>
  </span>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1;mso-yfti-lastrow:yes'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt 192.55pt'>
  <?php foreach($this->bs as $ghichu)
			  if(!$ghichu["NGAY_BOSUNG"]){?>
  <p class=MsoNormal><span style='mso-spacerun:yes'>             </span><span style='font-size:14.0pt'>Qua <span
  class=SpellE>kiểm</span> <span class=SpellE>tra</span>, <span class=SpellE>Tổ</span>
  <span class=SpellE>Tiếp</span> <span class=SpellE>nhận</span> <span
  class=SpellE>và</span> <span class=SpellE>trả</span> <span class=SpellE>hồ</span>
  <span class=SpellE>sơ</span> <span class=SpellE>xin</span> <span
  class=SpellE>trả</span> <span class=SpellE>lại</span> <span class=SpellE>hồ</span>
  <span class=SpellE>sơ</span> <span class=SpellE>để</span>: <br>
  <span style='mso-spacerun:yes'>             </span><?=nl2br($ghichu["CACGHICHU"])?><br></p>
  <?php }?>
  </span>
  </td>
 </tr>
</table>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><o:p>&nbsp;</o:p></b></p>

<table class=MsoNormalTable border=1 cellpadding=0 width="100%"
 style='width:100.0%;mso-cellspacing:1.5pt;border:solid white 1.0pt;mso-border-alt:
 solid white .5pt;mso-border-insideh:.5pt solid white;mso-border-insidev:.5pt solid white'>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><b>TỔ TIẾP NHẬN VÀ
  TRẢ HỒ SƠ</b></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1'>
  <td colspan=3 style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='margin-bottom:12.0pt'><br style='mso-special-character:
  line-break'>
  <![if !supportLineBreakNewLine]><br style='mso-special-character:line-break'>
  <![endif]></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:2'>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:3;mso-yfti-lastrow:yes'>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
 </tr>
</table>

<p class=MsoNormal><span style='display:none;mso-hide:all'><o:p>&nbsp;</o:p></span></p>

<table class=MsoNormalTable border=1 cellpadding=0 style='mso-cellspacing:1.5pt;
 border:solid white 1.0pt;mso-border-alt:solid white .5pt;mso-border-insideh:
 .5pt solid white;mso-border-insidev:.5pt solid white'>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><b><?=$config->sys_info->company?></b></p>
  </td>
  <td width="100%" style='width:100.0%;border:solid white 1.0pt;mso-border-alt:
  solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><b>CỘNG
  HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</b></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><b></b></p>
  </td>
  <td width="100%" style='width:100.0%;border:solid white 1.0pt;mso-border-alt:
  solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><span
  class=SpellE><b><u>Độc</u></b></span><b><u> <span class=SpellE>lập</span> – <span
  class=SpellE>Tự</span> do – <span class=SpellE>Hạnh</span> <span
  class=SpellE>phúc</span></u></b></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:2'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'>----------</p>
  </td>
  <td width="100%" style='width:100.0%;border:solid white 1.0pt;mso-border-alt:
  solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'>----------------------</p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:3'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><b>TỔ
  TIẾP NHẬN VÀ TRẢ HỒ SƠ</b></p>
  </td>
  <td width="100%" style='width:100.0%;border:solid white 1.0pt;mso-border-alt:
  solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=right style='text-align:right;line-height:13.4pt'><span
  class=SpellE><i><?=$config->sys_info->city?></span>, <span
  class=SpellE>ngày</span> <?=date("d")?> <span class=SpellE>tháng</span> <?=date("m")?> <span
  class=SpellE>năm</span> <?=date("Y")?></i></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:4;mso-yfti-lastrow:yes'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:13.4pt'><o:p>&nbsp;</o:p></p>
  </td>
  <td style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'><o:p>&nbsp;</o:p></span></p>
  </td>
  <td style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'><o:p>&nbsp;</o:p></span></p>
  </td>
 </tr>
</table>

<p align=center style='text-align:center'><b>PHIẾU TRẢ HỒ SƠ</b></p>

<table class=MsoNormalTable border=1 cellpadding=0 width="100%"
 style='width:100.0%;mso-cellspacing:1.5pt;border:solid white 1.0pt;mso-border-alt:
 solid white .5pt;mso-border-insideh:.5pt solid white;mso-border-insidev:.5pt solid white'>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
 <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt 192.55pt'>
  <?php foreach($this->data as $item){?>
  <p class=MsoNormal><span style='mso-spacerun:yes'>             </span><span style='font-size:14.0pt'><span
  class=SpellE>Văn</span> <span class=SpellE>phòng</span> <span class=SpellE>nhận</span>
  <span class=SpellE>được</span> <span class=SpellE>hồ</span> <span
  class=SpellE>sơ</span>: <?=$item["TENLOAI"]?><br>
  <span style='mso-spacerun:yes'>             </span><span class=SpellE>của</span>
  <span class=SpellE>đơn</span> <span class=SpellE>vị</span> <span
  class=SpellE>trình</span> : <span class=SpellE><?=$item["TENTOCHUCCANHAN"]?></span> </p>
  <?php } ?>
  </span>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1;mso-yfti-lastrow:yes'>
  <td nowrap style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt 192.55pt'>
  <?php foreach($this->bs as $ghichu)
			  if(!$ghichu["NGAY_BOSUNG"]){?>
  <p class=MsoNormal><span style='mso-spacerun:yes'>             </span><span style='font-size:14.0pt'>Qua <span
  class=SpellE>kiểm</span> <span class=SpellE>tra</span>, <span class=SpellE>Tổ</span>
  <span class=SpellE>Tiếp</span> <span class=SpellE>nhận</span> <span
  class=SpellE>và</span> <span class=SpellE>trả</span> <span class=SpellE>hồ</span>
  <span class=SpellE>sơ</span> <span class=SpellE>xin</span> <span
  class=SpellE>trả</span> <span class=SpellE>lại</span> <span class=SpellE>hồ</span>
  <span class=SpellE>sơ</span> <span class=SpellE>để</span>: <br>
  <span style='mso-spacerun:yes'>             </span><?=nl2br($ghichu["CACGHICHU"])?><br></p>
  <?php }?>
  </span>
  </td>
 </tr>
</table>

<p class=MsoNormal style='margin-bottom:12.0pt'><b><o:p>&nbsp;</o:p></b></p>

<table class=MsoNormalTable border=1 cellpadding=0 width="100%"
 style='width:100.0%;mso-cellspacing:1.5pt;border:solid white 1.0pt;mso-border-alt:
 solid white .5pt;mso-border-insideh:.5pt solid white;mso-border-insidev:.5pt solid white'>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><b>TỔ TIẾP NHẬN VÀ
  TRẢ HỒ SƠ</b></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1'>
  <td colspan=3 style='border:solid white 1.0pt;mso-border-alt:solid white .5pt;
  padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal style='margin-bottom:12.0pt'><br style='mso-special-character:
  line-break'>
  <![if !supportLineBreakNewLine]><br style='mso-special-character:line-break'>
  <![endif]></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:2'>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:3;mso-yfti-lastrow:yes'>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
  <td width="33%" nowrap style='width:33.0%;border:solid white 1.0pt;
  mso-border-alt:solid white .5pt;padding:.75pt .75pt .75pt .75pt'>
  <p class=MsoNormal align=center style='text-align:center'><o:p>&nbsp;</o:p></p>
  </td>
 </tr>
</table>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

</div>

</body>

</html>
<script>
window.print();

</script>
