<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr" >
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>QLVBDH</title>

<link rel="stylesheet" href="/styles/default.css" type="text/css" />
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
<link rel="stylesheet" href="/styles/reset.css" type="text/css" />
<link rel="stylesheet" href="/styles/typography.css" type="text/css" />
<link rel="stylesheet" href="/styles/traodoi_lightbox.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/styles/menu.css" type="text/css" media="screen" />
<script type="text/javascript" src="/js/jquery-1.3.2.js"></script>
<script type="text/javascript" src="/js/jqueryslidemenu.js"></script>
<script type="text/javascript" src="/js/LoadDynamicJs.js"></script> <!-- cai nay cua trung, khong ai duoc dung vao --> 
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/joomla.javascript.js"></script>
<script type="text/javascript" src="/js/calendar.js"></script>
<script type="text/javascript" src="/js/ajax/AjaxEngine.js"></script>
<script type="text/javascript" src="/js/dlg_confirm.js"></script>
<script type="text/javascript" src="/js/jquery.cycle.all.js"></script>
<script type="text/javascript" src="/js/jquery.nyroModal.custom.js"></script>
<script type="text/javascript" src="/js/jquery.scrollFollow.js"></script>
</head>
<body style="margin: 5px 5px 5px 5px;">
<select name="ID_LVB_FORADDIN" id="ID_LVB_FORADDIN" style="display:none">
<?php 
	echo vbdenModel::WriteLVB((int)$this->ID_LVB,"-- Chọn tất cả  --");
?> 
</select>
<form name=frm method=post action="/hscv/hscv/list/nolayout/1">
	<table border = 0>
		<tr>
			<td nowrap="nowrap">Loại công việc</td>
			<td nowrap="nowrap"><select name="OBJECT" onchange="
						document.frm.page.value = 1;
						if(document.frm.TRANGTHAI!=null)document.frm.TRANGTHAI.value = 0;
						document.frm.action = '/hscv/hscv/list/nolayout/1';
						document.frm.submit();
				">
						<option value="">--Chọn loại công việc--</option>
						<option value="VBD">Xử lý văn bản đến</option>
						<option value="VBSOANTHAO">Công việc</option>
				</select>
				<script>document.frm.OBJECT.value="<?=$this->OBJECT?>";</script>
				</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<?php
			if(strtoupper($this->code)!="ZIP"){
		?>
		<tr style="display:none">
			<td nowrap="nowrap">Trạng thái</td>
			<td nowrap="nowrap"><select name="TRANGTHAI" onchange="
						document.frm.page.value = 1;
						document.frm.action = '/hscv/hscv/list/nolayout/1';
						document.frm.submit();
					">
						<option value=0>--Chọn trang thái--</option>
						<?=WFEngine::ToCombo($this->datatrangthai,$this->TRANGTHAI)?>
				</select></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap></td>
			<td width="100%"></td>
		</tr>
		<?php } ?>
		
		<tr>
			<td nowrap="nowrap" valign=top>
			
			Nội dung
			</td>
			<td nowrap="nowrap" colspan="4" style="padding-right:6px;"><input type=text class=inputbox name=NAMECV value="<?=$this->NAME?>" size=50 style="width:100%;"><br>
			<input type="checkbox" name=INNAME value=1 <?=$this->INNAME==1?"checked":""?>>
			<?php switch($this->OBJECT){
				case "VBD":
					echo "Trong trích yếu";
				break;
				case "MOTCUA":
					echo "Trong tên hồ sơ";
				break;
				default:
					echo "Trong tên công việc";
				}
			?> 
			<input type="checkbox" name=INFILE value=1 <?=$this->INFILE==1?"checked":""?>>Trong nội dung dự thảo
			</td>
			<td nowrap></td>
			<td width="100%"></td>
		</tr>
		<?php if($this->OBJECT == "VBD"){ ?>
		<tr>
			<td nowrap="nowrap">Sổ văn bản</td>
			<td nowrap="nowrap">
				<select name="ID_SVB" id="ID_SVB" class="inputbox" size="1" onchange="document.frm.submit();">
            	<?php 
            		echo vbdenModel::WriteSVB((int)$this->ID_SVB,"-- Chọn tất cả  --", true);
            	?> 
        		</select>
			</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap">Loại văn bản</td>
			<td nowrap="nowrap">
				<select name="ID_LVB" id="ID_LVB" class="inputbox" size="1" onchange="document.frm.submit();">
            	<?php 
            		echo vbdenModel::WriteLVB((int)$this->ID_LVB,"-- Chọn tất cả  --");
            	?> 
        		</select>
			</td>
			<td nowrap></td>
			<td width="100%"></td>
		</tr>
		
		<tr>
			<td nowrap="nowrap">Số đến</td>
			<td nowrap="nowrap"><input type=text class=inputbox name=SODEN value="<?=$this->SODEN?>" size=10>
			<input name=SODEN_ISLIKE value=1 type=checkbox <?=$this->SODEN_ISLIKE==1?"checked":""?> > Tìm gần đúng
			</td>
			
			<td width="10" nowrap="nowrap"></td>
		
			<td nowrap="nowrap">Số, ký hiệu VB</td>
			<td nowrap="nowrap" ><input type=text class=inputbox name=SOKYHIEU value="<?=$this->SOKYHIEU?>" size=20></td>
			<td nowrap></td>
			<td width="100%"></td>
			
		</tr>
		<tr id=FindAdvanced2>
			<td nowrap="nowrap">Ngày đến</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendar($this->NGAYDEN_BD,"NGAYDEN_BD","NGAYDEN_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendar($this->NGAYDEN_KT,"NGAYDEN_KT","NGAYDEN_KT") ?>
			</td>
			<td nowrap></td>
			<td width="100%"></td>
		</tr>
		<tr id=FindAdvanced3>
			<td nowrap="nowrap">Ngày ban hành</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendar($this->NGAYBANHANH_BD,"NGAYBANHANH_BD","NGAYBANHANH_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendar($this->NGAYBANHANH_KT,"NGAYBANHANH_KT","NGAYBANHANH_KT") ?>
			</td>
			<td nowrap></td>
			<td width="100%"></td>
		</tr>
		
		<?php }?>
		<?php if($this->OBJECT == "MOTCUA"){ ?>

	
		<tr>
			<td nowrap="nowrap">Mã hồ sơ một cửa</td>
			<td nowrap="nowrap">
				<input type=text class=inputbox name=MASOHOSO value="<?=$this->MASOHOSO?>">
			</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap">Tên tổ chức công dân</td>
			<td nowrap="nowrap">
				<input type=text class=inputbox name=TENTOCHUCCANHAN value="<?=$this->TENTOCHUCCANHAN?>" >
			</td>
			<td nowrap></td>
			<td width="100%"></td>		
			
		</tr>
		
		<tr id=FindAdvanced2>
			<td nowrap="nowrap">Ngày tiếp nhận</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendar($this->NHAN_NGAY_BD,"NHAN_NGAY_BD","NHAN_NGAY_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendar($this->NHAN_NGAY_KT,"NHAN_NGAY_KT","NHAN_NGAY_KT") ?>
			</td>
			<td nowrap></td>
			<td width="100%"></td>
		</tr>
		<?php } ?>
		<?php if($this->OBJECT == "VBSOANTHAO"){ ?>
		<tr>
			<td nowrap="nowrap">Từ ngày</td>
			<td nowrap="nowrap"><?=QLVBDHCommon::calendar($this->NGAY_BD,"NGAY_BD","NGAY_BD") ?> Đến ngày <?=QLVBDHCommon::calendar($this->NGAY_KT,"NGAY_KT","NGAY_KT") ?></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap></td>
			<td width="100%"></td>
		</tr>
		
		<?php } ?>
		<tr>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap" colspan="3"><input type=submit value="Tìm kiếm"></td>
			<td nowrap></td>
			<td width="100%"></td>
		</tr>
	</table>
<table class=adminlist>
<thead>
	<tr>
		<th colspan="3">
			<div>
				<div class="limit" style="float:left;">Hiển thị #
					<select name="limit1"  style="width:60px;" id="limit1" class="inputbox" size="1" onchange="
						document.frm.page.value = 1;
						document.frm.limit2.value = document.frm.limit1.value;
						document.frm.action = '/hscv/hscv/list/nolayout/1';
						document.frm.submit();
					">
						<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
						<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
						<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
						<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
						<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
						<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
						<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
						<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
						<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
						<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
					</select>
				</div>
				<div class="limit" style="float:right;"><?php echo $this->showPage; ?></div>
			</div>
		</th>
	</tr>
	<tr class=secondtitle>
		<th nowrap="nowrap">
			#
		</th>
		<th width="100%">Tên công việc</th>
		<th nowrap="nowrap">Chọn</th>
	</tr>
</thead>
<tfoot>
	<tr>
		<th colspan="3">
			<div class="pagination">
				<div class="limit"><b>Hiển thị #</b>
					<select name="limit2" style="width:60px;" id="limit2" class="inputbox" size="1" onchange="
						document.frm.page.value = 1;
						document.frm.limit1.value = document.frm.limit2.value;
						document.frm.action = '/hscv/hscv/list/nolayout/1';
						document.frm.submit();
					">
						<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
						<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
						<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
						<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
						<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
						<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
						<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
						<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
						<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
						<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
					</select>
				</div>
				<div style="float:right"><?php echo $this->showPage; ?></div>
			</div>
		</th>
	</tr>
</tfoot>
<tbody>
<?php 
	$stt=($this->page-1)*$this->limit;
	foreach($this->data as $row){
		$stt++;
?>
<tr>
	<td><?=$stt?></td>
	<td><?=$this->INNAME==1?QLVBDHCommon::highlightWords($row['NAME'],$this->NAME):$row['NAME']?></td>
	<td><input type=radio name=CHOOSEHSCV value="<?=$row['ID_HSCV']?>"></td>
</tr>
<?php
	}
?>
</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>
</body>
</html>