<form name=frm method=post>
<table>
		<tr>
			<td nowrap="nowrap">Lĩnh vực</td>
			<td nowrap="nowrap"><select name="ID_LV_MC" onchange="
						document.frm.action = '/hscv/hscv/multisend/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
						document.frm.submit();
				">
						<option value=0>--Tất cả lĩnh vực--</option>
						<?=linhvucmotcuaModel::ToCombo($this->linhvuc,$this->ID_LV_MC)?>
				</select></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap">Phường</td>
			<td nowrap="nowrap"><select name="ID_PHUONG" onchange="
						document.frm.action = '/hscv/hscv/multisend/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
						document.frm.submit();
				">
						<option value=0>--Tất cả các phường--</option>
						<option value=-1 <?=($this->ID_PHUONG==-1)?"selected":""?>>--Không xác định--</option>
						<?=DanhMucPhuongModel::ToCombo($this->phuong,$this->ID_PHUONG)?>
				</select></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap">Nội dung</td>
			<td nowrap="nowrap" colspan="3"><input type=text class=inputbox name=NAMECV value="<?=$this->NAME?>" size=50><input type=hidden name=SCOPE[] value=0 <?=count(array_keys($this->SCOPE,2))>0?"checked":""?>></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap">Tên công dân</td>
			<td nowrap="nowrap" colspan="3"><input type=text class=inputbox name=NAMECD value="<?=$this->TENTOCHUCCANHAN?>" size=50><input type=hidden name=SCOPE[] value=0 <?=count(array_keys($this->SCOPE,2))>0?"checked":""?>></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap">Mã biên nhận</td>
			<td nowrap="nowrap" colspan="3"><input type=text class=inputbox name=MABIENNHAN value="<?=$this->MAHOSO?>" size=50><input type=hidden name=SCOPE[] value=0 <?=count(array_keys($this->SCOPE,2))>0?"checked":""?>></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap">Từ ngày</td>
			<td nowrap="nowrap"><?=QLVBDHCommon::calendar($this->NGAY_BD,"NGAY_BD","NGAY_BD") ?> Đến ngày <?=QLVBDHCommon::calendar($this->NGAY_KT,"NGAY_KT","NGAY_KT") ?></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap" colspan="3"><input type=submit value="Tìm kiếm"></td>
			<td width="100%"></td>
		</tr>
	</table>
	<table class=adminlist>
		<thead>
			<tr>
				<th nowrap>Chuyển cho</th>
				<th width=100%>
					<?=QLVBDHCommon::writeSelectDepartmentUserWithSelAndAction("ID_DEP","ID_U_RECEIVE",$this->ID_U_RECEIVE,1,"document.frm.submit();")?>
					<script>
						document.frm.ID_DEP.value="<?=$this->ID_DEP?>";
						FillComboByComboWithSel(document.frm.ID_DEP,document.getElementById("ID_U_RECEIVE"),ARR_ID_U_RECEIVE,'<?=$this->ID_U_RECEIVE?>');
					</script>
					<input type=button value="Chuyển" onclick="CreateButtonClick();">
				</th>
			</tr>
			<tr>
				<th nowrap>#</th>
				<th width=100%>Tên hồ sơ</th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<th colspan=2></th>
			</tr>
		</tfoot>
		<tbody>
			<?php
			$stt=0;
				foreach($this->data as $row){
					$sendable=false;
					$lastlog = WFEngine::GetCurrentTransitionInfoByIdHscv($row['ID_HSCV']);
					$action = WFEngine::GetNextTransitions($lastlog['ID_PI'],$this->ID_U);
					for($actioncnt = 0; $actioncnt<count($action);$actioncnt++){
						if(WFEngine::HaveSendAbleByTransition($action[$actioncnt]['ID_T'],$this->ID_U_RECEIVE)){
							$action[$actioncnt]["SEND"]=1;
							$sendable=true;
						}else{
							$action[$actioncnt]["SEND"]=0;
						}
					}
					//var_dump($action);
					if($sendable==false)continue;
					$stt++;
			?>
			<tr class="row<?=$i?>">
				<td rowspan=2><?=$stt?></td>
				<td>
					<B><?=$row['NAME']?> <font color=red>(<?=$lastlog['AC_NAME']?>)</font></B>
					<?php
						if($lastlog['NOIDUNG']!=""){
					?>
					<br><I><?=$lastlog['NOIDUNG']?></I>
					<?php
						}
					?>
				</td>
			</tr>
			<tr class="row<?=$i?>">
				<td>
					<script>
						var ARR_HANXL_<?=$row['ID_HSCV']?> = new Array();
						<?php
							//var_dump($action);
							foreach($action as $actionitem){
								if($actionitem['SEND']==1){
									echo "ARR_HANXL_".$row['ID_HSCV']."[ARR_HANXL_".$row['ID_HSCV'].".length] = new Array();";
									echo "ARR_HANXL_".$row['ID_HSCV']."[ARR_HANXL_".$row['ID_HSCV'].".length-1][0] = '".$actionitem['ID_T']."';";
									echo "ARR_HANXL_".$row['ID_HSCV']."[ARR_HANXL_".$row['ID_HSCV'].".length-1][1] = '".$actionitem['HANXULY']."';";
								}
							}
						?>
					</script>
					<input type=radio name=ID_T_<?=$row['ID_HSCV']?> value=0 checked onclick="changelc(ARR_HANXL_<?=$row['ID_HSCV']?>,<?=$row['ID_HSCV']?>,this.value);"> Không thực hiện
					<?php
						foreach($action as $actionitem){
							if($actionitem['SEND']==1){
								echo "<input type=radio name=ID_T_".$row['ID_HSCV']." value=".$actionitem['ID_T']." onclick='changelc(ARR_HANXL_".$row['ID_HSCV'].",".$row['ID_HSCV'].",this.value);'>".$actionitem['NAME']."";
							}
						}
					?>
					<br>Hạn xử lý <?=QLVBDHCommon::createInputHanxuly('HANXULY'.$row['ID_HSCV'],'HANXULY[]','0')?>
					<input type=hidden name=ID_HSCV[] value="<?=$row['ID_HSCV']?>">
				</td>
			</tr>
			<?php
					$i = (-1+$i)*-1;
				}
			?>
		</tbody>
	</table>
</form>
<script>
	function CreateButtonClick(){
		document.frm.action = "/hscv/hscv/multisendsave";
		document.frm.submit();
	}
	function changelc(arrhxl,idhscv,idlc){
		//duyet han xu ly
		for(var i=0;i<arrhxl.length;i++){
			if(arrhxl[i][0]==idlc){
				if(arrhxl[i][1]>1){
					/*
					<input id='HANXULY2193' type=textbox onkeypress='return isNumberKey(event)' name='temp_HANXULY[]' size=3 maxlength=3 value='2' onchange='document.getElementById("real_HANXULY2193").value=this.value/document.frm.type_real_HANXULY2193.value;'><input style='display:none' type=text id='real_HANXULY2193' name='HANXULY[]' value='2'><input checked type=radio name='type_HANXULY2193' id='type_1_HANXULY2193' onclick="document.frm.type_real_HANXULY2193.value=1;document.getElementById('real_HANXULY2193').value=document.getElementById('HANXULY2193').value/this.value;" value=1>ngày <input  type=radio name='type_HANXULY2193' id='type_8_HANXULY2193' onclick="document.frm.type_real_HANXULY2193.value=8;document.getElementById('real_HANXULY2193').value=document.getElementById('HANXULY2193').value/this.value;" value=8>giờ<input style='display:none' type=text id='type_real_HANXULY2193' name='type_real_HANXULY2193' value='1'>					<input type=hidden name=ID_HSCV[] value="2193">*/
					document.getElementById('HANXULY'+idhscv).value=arrhxl[i][1];
					document.getElementById('real_HANXULY'+idhscv).value=arrhxl[i][1];
					document.getElementById('type_1_HANXULY'+idhscv).checked=true;
					document.getElementById('type_real_HANXULY'+idhscv).value=1;
				}else{
					document.getElementById('HANXULY'+idhscv).value=arrhxl[i][1]*8;
					document.getElementById('real_HANXULY'+idhscv).value=arrhxl[i][1];
					document.getElementById('type_8_HANXULY'+idhscv).checked=true;
					document.getElementById('type_real_HANXULY'+idhscv).value=8;
				}
				break;
			}
		}
	}
</script>