<table class=adminlist>
	<thead>
		<tr>
			<th nowrap="nowrap">#</th>
			<th width="100%">Tên Thủ Tục</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3"></th>
		</tr>
	</tfoot>
	<tbody>
	<?php
	$i=0;
	$stt=1;
	if(count($this->data)>0){
		foreach($this->data as $row){
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap="nowrap">
				<?php echo $stt; ?>
			</td>
			<td width="100%">
				<?=$row["TEN_THUTUC"]?>
			</td>
		</tr>
<?php
			$stt++;
		}
	}else{
?>
		<tr class="row<?=$i?>">
			<td colspan="3">
				Chưa có chi tiết thủ tục nào
			</td>
		</tr>
<?php
	}
?>

	</tbody>
</table>

