<?php
	
?>
<table class=adminlist>
	<thead>
		<tr>
			<th nowrap="nowrap">#</th>
			<th width="100%">Nội dung bút phê</th>
			<th nowrap="nowrap">Ngày BP</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3"></th>
		</tr>
	</tfoot>
	<tbody>
<?php
	$stt=0;
	$i=0;
	foreach($this->data as $row){
		$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap="nowrap">
				<?php echo $stt ?>
			</td>
			<td width="100%">
				<b><?=$row["EMPNAME"]?></b>: <?=$row["NOIDUNG"] ?>
			</td>
			<td nowrap="nowrap">
				<?=$row["NGAYBP"]==""?"":date("d/m/Y H:i:s",strtotime($row["NGAYBP"]))?>
			</td>
		</tr>
<?php
	}
?>
	</tbody>
</table>