<table class=adminlist>
	<thead>
		<tr>
			<th nowrap="nowrap">STT</th>
			<th width="100%">File hướng dẫn</th>
		</tr>
	</thead>
	<tbody>
		
		<tr>
			<td nowrap="nowrap">1</td>
			<td width="100%"><a href="/images/MotCua.doc" target="_blank">Hướng dẫn sử dụng phần mềm Một cửa điện tử</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">2</td>
			<td width="100%"><a href="/images/Huongdancaidat.docx" target="_blank">Hướng dẫn cài đặt phần mềm Một cửa điện tử</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">3</td>
			<td width="100%"><a href="/images/tracuucamung.doc" target="_blank">Hướng dẫn sử dụng màn hình cảm ứng dành cho QTHT</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">4</td>
			<td width="100%"><a href="/images/Qlvbdh_Alert.zip" target="_blank">File cài đặt trao đổi, thông báo, nhắc nhở</a></td>
		</tr>
		
		<tr>
			<td nowrap="nowrap">5</td>
			<td width="100%"><a href="/images/vstor.exe" target="_blank">File hỗ trợ môi trường cho word 2003</a> <a href="/images/2003.msi" target="_blank">File cài đặt addin cho Word 2003</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">6</td>
			<td width="100%"><a href="/images/2007.exe" target="_blank">File cài đặt addin cho Word 2007</a></td>
		</tr>
	</tbody>
</table>