<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<?php
	foreach($this->sel_lhss as $loai){
	
		$this->data = HosochuatiepnhanModel::reportHoso($this->trangthai,$loai, $this->fromdate, $this->todate);
		if(count($this->data) >0){
			
?>
		<b><?=HosochuatiepnhanModel::getTenLoai($loai);?></b>
		<br>
		<br>
		<table class=adminlist>
		 <thead>
			<tr>
				<th nowrap >STT</th>			
				<th nowrap >Mã hồ sơ</th>
				<th nowrap >Đơn vị cá nhân</th>
			<?php
				$arr_custom_fields = motcua_hosoModel::Customfields($loai);
				foreach($arr_custom_fields as $cus){
			?>	
				<th nowrap ><?=$cus["NAME_DISPLAY"]?></th>
			<?php }
			?>					
				<th nowrap >Địa chỉ</th>
				<th nowrap >Điện thoại</th>
				<th nowrap >Email</th>
				<th nowrap >Ngày nhận</th>
			</tr>
		 </thead>
		 <tbody>
		<?php require_once 'qtht/models/LoaiVanBanModel.php';
		require_once 'qtht/models/CoquanModel.php'; 
		require_once 'qtht/models/DepartmentsModel.php';
		require_once 'qtht/models/UsersModel.php';
		$stt=1;
		foreach($this->data as $row){
		?>
			<tr>
			<td><?=$stt?></td>
			<td  valign=top rowspan=<?php echo $d ?>><?php  echo $row["MAHOSO"]; ?></td>
			<td  valign=top rowspan=<?php echo $d ?>><?php  echo $row["TENTOCHUCCANHAN"]; ?></td>
			<?php
				foreach($arr_custom_fields as $cus){
			?>	
				<td nowrap >
					<?php 
						if($cus["TYPE"] == "DATE"){
							echo implode("/",array_reverse(explode("-",$row[$cus["NAME_COLUMN"]])));
						}else{
							echo $row[$cus["NAME_COLUMN"]];
						}
						?>
				</td>
			<?php }
			?>
			<td   valign=top rowspan=<?php echo $d ?>><?php  echo $row["DIACHI"]?></td>
			<td   valign=top rowspan=<?php echo $d ?>><?php  echo $row["DIENTHOAI"]?></td>
			<td   valign=top rowspan=<?php echo $d ?>><?php  echo $row["EMAIL"]?></td>
			<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo QLVBDHCommon::MysqlDateToVnDate($row["GUI_LUC"])?></td>
			</tr>
		<?php  	
			$stt++;
			
			}
			
		  } ?>
		 </tbody>
		 <tfoot>
		 </tfoot>
		</table>
		<br>
		<br>
		<br>
<?php 
}
?>
<p id=lasttext></p>
</body>
</html>
<script>
var iframeElement = window.parent.document.getElementById('reportview');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 

</script>