<form name=frmListMenus method="post" action="/qtht/menus/">
	<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo $this->search ?>" class="text_area" onchange="document.frmListMenus.submit();" />
				<button onclick="document.frmListMenus.submit();">Tìm</button>
				<button onclick="document.getElementById('search').value='';document.frmListMenus.submit();">Làm lại</button>
			</td>
			<td nowrap="nowrap">				
			</td>
		</tr>
	</table>
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>#</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th width="100%">Tên menu</th>
			<th nowrap>Có popup</th>			
			<th nowrap>Url</th>
			<th nowrap>Action</th>
			<th nowrap><a href="#" onclick="
				document.frmListMenus.action = '/qtht/menus/index/code/order';
				document.frmListMenus.submit();
			">Thứ tự</a></th>
			
			
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="7">
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row )
	{
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row['ID_MNU'] ?>'>
			</td>
			<td width=100%>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_MNU'] ?>);">
				<?php echo str_repeat("----",$row['LEVEL']-1).htmlspecialchars($row['NAME']) ?>
				</a>
			</td>
			<td><a href="<?php echo $this->url(array('controller'=>'menus', 
            'action'=>'input', 'id'=>$row['ID_MNU'],'popup'=>$row['POPUP']));?>"><?php if($row['POPUP']==1) echo 'Rồi';
			else echo 'Chưa';?></a></td>
			<td><?php echo $row['URL'];?></td>
			<td><?php echo $row['URL_ACTION'];?></td>	
			<td><input type=hidden name=ID_ORDER[] value="<?=$row['ID_MNU']?>"><input size=4 type=text name=ORDER[] value="<?=$row['ORDERS']?>"></td>
			
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
<input type="hidden" name="comeFrom" value="listForm">
</form>
<script>
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","Chọn ít nhất một menu để xoá.");
	if(mess){
		if(confirm("<?php echo 'Bạn muốn xóa mục này!'; ?>")){
			document.frmListMenus.action = "/qtht/menus/delete";
			document.frmListMenus.submit();
		}
	}else{
		alert("Chọn ít nhất một menu để xoá.");
	}
}
function AddNewButtonClick()
{
	document.frmListMenus.action = "/qtht/menus/input";
	document.frmListMenus.submit();
}
function ItemClick(id)
{
	document.frmListMenus.action = "/qtht/menus/input/id/"+id;
	document.frmListMenus.submit();
}
</script>




