<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<?php
require_once 'report/models/tamnghivanghihanModel.php'; ?>
<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="lkjhgloctteeeesssrrrrrrr_files/filelist.xml">
<link rel=Edit-Time-Data href="lkjhgloctteeeesssrrrrrrr_files/editdata.mso">
<link rel=OLE-Object-Data href="lkjhgloctteeeesssrrrrrrr_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:LastAuthor>User</o:LastAuthor>
  <o:Created>2009-11-01T07:52:52Z</o:Created>
  <o:LastSaved>2009-11-01T07:54:05Z</o:LastSaved>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:1.0in .75in 1.0in .75in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;
	mso-page-orientation:landscape;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	text-align:center;}
.xl25
	{mso-style-parent:style0;
	text-align:center;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;}
.xl26
	{mso-style-parent:style0;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;}
.xl27
	{mso-style-parent:style0;
	text-align:center;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid black;
	background:silver;
	mso-pattern:auto none;}
.xl28
	{mso-style-parent:style0;
	text-align:center;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;}
.xl29
	{mso-style-parent:style0;
	text-align:center;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;}
.xl30
	{mso-style-parent:style0;
	mso-number-format:"Short Date";
	text-align:center;
	border-top:.5pt solid black;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid black;
	background:silver;
	mso-pattern:auto none;}
.xl31
	{mso-style-parent:style0;
	mso-number-format:"Short Date";
	text-align:center;
	border-top:.5pt solid black;
	border-right:none;
	border-bottom:none;
	border-left:none;
	background:silver;
	mso-pattern:auto none;}
.xl32
	{mso-style-parent:style0;
	mso-number-format:"Short Date";
	text-align:center;
	border-top:.5pt solid black;
	border-right:.5pt solid black;
	border-bottom:none;
	border-left:none;
	background:silver;
	mso-pattern:auto none;}
.xl33
	{mso-style-parent:style0;
	border-top:none;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid windowtext;}
.xl34
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl35
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl36
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl37
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl38
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid black;
	white-space:normal;}
.xl39
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl40
	{mso-style-parent:style0;
	border-top:none;
	border-right:.5pt solid black;
	border-bottom:none;
	border-left:none;}
.xl41
	{mso-style-parent:style0;
	mso-number-format:"Short Date";
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl42
	{mso-style-parent:style0;
	mso-number-format:"Short Date";
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl43
	{mso-style-parent:style0;
	mso-number-format:"Short Date";
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl44
	{mso-style-parent:style0;
	mso-number-format:"Short Date";
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:Scale>83</x:Scale>
      <x:HorizontalResolution>150</x:HorizontalResolution>
      <x:VerticalResolution>200</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>60</x:PageBreakZoom>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>8</x:ActiveRow>
       <x:ActiveCol>3</x:ActiveCol>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>9750</x:WindowHeight>
  <x:WindowWidth>15315</x:WindowWidth>
  <x:WindowTopX>360</x:WindowTopX>
  <x:WindowTopY>60</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext="edit" spidmax="1025"/>
</xml><![endif]-->
</head>

<body link=blue vlink=purple>

<table x:str border=0 cellpadding=0 cellspacing=0 width=1129 style='border-collapse:
 collapse;table-layout:fixed;width:849pt'>
 <col width=36 style='mso-width-source:userset;mso-width-alt:1316;width:27pt'>
 <col width=42 style='mso-width-source:userset;mso-width-alt:1536;width:32pt'>
 <col width=46 style='mso-width-source:userset;mso-width-alt:1682;width:35pt'>
 <col width=52 style='mso-width-source:userset;mso-width-alt:1901;width:39pt'>
 <col width=48 style='mso-width-source:userset;mso-width-alt:1755;width:36pt'>
 <col width=45 style='mso-width-source:userset;mso-width-alt:1645;width:34pt'>
 <col width=64 style='width:48pt'>
 <col width=90 style='mso-width-source:userset;mso-width-alt:3291;width:68pt'>

 <col width=64 style='width:48pt'>
 <col width=110 style='mso-width-source:userset;mso-width-alt:4022;width:83pt'>
 <col width=84 style='mso-width-source:userset;mso-width-alt:3072;width:63pt'>
 <col width=64 span=7 style='width:48pt'>
 <tr height=17 style='height:12.75pt'>
  <td colspan=5 height=17 class=xl24 width=224 style='height:12.75pt;
  width:169pt'>UBND HUYỆN DAKDOA</td>
  <td width=45 style='width:34pt'></td>
  <td width=64 style='width:48pt'></td>

  <td width=90 style='width:68pt'></td>
  <td colspan=8 class=xl24 width=578 style='width:434pt'>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td colspan=5 height=17 class=xl26 style='height:12.75pt'>PHÒNG TC - KH</td>
  <td colspan=3 style='mso-ignore:colspan'></td>

  <td colspan=8 class=xl24>Độc lập - Tự do - Hạnh Phúc</td>
  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td colspan=5 height=17 class=xl24 style='height:12.75pt'>Số:……/</td>
  <td colspan=3 style='mso-ignore:colspan'></td>
  <td colspan=8 class=xl24><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>

  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=18 style='height:12.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=2 style='height:12.75pt;mso-ignore:colspan'></td>
  <td colspan=13 class=xl24>DANH SÁCH CÁC HỘ KINH DOANH XIN TẠM NGHĨ VÀ NGHĨ
  HẲN</td>

  <td colspan=3 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=6 style='height:12.75pt;mso-ignore:colspan'></td>
  <td colspan=5 class=xl24><?php echo $this->thu;?> NĂM <?php echo $this->year;?></td>
  <td colspan=7 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=34 style='height:25.5pt;mso-xlrowspan:2'>

  <td height=34 colspan=18 style='height:25.5pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=29 style='mso-height-source:userset;height:21.75pt'>
  <td height=29 colspan=3 style='height:21.75pt;mso-ignore:colspan'></td>
  <td class=xl25>Số</td>
  <td colspan=2 class=xl27 style='border-right:.5pt solid black;border-left:
  none'>Số VB</td>
  <td colspan=2 class=xl27 style='border-right:.5pt solid black;border-left:
  none'>Tên tổ chức cá nhân</td>

  <td colspan=2 class=xl27 style='border-right:.5pt solid black;border-left:
  none'>Địa chỉ kinh doanh</td>
  <td colspan=3 class=xl27 style='border-right:.5pt solid black;border-left:
  none'>Ngành hàng kinh doanh</td>
  <td colspan=3 class=xl30 style='border-right:.5pt solid black;border-left:
  none'>Thời gian</td>
  <td colspan=2 style='mso-ignore:colspan'></td>
   <?php foreach($this->dataub as $row){?>
 </tr>
 <tr height=34 style='mso-height-source:userset;height:25.5pt'>
  <td height=34 colspan=2 style='height:25.5pt;mso-ignore:colspan'></td>

  <td class=xl40>&nbsp;</td>
  <td class=xl34 width=52 style='border-top:none;width:39pt'><?=$row["SO"]?></td>
  <td colspan=2 class=xl36 width=93 style='border-right:.5pt solid black;
  border-left:none;width:70pt'><?php if(count($row["SOKYHIEU"])>0){
    echo $row["SOKYHIEU"];}else{
	  $skh=tamnghivanghihanModel::getSKH($row["ID_HSCV"]);	  
	  foreach($skh as $skh1){ 
            echo $skh1["SOKYHIEU"]; ?> </br>	  
	 <?php }}?> </td>
  <td colspan=2 class=xl38 width=154 style='border-right:.5pt solid black;
  border-left:none;width:116pt'><?=$row["TENTOCHUCCANHAN"]?></td>
  <td colspan=2 class=xl38 width=174 style='border-right:.5pt solid black;
  border-left:none;width:131pt'><?=$row['DIACHIKINHDOANH']?></td>
  <td colspan=3 class=xl38 width=212 style='border-right:.5pt solid black;
  border-left:none;width:159pt'><?=$row['NGANHHANGKD']?></td>
   <?php if(count($row['NGAYNGHIHAN'])>0) {?>
  <td colspan=3 class=xl41 width=192 style='border-right:.5pt solid black;
  border-left:none;width:144pt'>Nghỉ hẳn <?=QLVBDHCommon::MysqlDateToVnDate($row["NGAYNGHIHAN"])?></td>
  <?php }else{?>
   <td colspan=3 class=xl41 width=192 style='border-right:.5pt solid black;
  border-left:none;width:144pt'>            
	            <?php  echo QLVBDHCommon::MysqlDateToVnDate($row['TAMNGHI_BATDAU'])."->".QLVBDHCommon::MysqlDateToVnDate($row['TAMNGHI_KETTHUC']); ?></td>
  <?php }?>
  <td class=xl33 style='border-left:none'>&nbsp;</td>
  <td></td>
 </tr>
 <?php }?>
 <tr height=30 style='mso-height-source:userset;height:22.5pt'>
  <td height=30 colspan=3 style='height:22.5pt;mso-ignore:colspan'></td>
  <td colspan=13 class=xl36 width=877 style='border-right:.5pt solid black;
  width:659pt'>PHÒNG TÀI CHÍNH KẾ HOẠCH</td>
  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>
<?php foreach($this->datatckh as $r){?>
 <tr height=36 style='mso-height-source:userset;height:27.0pt'>
  <td height=36 colspan=2 style='height:27.0pt;mso-ignore:colspan'></td>
  <td style='solid black'></td>
  <td class=xl35 width=52 style='width:39pt'><?=$r["SO"]?></td>
  <td colspan=2 class=xl38 width=93 style='border-right:.5pt solid black;
  border-left:none;width:70pt'><?php if(count($r["SOKYHIEU"])>0){
    echo $r["SOKYHIEU"];}else{
	  $skh=tamnghivanghihanModel::getSKH($r["ID_HSCV"]);
	  foreach($skh as $skh1){ 
            echo $skh1["SOKYHIEU"]; ?> </br>	  
	 <?php }}?>
	  </td>
  <td colspan=2 class=xl38 width=154 style='border-right:.5pt solid black;
  border-left:none;width:116pt'><?=$r["TENTOCHUCCANHAN"]?></td>
  <td colspan=2 class=xl36 width=174 style='border-right:.5pt solid black;
  border-left:none;width:131pt'><?=$r['DIACHIKINHDOANH']?></td>

  <td colspan=3 class=xl36 width=212 style='border-right:.5pt solid black;
  border-left:none;width:159pt'><?=$r['NGANHHANGKD']?></td>
  <?php if(count($r['NGAYNGHIHAN'])>0) {?>
  <td colspan=3 class=xl41 width=192 style='border-right:.5pt solid black;
  border-left:none;width:144pt'>Nghĩ hẳn <?=QLVBDHCommon::MysqlDateToVnDate($r["NGAYNGHIHAN"])?></td>
  <?php }else{?>
	           <td colspan=3 class=xl41 width=192 style='border-right:.5pt solid black;
  border-left:none;width:144pt'>	            
	            <?php  echo QLVBDHCommon::MysqlDateToVnDate($r['TAMNGHI_BATDAU'])."->".QLVBDHCommon::MysqlDateToVnDate($r['TAMNGHI_KETTHUC']); ?></td>
		<?php }?>
  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>
 <?php } ?>
 <tr height=34 style='height:25.5pt;mso-xlrowspan:2'>
  <td height=34 colspan=18 style='height:25.5pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>

  <td height=17 style='height:12.75pt'></td>
  <td colspan=2 class=xl26>Nơi nhận:</td>
  <td colspan=3 class=xl24></td>
  <td colspan=5 style='mso-ignore:colspan'></td>
  <td colspan=5 class=xl24>TRƯỞNG PHÒNG TÀI CHÍNH - KẾ HOẠCH</td>
  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>

  <td height=17 style='height:12.75pt'></td>
  <td colspan=3 style='mso-ignore:colspan'>. Chi cục Thuế</td>
  <td class=xl24></td>
  <td colspan=8 style='mso-ignore:colspan'></td>
  <td colspan=4 class=xl24></td>
  <td></td>
 </tr>
 <tr height=17 style='height:12.75pt'>

  <td height=17 style='height:12.75pt'></td>
  <td colspan=3>. QLTT(để kiểm tra)</td>
  <td colspan=14 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 style='height:12.75pt'></td>
  <td colspan=4 style='mso-ignore:colspan'>. Các địa phương liên quan</td>
  <td colspan=13 style='mso-ignore:colspan'></td>

 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 style='height:12.75pt'></td>
  <td colspan=2>. Lưu</td>
  <td colspan=15 style='mso-ignore:colspan'></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>

  <td width=36 style='width:27pt'></td>
  <td width=42 style='width:32pt'></td>
  <td width=46 style='width:35pt'></td>
  <td width=52 style='width:39pt'></td>
  <td width=48 style='width:36pt'></td>
  <td width=45 style='width:34pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=90 style='width:68pt'></td>
  <td width=64 style='width:48pt'></td>

  <td width=110 style='width:83pt'></td>
  <td width=84 style='width:63pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>

 </tr>
 <![endif]>
</table>
</body>
</html>
<script>print();</script>