<?php
$phuong = new DanhMucPhuongModel();
$phuong = $phuong->SelectAll(0,0,"");
$loai = new LoaiModel();
$loai->_linhvuc = $this->param['sel_lv'];
$loai = $loai->SelectAll(0,0,"");
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="Book1_files/filelist.xml">
<link rel=Edit-Time-Data href="Book1_files/editdata.mso">
<link rel=OLE-Object-Data href="Book1_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>nguyennd</o:Author>
  <o:LastAuthor>nguyennd</o:LastAuthor>
  <o:LastPrinted>2009-08-25T15:45:14Z</o:LastPrinted>
  <o:Created>2009-08-25T14:43:47Z</o:Created>
  <o:LastSaved>2009-08-25T15:59:24Z</o:LastSaved>
  <o:Company>Hewlett-Packard</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.2in .2in .2in .2in;
	mso-header-margin:.2in;
	mso-footer-margin:.2in;
	mso-page-orientation:landscape;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl25
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl26
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl27
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl28
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl29
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl30
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl31
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl32
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl33
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:right;}
.xl34
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl35
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl36
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:Fixed;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
.xl37
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:top;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl38
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:Fixed;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:DefaultRowHeight>315</x:DefaultRowHeight>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>13</x:ActiveRow>
       <x:ActiveCol>5</x:ActiveCol>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>13575</x:WindowHeight>
  <x:WindowWidth>15315</x:WindowWidth>
  <x:WindowTopX>360</x:WindowTopX>
  <x:WindowTopY>45</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]-->
</head>

<body link=blue vlink=purple class=xl24>

<table x:str border=0 cellpadding=0 cellspacing=0 width=1106 style='border-collapse:
 collapse;table-layout:fixed;width:826pt'>
 <col class=xl24 width=221 style='mso-width-source:userset;mso-width-alt:8082;
 width:166pt'>
 <col class=xl24 width=59 span=255 style='mso-width-source:userset;mso-width-alt:
 2157;width:44pt'>
 <tr height=21 style='height:15.75pt'>
  <td colspan=4 height=21 class=xl25 width=398 style='height:15.75pt;
  width:298pt'><?=mb_strtoupper($this->config->sys_info->company,"utf-8"). " ".mb_strtoupper($this->config->sys_info->city,"utf-8") ?></td>
  <td class=xl24 width=59 style='width:44pt'></td>
  <td class=xl26 width=59 style='width:44pt'></td>
  <td class=xl24 width=59 style='width:44pt'></td>
  <td class=xl24 width=59 style='width:44pt'></td>
  <td class=xl24 width=59 style='width:44pt'></td>
  <td class=xl24 width=59 style='width:44pt'></td>
  <td colspan=6 class=xl31 width=354 style='width:264pt'>C&#7896;NG HÒA XÃ
  H&#7896;I CH&#7910; NGH&#296;A VI&#7878;T NAM</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=4 height=21 class=xl31 style='height:15.75pt'><?=mb_strtoupper($this->config->sys_info->motcuaname,"utf-8")?></td>
  <td class=xl24></td>
  <td class=xl27></td>
  <td colspan=4 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=6 class=xl32>Ð&#7897;c l&#7853;p - T&#7921; do - H&#7841;nh phúc</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=5 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
  <td class=xl28></td>
  <td colspan=4 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=6 class=xl33><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=16 height=21 class=xl31 style='height:15.75pt'>TH&#7888;NG KÊ
  S&#7888; L&#431;&#7906;NG H&#7890; S&#416;</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=16 height=21 class=xl34 style='height:15.75pt'>Từ ngày <?=$this->fromdate?> đến ngày <?=$this->todate?> năm <?=date("Y")?></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=16 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=42 style='height:31.5pt'>
  <td height=42 class=xl29 width=221 style='height:31.5pt;width:166pt'>H&#7890;
  S&#416;</td>
<?php
	foreach($phuong as $itemphuong){
?>
	<td class=xl30 width=59 style='width:44pt'><?=$itemphuong["TENPHUONG"]?></td>
<?php
	}
?>
  <td class=xl30 width=59 style='width:44pt'>Không rõ</td>
  <td class=xl30 width=59 style='width:44pt'>T&#7896;NG C&#7896;NG</td>
  <td colspan=12 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
<?php
	$cntallphuong = array();
	$cntall = 0;
	foreach($loai as $itemloai){
		$tong = 0;
?>
 <tr>
  <td class=xl35 width=221 style='width:166pt' x:num><?=$itemloai["TENLOAI"]?></td>
<?php
			$stt=0;
			foreach($phuong as $itemphuong){
				$cntphuong = TiepnhanhosomotcuaModel::CountHoso($this->param['sel_loaitk'],$itemloai["ID_LOAIHOSO"],$itemphuong["ID_PHUONG"],$this->xfromdate,$this->xtodate,$this->xfromdategt,$this->xtodategt);
				$cntallphuong[$stt] += $cntphuong;
				$stt++;
				$tong += $cntphuong;
				$cntall += $cntphuong;
			?>
			<td class=xl36><?=$cntphuong?></td>
			<?php
			}
			$cntphuong = TiepnhanhosomotcuaModel::CountHoso($this->param['sel_loaitk'],$itemloai["ID_LOAIHOSO"],0,$this->xfromdate,$this->xtodate,$this->xfromdategt,$this->xtodategt);
			$tong += $cntphuong;
			$cntallphuong[$stt] += $cntphuong;
			$cntall += $cntphuong;
?>
  <td class=xl36><?=$cntphuong?></td>
  <td class=xl38><?=$tong?></td>
  <td colspan=12 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
	<?php
		}
	?>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl37 width=221 style='height:15.75pt;border-top:none;
  width:166pt'>T&#7896;NG C&#7896;NG</td>
  <?php
			$stt=0;
			foreach($phuong as $itemphuong){
			?>
			<td class=xl38><?=$cntallphuong[$stt]?></tD>
			<?php
				$stt++;
			}
			?>

  <td class=xl38><?=$cntallphuong[$stt]?></td>
  <td class=xl38><?=$cntall?></td>
  <td colspan=12 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=16 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=3 height=21 class=xl31 style='height:15.75pt'>Ng&#432;&#7901;i
  nh&#7853;n h&#7891; s&#417;</td>
  <td colspan=10 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=3 class=xl31>Ng&#432;&#7901;i bàn giao h&#7891; s&#417;</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=16 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=2 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
  <td class=xl25></td>
  <td colspan=13 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=16 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=2 class=xl25 style='height:15.75pt;mso-ignore:colspan'></td>
  <td colspan=11 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=3 class=xl25><?=Zend_Registry::get("auth")->getIdentity()->FULLNAME?></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=221 style='width:166pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=59 style='width:44pt'></td>
 </tr>
 <![endif]>
</table>

</body>

</html>
<?php if($this->view->param["excel"]!="1"){ ?>
<script>print();</script>
<?php } ?>