<?php 
require_once 'qtht/models/SoVanBanModel.php';
require_once 'qtht/models/LoaiVanBanModel.php'; 
require_once 'qtht/models/CoQuanModel.php'; 
?>

<form name="frm" action="<?echo $this->baseUrl()?>/qtht/DanhMucSoVanBan" method="post"> 
<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo htmlspecialchars($this->search); ?>" class="text_area" onchange="document.frm.page.value=1;document.frm.submit();" />
				<button onclick="document.frm.submit();">Tìm</button>
				<button onclick="document.getElementById('search').value='';document.frm.submit();">Làm lại</button>
			</td>
			<td nowrap="nowrap">
				<select name="filter_object" id="filter_object" class="inputbox" size="1" onchange="document.frm.submit();">
					<?php 
						echo SoVanBanModel::toComboFilter($this->filter_object);
						//echo ClassModel::ToCombo($this->class,$this->filter_object); 
					?>
				</select>
			</td>
		</tr>
</table>


<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>STT</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th nowrap>Tên</th>
			<th nowrap>Loại </th>
			<th nowrap>Lĩnh vực </th>
			<th>Loại văn bản liên quan</th>
			<th>Cơ quan</th>
			<th nowrap>Đã được sử dụng</th>
			<th nowrap>Năm</th>
		</tr>
	</thead>
	
	<tbody>
<?php
$stt=0;
$i=0;

foreach ($this->data as $row ){
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row->ID_SVB ?>'>
			</td>
			<td width=100%>
				<a href="#" onclick = "ItemClick(<?php echo $row->ID_SVB?>);">
				<?php echo htmlspecialchars($row->NAME) ?>
				</a>
			</td>
		
		<td nowrap>
	<?php $type = $row->TYPE; 
	
	switch($type)
	{
		case 0:
			echo "Chưa Xác Định";
			break;
		case 1:
			echo "Văn Bản Đến";
			break;
		case 2:
			echo "Văn Bản Đi";
			break;
		case 3: 
			echo "Hồ sơ một cửa";
			break;
		default:
			echo "Không biết";
			break;
	}
	?>
	 
	</td>

	
	<td nowrap><?php 
		if((int)$row->ID_LV_MC == 0)
			echo "Không có";
		else	
			echo htmlspecialchars(SoVanBanModel::getNamLV_MCById((int)$row->ID_LV_MC))?>
	</td>
	<td nowrap><?php 
		if((int)$row->ID_LVB == 0)
			echo "Không có";
		else	
		echo htmlspecialchars(LoaiVanBanModel::getNameById($row->ID_LVB))?>
	</td>
	
	<td nowrap><?php 
		if((int)$row->ID_CQ == 0)
			echo "Không có";
		else	
		echo  CoQuanModel::getNameById($row->ID_CQ)?>
	</td>
		<td nowrap>
	<?php
	$active = $row->ACTIVE;
	if($active == 1)
		echo "Có";
	else 
		echo "Không";
	
	?>
	</td>
	<td><?=htmlspecialchars($row->YEAR)?></td>
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>	
	</tbody>
		
	<tfoot>
		<tr>
			<td colspan="9">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frm.page.value = 1;document.frm.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<script>
									document.frm.limit.value='<?php echo $this->limit ?>';
								</script>
							</select>
						</div>
						<div style="float:right"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>
</table>					
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>

<script>
function DeleteButtonClick()
{
var ln = 0;
	var arr = document.getElementsByName('DEL[]');
	for(var i = 0 ; i < arr.length ;i++ )
	{
		
		if(arr[i].checked == true)
		{
			ln = 1;
		}
	}
	if(ln == 1)
	{
		if(confirm("<?php echo DELETEQUESTION; ?>"))
		{
			document.frmListData.submit();
		}
	}
	else
	{
		alert("Bạn phải một dòng chọn để xóa");
	}
}
</script>
<script>

function DeleteButtonClick(){
	var ln = 0;
	var arr = document.getElementsByName('DEL[]');
	for(var i = 0 ; i < arr.length ;i++ ){
		if(arr[i].checked == true){
			ln = 1;
		}
	}
	if(ln == 1){
		if(confirm("<?php echo "Bạn có muốn xóa không"; ?>")){
			//document.URL=
			document.frm.action="/qtht/DanhMucSoVanBan/delete";
			document.frm.method="post";
			document.frm.submit();
		}
	}else{
		alert("Bạn phải một dòng chọn để xóa");
	}
}
function AddNewButtonClick(){
	//document.URL = "/qtht/DanhMucCoQuan/input";
	document.frm.action="/qtht/DanhMucSoVanBan/input";
	document.frm.method="post";
	document.frm.submit();
	
}
function ItemClick(id){
	//document.URL = "/qtht/DanhMucCoQuan/input/idCoQuan/"+id;
	document.frm.action="/qtht/DanhMucSoVanBan/input/idSVB/"+id;;
	document.frm.method="post";
	document.frm.submit();
}
</script>


