<?php 
require_once 'qtht/models/sovanbanModel.php';
?>

<!-- Khung lọc dữ liệu -->
<div>
<form name=frm action="/report/baocaochomuonhoso/indextke" method="POST">
<div>
<label><b>Ngày bắt đầu:</b></label>
<?=QLVBDHCommon::calendarfull($this->fromdate,"fromdate","fromdate") ?>
>>
<?=QLVBDHCommon::calendarfull($this->todate,"todate","todate") ?>
</div>
<span class="box_erro_area" id="ERRfromdate"></span>
<span class="box_erro_area" id="ERRtodate"></span>
<div class=clr></div>
<div>
<div>
<label><b>Tháng:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/1')">1
<?php 
$year = QLVBDHCommon::getYear();
$d = strtotime($year."-3-1") ;
$d = $d - 86400;
$str_cuoi2 =date('d/m',$d); 
 ?>
<input type="radio" name='sel_timedis' value="2" onclick="setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')" >2
<input type="radio" name='sel_timedis' value="3" onclick="setvalueDateD('1/3','31/3')">3
<input type="radio" name='sel_timedis' value="4" onclick="setvalueDateD('1/4','30/4')" >4
<input type="radio" name='sel_timedis' value="5" onclick="setvalueDateD('1/5','31/5')">5
<input type="radio" name='sel_timedis' value="6" onclick="setvalueDateD('1/6','30/6')">6
<input type="radio" name='sel_timedis' value="7" onclick="setvalueDateD('1/7','31/7')" >7
<input type="radio" name='sel_timedis' value="8" onclick="setvalueDateD('1/8','31/8')" >8
<input type="radio" name='sel_timedis' value="9" onclick="setvalueDateD('1/9','30/9')">9
<input type="radio" name='sel_timedis' value="10"onclick="setvalueDateD('1/10','31/10')">10
<input type="radio" name='sel_timedis' value="11" onclick="setvalueDateD('1/11','30/11')">11
<input type="radio" name='sel_timedis' value="12" onclick="setvalueDateD('1/12','31/12')">12
</div>
<div class=clr></div>
<div>
<label><b>Quý:</b></label>
<input type="radio" name='sel_timedis' value="I" onclick="setvalueDateD('1/1','31/3')">I
<input type="radio" name='sel_timedis' value="II" onclick="setvalueDateD('1/4','30/6')">II
<input type="radio" name='sel_timedis' value="III" onclick="setvalueDateD('1/7','30/9')">III
<input type="radio" name='sel_timedis' value="IV" onclick="setvalueDateD('1/10','31/12')">IV
</div>
<div class=clr></div>

<div>
<label><b>Năm:</b></label>
<input type="radio" name='sel_timedis' value="year" onclick="setvalueDateD('1/1','31/12')">
</div>
</div>
<div class=clr></div>
<br/>
<div>
<div style="float:left">
<label><b>Loại hồ sơ:</b></label>
<select name="sel_lhs" id="sel_lhs" >
	<option value=0>[Chọn tất cả]</option>
	<?php sovanbanModel::toComboNameLoaihosoluutru($this->id_lhs);?>
</select>
</div>	
</div>
<div class="clr"></div>
<input type=hidden id=h_isexel name=h_isexel value=0>
<input type=button value="Thống kê" onclick="thongke();">
<input type=button value="In" onclick="In();">
<input type=button value="Xuất excel" onclick="Excel();">
</form>

</div>
<div class="clr"></div>
<?php if($this->hienthi ==1){ ?>
<table class=adminlist>
	<thead>
		<tr>
		    <th>Tên loại</th>
			<th>Mượn chưa trả</th>
			<th>Mượn chưa trả(trễ)</th>
			<th>Mượn đã trả</th>
			<th>Mượn đã trả(trễ)</th>			
		</tr>
	</thead>
	<tbody>
			<?php
		global $db;
		if($this->id_lhs==0){
			$r = $db->query("SELECT * FROM qllt_loaihoso");
			$row = $r->fetchAll();
			}else{
			$r = $db->query("SELECT * FROM qllt_loaihoso where ID_LOAIHOSO=$this->id_lhs");
			$row = $r->fetchAll();
			//var_dump($row);
			}
		foreach($row as $lhs){
		?>
		<tr>
			<td nowrap  width=20%>
			<?=$lhs['TENLOAI']?>
			</td>
			<td nowrap  width=20%>	
			<a href="#" onclick="Detail(<?=$this->fromdatex?>,<?=$this->todatex?>,3,<?=$lhs['ID_LOAIHOSO']?>)">				
			 <?php			       
				echo  baocaochomuonhosoreportModel::CountgetReportData($this->fromdate,$this->todate,3,$lhs['ID_LOAIHOSO']);				
			 ?>			 
			 </a>
			</td>			 
			<td nowrap  width=20%>	
			<a href="#" onclick="Detail(<?=$this->fromdatex?>,<?=$this->todatex?>,1,<?=$lhs['ID_LOAIHOSO']?>)">	
			 <?php
				echo baocaochomuonhosoreportModel::CountgetReportData($this->fromdate,$this->todate,1,$lhs['ID_LOAIHOSO']);			
			 ?>
			  </a>
			</td>			 
			<td nowrap  width=20%>
			<a href="#" onclick="Detail(<?=$this->fromdatex?>,<?=$this->todatex?>,4,<?=$lhs['ID_LOAIHOSO']?>)">	
			<?php
				echo baocaochomuonhosoreportModel::CountgetReportData($this->fromdate,$this->todate,4,$lhs['ID_LOAIHOSO']);			
			 ?>
			  </a>
			</td>
			<td nowrap  width=20%>
			<a href="#" onclick="Detail(<?=$this->fromdatex?>,<?=$this->todatex?>,2,<?=$lhs['ID_LOAIHOSO']?>)">	
			<?php
				echo baocaochomuonhosoreportModel::CountgetReportData($this->fromdatex,$this->todatex,2,$lhs['ID_LOAIHOSO']);			
			 ?>
			  </a>
			</td>
			<?php }?>
		</tr>
	</tbody>
</table>
<?php }?>
<script>
function setvalueDateD(value_from,value_to){
	document.frm.fromdate.value = value_from+"/<?=QLVBDHCommon::getYear()?>";
	document.frm.todate.value = value_to+"/<?=QLVBDHCommon::getYear()?>";
}
function thongke(){
var err = true;
if(document.frm.fromdate.value !=''){
err=err & validateInput('date',document.frm.fromdate,'Ngày bắt đầu nhập sai định dạng ngày/');
}
if(document.frm.todate.value !=''){
err=err & validateInput('date',document.frm.todate,'Ngày kết thúc nhập sai định dạng ngày'); 
}
if(err==true){
	document.frm.action = "/report/baocaochomuonhoso/indextke/in/1";
	document.frm.target = "_self";
	document.frm.submit();
	}
}
function In(){
var err = true;
if(document.frm.fromdate.value !=''){
err=err & validateInput('date',document.frm.fromdate,'Ngày bắt đầu nhập sai định dạng ngày/');
}
if(document.frm.todate.value !=''){
err=err & validateInput('date',document.frm.todate,'Ngày kết thúc nhập sai định dạng ngày'); 
}
if(err==true){
	document.frm.action = "/report/baocaochomuonhoso/xuatwebtke";
	document.frm.target = "_blank";
	document.frm.submit();
	}
}
function Excel(){
var err = true;
if(document.frm.fromdate.value !=''){
err=err & validateInput('date',document.frm.fromdate,'Ngày bắt đầu nhập sai định dạng ngày/');
}
if(document.frm.todate.value !=''){
err=err & validateInput('date',document.frm.todate,'Ngày kết thúc nhập sai định dạng ngày'); 
}
if(err==true){
	document.frm.action = "/report/baocaochomuonhoso/xuatexceltke";
	document.frm.target = "_self";
	document.frm.submit();
	}
}

function Detail(fromdate,todate,sel_tt,sel_lhs){
	document.frm.action = "/report/baocaochomuonhoso/reportview?eval(fromdate=fromdate)&eval(todate=todate)&is_in=1&sel_tt="+sel_tt+"&sel_lhs="+sel_lhs;
	document.frm.target = "_blank";
	document.frm.submit();
}

</script>