<?php
require_once 'qtht/models/CoQuanModel.php';
?>

<form name="frm" action="<?echo $this->baseUrl()?>/qtht/DanhMucCoQuan" method="post">
<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo htmlspecialchars($this->search);  ?>" class="text_area" onchange="document.frm.submit();" />
				<button onclick="document.frm.submit();">Tìm</button>
				<button onclick="document.getElementById('search').value='';document.frm.submit();">Làm lại</button>
			</td>
		</tr>
</table>


<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>#</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th nowrap>Ký hiệu</th>
			<th nowrap>Tên cơ quan</th>
		    <th nowrap>Email</th>
			<th nowrap>Mã cơ quan</th>
			<th nowrap>Phạm vi</th>
			<th nowrap>Cấp cơ quan</th>
		</tr>
	</thead>

	<tbody>
<?php
$stt=0;
$i=0;

foreach ($this->data as $row ){
	$stt++;    
?>

		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row['ID_CQ'] ?>'>
			</td>
			 <td >
			     <?php echo htmlspecialchars($row['KYHIEU']) ?>
			</td>
			<td width=100%>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_CQ'] ?>);">
				<?php echo str_repeat("----",$row["LEVEL"]-1).htmlspecialchars($row['NAME']) ?>
				</a>
			</td>
			<td><?php echo htmlspecialchars($row['EMAIL']); ?>  </td>
			<td><?php echo htmlspecialchars($row['CODE']); ?>  </td>
			<td nowrap>
<?php
	$noibo =  $row["ISSYSTEMCQ"];
	if($noibo == 1){
		echo "Nội bộ";
	}
	else {
		echo "Bên ngoài";
	}
?>
			</td>
			<td nowrap>
			<?php echo CoQuanModel::returnCapCoQuan($row["CAPCQ"]);?>
			</td>
		</tr>
<?php
	$i = (-1+$i)*-1;    
}
?>
	</tbody>

	<tfoot>
	<tr>
			<td colspan="8">
					<div class="pagination">
						<div class="limit">

						</div>
						<div class="limit"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>
</table>
</form>


<script>

function DeleteButtonClick(){
	var ln = 0;
	var arr = document.getElementsByName('DEL[]');
	for(var i = 0 ; i < arr.length ;i++ ){
		if(arr[i].checked == true){
			ln = 1;
		}
	}
	if(ln == 1){
		if(confirm("<?php echo "Bạn có muốn xóa không"; ?>")){
			//document.URL=
			document.frm.action="/qtht/DanhMucCoQuan/delete";
			document.frm.method="post";
			document.frm.submit();
		}
	}else{
		alert("Bạn phải một dòng chọn để xóa");
	}
}
function AddNewButtonClick(){
	//document.URL = "/qtht/DanhMucCoQuan/input";
	document.frm.action="/qtht/DanhMucCoQuan/input";
	document.frm.method="get";
	document.frm.submit();

}
function ItemClick(id){
	//document.URL = "/qtht/DanhMucCoQuan/input/idCoQuan/"+id;
	document.frm.action="/qtht/DanhMucCoQuan/input/idCoQuan/"+id;;
	document.frm.method="get";
	document.frm.submit();
}
</script>
