<table class=adminlist>
	<thead>
		<?php
			if($this->isreadonly==0){
		?>
		<tr>
			<th colspan="3">
			<?php
				if($this->havegopy){
			?>
			<a href="#" onclick="
				document.getElementById('phoihop<?=$this->idhscv?>').style.display='';
				document.getElementById('phoihop<?=$this->idhscv?>').src = '/hscv/phoihop/addgopy/idhscv/<?=$this->idhscv?>';
				return false;
			">Góp ý&nbsp;&nbsp;&nbsp;</a>
			<?php
				}
			?>
			<a href="#" onclick="
				document.getElementById('phoihop<?=$this->idhscv?>').style.display='';
				document.getElementById('phoihop<?=$this->idhscv?>').src = '/hscv/phoihop/viewuser/idhscv/<?=$this->idhscv?>';
				return false;
			">Người phối hợp</a></th>
		</tr>
		<?php
			}
		?>
		<tr>
			<th>#</th>
			<th width="100%">Nội dung góp ý</th>
			<th nowrap>Người góp ý</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3">
				<iframe style="overflow-x:visible;display:none" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no name="phoihop<?=$this->idhscv?>" id="phoihop<?=$this->idhscv?>" src="" width="100%"></iframe>
			</th>
		</tr>
	</tfoot>
	<tbody>
<?php
	$i=0;
	$stt=1;
	if(count($this->data)>0){
		foreach($this->data as $row){
?>
		<tr class="row<?=$i?>">
			<td nowrap><?=$stt?></td>
			<td width=100%><?=nl2br(htmlspecialchars($row['NOIDUNG']))?></td>
			<td nowrap><?=$row['EMPNAME']?></td>
		</tr>
<?php
			$i = (-1+$i)*-1;
			$stt++;
		}
	}else{
?>
		<tr class="row<?=$i?>">
			<td colspan="3">
				Chưa có góp ý nào
			</td>
		</tr>
<?php
	}
?>
	</tbody>
</table>