<?php
	$do_gzip_compress = false;
	
	$phpver = phpversion();
	
	//if ( $phpver >= '4.0.4pl1' )
	//{
	//	if ( extension_loaded('zlib') )
	//	{
	//		ob_start('ob_gzhandler');
	//	}
	//}
	//else 
	if ($phpver > '4.0')
	{
		if (strstr($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip') )
		{
			if (extension_loaded('zlib') )
			{
				$do_gzip_compress = true;
				ob_start();
				ob_implicit_flush(0);
				header('Content-Encoding: gzip');
			}
		}
	}
?>