<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<?php
	global $auth;
	global $url;
	$config = Zend_Registry::get('config');
	
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="vi-vn" lang="vi-vn" dir="ltr" id="minwidth" >

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo  $config->sys_info->name_system?> - <?=$this->title?></title>
	<?php
	    global $auth;
	    $user = $auth->getIdentity();
	    // Check if dojo library is needed
	    if ($this->dojo()->isEnabled()):
	        // Include dojo library
	        $this->dojo()->setLocalPath('/js/dojo/dojo.js')
	            // Use dojo theme tundra
	            ->addStyleSheetModule('dijit.themes.tundra');
	        // Echo out the dojo <script> tags
	        echo $this->dojo();
	    endif; 
    ?>
	<script type="text/javascript" src="/js/LoadDynamicJs.js"></script> <!-- cai nay cua trung, khong ai duoc dung vao --> 
	<script type="text/javascript" src="/js/common.js"></script>
    <script src="/js/validate.js" type="text/javascript"></script>
<?php if($auth->hasIdentity()){ ?>
	<script type="text/javascript" src="/js/mootools.js"></script>
	<script src="/js/menu.js" type="text/javascript"></script>
	<script src="/js/index.js" type="text/javascript"></script>
	<script type="text/javascript" src="/js/joomla.javascript.js"></script>
	<script type="text/javascript" src="/js/calendar.js"></script>
	<script type="text/javascript" src="/js/ajax/AjaxEngine.js"></script>
	<script type="text/javascript">
		window.addEvent('domready', function(){ new Accordion($$('.panel h3.jpane-toggler'), $$('.panel div.jpane-slider'), {onActive: function(toggler, i) { toggler.addClass('jpane-toggler-down'); toggler.removeClass('jpane-toggler'); },onBackground: function(toggler, i) { toggler.addClass('jpane-toggler'); toggler.removeClass('jpane-toggler-down'); },duration: 300,opacity: false,alwaysHide: true}); });
    </script>
    <link rel="stylesheet" type="text/css" href="/styles/menu.css" />
<?php
}
?>
	<link rel="stylesheet" href="/styles/system.css" type="text/css" />
	<link rel="stylesheet" type="text/css" href="/styles/rounded.css" />
	<link rel="stylesheet" type="text/css" href="/styles/general.css" />
	<link rel="stylesheet" type="text/css" href="/styles/template.css" />
<?php if(!$auth->hasIdentity()){ ?>
	<link rel="stylesheet" type="text/css" href="/styles/login.css" />
<?php
	}
?>
<link rel="stylesheet" href="/styles/traodoi_lightbox.css" type="text/css" media="screen" />

</head>
<body id="minwidth-body" 
<?php if((int)$this->is_mailmain == 1){ ?>
onLoad="
dofinishLoad();
;
"<?php }?>
>
	<div style="position:absolute;display:none;" id="atAutoComplete"></div>
	<div id="border-top" class="h_green">
		<div>
			<div>
				<div style="float:left;">
				<span class="title"><?php echo $config->sys_info->name_system?></span>
				<span class="version"><?php echo $config->sys_info->version ?></span><br>
				<span class="version"><?php echo $config->sys_info->company ?></span><br>
			
			</div>
			<div style="float:right;background:none;margin:0;padding:0;">
			<?php if($auth->hasIdentity()){ ?>
			<br>
			<span><a href="/auth/user/changepassword"><font color="#ffffff">
			Đổi mật khẩu
			</font></a></span>
			
			<?php } ?>
			</div>
			</div>
		</div>
	</div>
	<div class=clr></div>
<?php if($auth->hasIdentity()){ ?>
	<div id="header-box">
		<div id="module-status">
			<div style="float:left;clear:left;margin-top:3px;">
				
			</div>
			
			<div class="signUpNowLink"><a href="/auth/logout"><span>Thoát</span></a></div>
		</div>
		<div class="mainNavigator">
			<ul id="menu" >
				<?php
					$menu = new Zend_Session_Namespace('menu');
					echo $menu->menu;
				?>
			</ul>
		</div>
		
			
		
		<div class="clr"></div>
		
	</div><a name=atitle></a>
	<div id="content-box">
		<div class="border">
			<div class="padding">
				<div id="toolbar-box">
		   			<div class="t">
						<div class="t">
							<div class="t"></div>
						</div>
					</div>
					<div class="m">
						<table width="100%">
							<tr>
								<td><div class="header"><?=$this->title?>: <small><small>[ <?=$this->subtitle?> ]</small></small></div></td>
								<td align="right"><?php echo(QLVBDHButton::DrawButton()) ?></td>
							</tr>
						</table>
						<div class="clr"></div>
					</div>
					<div class="b">
						<div class="b">
							<div class="b"></div>
						</div>
					</div>
	  			</div>
	   			<div class="clr"></div>
				<div id="element-box">
					<div class="t">
				 		<div class="t">
							<div class="t"></div>
			 			</div>
					</div>
					<div class="m">
		                <?php echo $this->layout()->content ?>
						<div class="clr"></div>
					</div>
					<div class="b">
						<div class="b">
							<div class="b"></div>
						</div>
					</div>
	  			</div>
			<div class="clr"></div>
		</div>
		<div class="clr"></div>
	</div>
</div>
<?php
	}else{
?>
	<div id="content-box">
		<div class="padding" style="padding-top:20px;">
			<div id="element-box" class="login" style="margin-bottom:10px">
				<div class="t">
					<div class="t">
						<div class="t"></div>
					</div>
				</div>
				<div class="m">
					<?php echo $this->layout()->content ?>
				</div>
				<div class="b">
					<div class="b">
						<div class="b"></div>
					</div>
				</div>
			</div>
			<div class="clr"></div>
		</div>
	</div>
<?php
	}
?>
	<div id="border-bottom"><div><div></div></div></div>
	<div id="footer">
    	<p class="copyright">Copyright © 2008 Unitech</p>
	</div>
</body>
</html>