<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="baocaovanbandi-6_files/filelist.xml">
<link rel=Edit-Time-Data href="baocaovanbandi-6_files/editdata.mso">
<link rel=OLE-Object-Data href="baocaovanbandi-6_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>nguyennd</o:Author>
  <o:LastAuthor>User</o:LastAuthor>
  <o:LastPrinted>2010-11-02T04:38:38Z</o:LastPrinted>
  <o:Created>2009-08-25T14:43:47Z</o:Created>
  <o:LastSaved>2010-11-02T04:38:55Z</o:LastSaved>
  <o:Company>Hewlett-Packard</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.2in .2in .2in .2in;
	mso-header-margin:.2in;
	mso-footer-margin:.2in;
	mso-page-orientation:landscape;
	mso-horizontal-page-align:center;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl25
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl26
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl27
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl28
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl29
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl30
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl31
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl32
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl33
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\[$-1010000\]d\/m\/yyyy\;\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl34
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl35
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl36
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl37
	{mso-style-parent:style0;
	font-size:13.0pt;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl38
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:right;}
.xl39
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl40
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:DefaultRowHeight>315</x:DefaultRowHeight>
     <x:FitToPage/>
     <x:FitToPage/>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>60</x:PageBreakZoom>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>7</x:ActiveRow>
       <x:ActiveCol>3</x:ActiveCol>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
    <x:PageBreaks>
     <x:ColBreaks>
      <x:ColBreak>
       <x:Column>8</x:Column>
      </x:ColBreak>
     </x:ColBreaks>
    </x:PageBreaks>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>12240</x:WindowHeight>
  <x:WindowWidth>15315</x:WindowWidth>
  <x:WindowTopX>885</x:WindowTopX>
  <x:WindowTopY>-135</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]-->
</head>

<body link=blue vlink=purple class=xl24>

<table x:str border=0 cellpadding=0 cellspacing=0 width=1052 style='border-collapse:
 collapse;table-layout:fixed;width:789pt'>
 <col class=xl24 width=40 style='mso-width-source:userset;mso-width-alt:1462;
 width:30pt'>
 <col class=xl24 width=87 style='mso-width-source:userset;mso-width-alt:3181;
 width:65pt'>
 <col class=xl24 width=77 style='mso-width-source:userset;mso-width-alt:2816;
 width:58pt'>
 <col class=xl24 width=255 style='mso-width-source:userset;mso-width-alt:9325;
 width:191pt'>
 <col class=xl24 width=52 style='mso-width-source:userset;mso-width-alt:1901;
 width:39pt'>
 <col class=xl24 width=148 style='mso-width-source:userset;mso-width-alt:5412;
 width:111pt'>
 <col class=xl24 width=151 style='mso-width-source:userset;mso-width-alt:5522;
 width:113pt'>
 <col class=xl24 width=142 style='mso-width-source:userset;mso-width-alt:5193;
 width:107pt'>

 <col class=xl24 width=100 style='mso-width-source:userset;mso-width-alt:3657;
 width:75pt'>
 <col class=xl24 width=149 style='mso-width-source:userset;mso-width-alt:5449;
 width:112pt'>
 <col class=xl24 width=139 style='mso-width-source:userset;mso-width-alt:5083;
 width:104pt'>
 <col class=xl24 width=125 style='mso-width-source:userset;mso-width-alt:4571;
 width:94pt'>
 <col class=xl24 width=131 style='mso-width-source:userset;mso-width-alt:4790;
 width:98pt'>
 <tr class=xl25 height=23 style='mso-height-source:userset;height:17.25pt'>
  <td colspan=4 height=23 class=xl35 width=459 style='height:17.25pt;
  width:344pt'><?=mb_strtoupper($this->config->sys_info->company,"utf-8") ?></td>
  <td colspan=4 class=xl35 width=493 style='width:370pt'>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>

  <td class=xl26 width=100 style='width:75pt'></td>
 </tr>
 <tr class=xl25 height=23 style='mso-height-source:userset;height:17.25pt'>
  <td colspan=4 height=23 class=xl36 style='height:17.25pt'>VĂN PHÒNG <?=mb_strtoupper($this->config->sys_info->company,"utf-8") ?></td>
  <td colspan=4 class=xl37>Ðộc lập - Tự do - Hạnh phúc</td>
  <td class=xl27></td>
 </tr>
 <tr height=21 style='height:15.75pt'>

  <td height=21 colspan=2 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
  <td colspan=2 class=xl28 style='mso-ignore:colspan'></td>
  <td colspan=4 class=xl38><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
  <td class=xl28></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=9 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>

 <tr height=21 style='height:15.75pt'>
  <td colspan=8 height=21 class=xl39 style='height:15.75pt'>BÁO CÁO VĂN BẢN ĐI</td>
  <td class=xl24></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=8 height=21 class=xl40 style='height:15.75pt'><?php echo $this->thu;?> năm <?=date("Y")?></td>
  <td class=xl24></td>
 </tr>

 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=9 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr class=xl29 height=28 style='mso-height-source:userset;height:21.0pt'>
  <td height=28 class=xl30 width=40 style='height:21.0pt;width:30pt'>Số đi</td>
  <td class=xl31 width=87 style='width:65pt'>Ngày tháng</td>
  <td class=xl31 width=77 style='width:58pt'>Số ký hiệu</td>

  <td class=xl31 width=255 style='width:191pt'>Trích yếu nội dung</td>
  <td class=xl31 width=52 style='width:39pt'>Số bản</td>
  <td class=xl31 width=148 style='width:111pt'>Nơi nhận</td>
  <td class=xl31 width=151 style='width:113pt'>Lưu hồ sơ (người ký)</td>
  <td class=xl31 width=142 style='width:107pt'>Ghi chú</td>
  <td class=xl29></td>

 </tr>
 <?php require_once 'qtht/models/LoaiVanBanModel.php';
require_once 'qtht/models/CoquanModel.php'; 
require_once 'qtht/models/DepartmentsModel.php';
require_once 'qtht/models/UsersModel.php';
?>
<?php  $stt=1; 
$num = count($this->data);

foreach($this->data as $row){ 
 ?>
 <tr height=42 style='height:31.5pt'>
  <td height=42 class=xl32 width=40 style='height:31.5pt;width:30pt'><?php echo $row["SODI"]?></td>
  <td class=xl33 width=87 style='width:65pt'><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYBANHANH"]) ?></td>
  <td class=xl34 width=77 style='width:58pt'><?php echo $row["SOKYHIEU"]?></td>
  <td class=xl34 width=255 style='width:191pt'><?php echo $row["TRICHYEU"] ?></td>
  <td class=xl34 width=52 style='width:39pt'><?php echo $row["SOBAN"] ?></td>

  <td class=xl34 width=148 style='width:111pt'><?php echo $row["NOINHAN"] ?></td>
  <td class=xl34 width=151 style='width:113pt'><?php echo UsersModel::getEmloyeeNameByIdUser($row["NGUOIKY"]) ?><br>
    </td>
  <td class=xl34 width=142 style='width:107pt'></td>
  <td class=xl24></td>
 </tr>
  <?php $stt++ ; } ?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>

  <td width=40 style='width:30pt'></td>
  <td width=87 style='width:65pt'></td>
  <td width=77 style='width:58pt'></td>
  <td width=255 style='width:191pt'></td>
  <td width=52 style='width:39pt'></td>
  <td width=148 style='width:111pt'></td>
  <td width=151 style='width:113pt'></td>
  <td width=142 style='width:107pt'></td>
  <td width=100 style='width:75pt'></td>

 </tr>
 <![endif]>
</table>

</body>

</html>
