<table class=adminlist>
	<thead>
		<tr>
			<th nowrap="nowrap">#</th>
			<th width="100%">Tên văn bản</th>
			<th nowrap="nowrap">File văn bản</th>
			<th nowrap="nowrap"></th>
		</tr>
	</thead>
	<tfoot>
		<tr id="#trframe<?=$this->idhoso?>"><td colspan=4 style="background-color:#F3F3F3;">
		<?php 
		if ((int)$row["ID_VANBAN"] != 0)
		{
		?>
				<a href="#trframe<?=$this->idhoso?>" onClick="document.getElementById('iframesend<?=$row['ID_HOSO']?>').style.display='';
								document.getElementById('iframesend<?=$row['ID_HOSO']?>').setAttribute('src','/qllt/vanban/input/IdFrame/iframesend<?=$row['ID_HOSO']?>/idhoso/<?=$this->idhoso?>/idvanban/0');" />[Thêm mới]
				</a>
		<?php }else { ?>
				<a href="#trframe<?=$this->idhoso?>" onClick="document.getElementById('iframesend<?=$this->idhoso?>').style.display='';
								document.getElementById('iframesend<?=$this->idhoso?>').setAttribute('src','/qllt/vanban/input/IdFrame/iframesend<?=$this->idhoso?>/idhoso/<?=$this->idhoso?>/idvanban/0');" />[Thêm mới]
				</a>
		<?php }?>
		</td></tr>
	</tfoot>
	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row )
	{
	$stt++;	
?>
		<tr class=row<?=$i?>>
			<td nowrap="nowrap" style="height:15px"><?=$stt?></td>
			<td width="100%" style="height:15px">				
				<a href="#trframe<?=$row['ID_HOSO']?>" onclick="
								document.getElementById('iframesend<?=$row['ID_HOSO']?>').style.display='';
								document.getElementById('iframesend<?=$row['ID_HOSO']?>').setAttribute('src','/qllt/vanban/input/IdFrame/iframesend<?=$row['ID_HOSO']?>/idhoso/<?=$row['ID_HOSO']?>/idvanban/<?=$row["ID_VANBAN"]?>');
				"><?=$row["KYHIEUVANBAN"]?> - <?=$row["TENVANBAN"]?></a>
				<input type="hidden" name="idvanban" value="<?=$row["ID_VANBAN"]?>" />
			</td>
			<td nowrap="nowrap" style="height:15px">
			<?php 
				if ($row["FILENAME"] != "")
				{ ?>
				<a href="/qllt/vanban/download/id/<?=$row["ID_VANBAN"]?>"><?=$row["KYHIEUVANBAN"]?></a>
				<?php }else {}?>
			</td>
			<td nowrap="nowrap" style="height:15px" colspan=2>
				<a href="#" onClick="javascript:
										if(confirm('Bạn có muốn xóa các văn bản được chọn không?')){
											
											execfunction('qllt','vanban','delete','idvanban/<?=$row['ID_VANBAN']?>/idhoso/<?=$row['ID_HOSO'] ?>');
											
										};
				" >[Xóa]</a>
			</td>
		</tr>		
<?php 
} 
?>		
		
	</tbody>
</table>

	<iframe style="overflow-x:visible;display:none; width:100%" height=0 width=100% id=iframesend<?=$this->idhoso?> allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no src=""></iframe>
	
<script>
function DeleteButtonClick(){
//	var mess = true;
//	mess = validateInput("selone_check","DELVANBAN[]","abc");
//	if(mess){
//		if(confirm("Bạn có muốn xóa các văn bản được chọn không?")){
//			document.frmVanban.action = "/qllt/vanban/delete";
//			var caigido = getDataFromFrm('frmVanban');
//			execfunction('qllt','vanban','delete','?'+caigido);
//		}
//	}else{
//		alert("Phải chọn ít nhất một tài liệu để xóa.");
//	}
}
function AddNewButtonClick(){
	window.location = "/qllt/vanban/input";
	//document.frmVanban.submit();
}
function ItemClick(id){
	document.frmVanban.action = "/qllt/vanban/input/idvanban/"+id;
	document.frmVanban.submit();
}

function SwapIframe(id,url){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
					document.getElementById("groupcontent"+id).style.display="none";
					document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
					break;
				}
			}
		}
		if(document.getElementById('groupcontent'+id).style.display == ''){
			document.getElementById('groupcontent'+id).style.display = 'none';
		}else{
			document.getElementById('groupcontent'+id).innerHTML = '<iframe style="overflow-x:visible" height=0 id=iframebutphe'+id+' allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no src="'+url+'"></iframe>';
			document.getElementById('groupcontent'+id).style.display = '';
		}
	}
</script>