<form name=frmListUsers method="post" action="/qtht/users">
	<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo $this->search ?>" class="text_area" onchange="document.frmListUsers.submit();" />
				<button onclick="document.frmListUsers.submit();">Tìm</button>
				<button onclick="document.getElementById('search').value='';document.frmListUsers.submit();">Làm lại</button>
			</td>
			<td align="right" nowrap="nowrap">	
			
			</td>
		</tr>
	</table>
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>#</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th width="100%">Tên</th>
			<th nowrap>Kích hoạt</th>
			
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="4">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frmListUsers.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="50">50</option>
								<option value="100">100</option>
								<script>
									document.frmListUsers.limit.value='<?php echo $this->limit ?>';
								</script>
							</select>
						</div>
						<div style="float:right;"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row ){
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row['ID_U'] ?>'>
			</td>
			<td width=100%>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_U'] ?>);">
				<?php echo htmlspecialchars($row['USERNAME']) ?>
				</a>
			</td>
			<td><a href="<?php echo $this->url(array('controller'=>'users', 
            'action'=>'save', 'id_u'=>$row['ID_U'],'active'=>$row['ACTIVE']));?>"><?php if($row['ACTIVE']=='1') echo 'Rồi';
			else echo 'Chưa';?></a></td>
			
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
<input type="hidden" name="comeFrom" value="listForm">
</form>
<script>
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","Chọn ít nhất một người dùng để xoá.");
	if(mess){
		if(confirm("<?php echo 'Bạn muốn xóa mục này!'; ?>")){
			document.frmListUsers.action = "/qtht/users/delete";
			document.frmListUsers.submit();
		}
	}else{
		alert("Chọn ít nhất một người dùng để xoá.");
	}
}
function AddNewButtonClick()
{
	document.frmListUsers.action = "/qtht/users/input";
	document.frmListUsers.submit();
}
function ItemClick(id)
{
	document.frmListUsers.action = "/qtht/users/input/id/"+id;
	document.frmListUsers.submit();
}
</script>


