<form name=frmListTinhThanh method="post" action="/qtht/tinhthanh">
	<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo $this->search ?>" class="text_area" onchange="document.frmListTinhThanh.submit();" />
				<button onclick="document.frmListTinhThanh.submit();">Tìm</button>
				<button onclick="document.getElementById('search').value='';document.frmListTinhThanh.submit();">Làm lại</button>
			</td>
			<td nowrap="nowrap">				
			</td>
		</tr>
	</table>
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>#</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th width="10%">Mã tỉnh thành</th>
			<th width="80%">Tên tỉnh thành</th>
			<th width="10%">Thuộc nội bộ</th>
			
			
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="5">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frmListTinhThanh.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="50">50</option>
								<option value="100">100</option>
							</select>
							<script>
								document.frmListTinhThanh.limit.value='<?php echo $this->limit ?>';
							</script>
						</div>
						<div style="float:right"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row ){
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row['ID_TINHTHANH'] ?>'>
			</td>
			<td align="center">
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_TINHTHANH'] ?>);">
				<?php echo $row['CODE'] ?>
				</a>
			</td>
			<td>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_TINHTHANH'] ?>);">
				<?php echo htmlspecialchars($row['TEN_TINHTHANH']) ?>
				</a>
			</td>
			<td>
				<?php if($row['ISLOCAL']=='1') echo 'Thuộc';
			else echo 'Không thuộc';?> 
				
			</td>
			
			
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
<input type="hidden" name="comeFrom" value="listForm">
</form>
<script>
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","Chọn ít nhất một người dùng để xoá.");
	if(mess){
		if(confirm("<?php echo 'Bạn muốn xóa mục này!'; ?>")){
			document.frmListTinhThanh.action = "/qtht/tinhthanh/delete";
			document.frmListTinhThanh.submit();
		}
	}else{
		alert("Chọn ít nhất một người dùng để xoá.");
	}
}
function AddNewButtonClick()
{
	document.frmListTinhThanh.action = "/qtht/tinhthanh/input";
	document.frmListTinhThanh.submit();
}
function ItemClick(id)
{
	document.frmListTinhThanh.action = "/qtht/tinhthanh/input/id/"+id;
	document.frmListTinhThanh.submit();
}
</script>



