<form action="" enctype="multipart/form-data" name="frmEditTinhthanh"  method="<?php echo $this->form->getAttrib('method');?>">
<fieldset>
	<div style="text-align:right;width:100%">
		Trường có dấu <font color="red">*</font> là bắt buộc nhập
	</div>
	<div class="required">
		<label id="lblTextIput">Mã tỉnh thành<font color="red">*</font></label>
		<?php echo $this->form->getElement('CODE');?>
    	<span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('CODE'));			
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="optional">
		<label for="ID_DEP_PARENT" id="lblTextIput">Tên tỉnh thành<font color="red">*</font></label>
		<?php echo $this->form->getElement('TEN_TINHTHANH');?>
        <span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('TEN_TINHTHANH'));			
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="optional">
		<label for="ACTIVE" id="lblTextIput">Nội bộ</label>
		<?php echo $this->form->getElement('ISLOCAL');?>
	</div>
	<div class="clr"></div>
	<input type=hidden name="id" value=<?php echo $this->id?> >
</fieldset>
</form>

<script>
	function SaveButtonClick()
	{
		document.frmEditTinhthanh.submit();
	}
	function BackButtonClick()
	{
		document.frmEditTinhthanh.action = "/qtht/tinhthanh/";
		document.frmEditTinhthanh.submit();
	}
</script>