<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<?php 
$year = QLVBDHCommon::getYear();
$ktxuly_ravbdi = 0;
$dangxuly_ravbdi = 0;
?>
<div id="div_thongke" style="padding-bottom:20px;padding-top:20px;padding-left:0px" ></div>

<form name="frm">
<table class="adminlist">
<thead>
<tr>
			<th colspan="7">
				<div>
					<div class="limit" style="float:left;">Hiển thị #
						<select name="limit1"  style="width:60px;" id="limit1" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit2.value = document.frm.limit1.value;
							document.frm.action = '/report/xulyvanbanden/reportview';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div class="limit" style="float:right;"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
	<tr>
<tr>
	<th>#</th>
	<th colspan=3><?php
	switch($this->type){
		case 1:
			echo "Xử lý văn bản đến";
			break;
		case 2:
			echo "Công việc soạn thảo";
			break;
		case 3:
			echo "Hồ sơ một cửa";
			break;
		default:
			echo "Không xác định";
	}
	?></th>
	<th colspan=3>Tình hình xử lý</th>
</tr>
<tr>
	<th></th>
	<th>Số ký hiệu</th>
	<th>Cơ quan ban hành</th>
	<th>Trích yếu</th>
	<th>Người đang xử lý</th>
	<th>Trạng thái</th>
	<th>Kết quả xử lý</th>
</tr>
</thead>
<tfoot>
	<tr>
			<th colspan="7">
				<div class="pagination">
					<div class="limit">Hiển thị #
						<select name="limit2" style="width:60px;" id="limit2" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit1.value = document.frm.limit2.value;
							document.frm.action = '/report/xulyvanbanden/reportview';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div style="float:right"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
</tfoot>
<tbody>
<?php 
$arr_thongke = $this->arr_thongke;
/*$arr_thongke = array();
$dem_ktxl_tre = 0;
$dem_ktxl = 0;
$dem_dangxl = 0;
$dem_dangxl_tre = 0;
$dem_ktxlluutheodoi = 0;
$dem_khongxuly = 0;*/

$stt=1;foreach($this->data as $item){

			/*if($item["IS_KHONGXULY"]){
				$dem_khongxuly++;
				$dem_ktxl++;
			}else
			if($item["IS_FINISH"]){
				$dem_ktxl++;
				if($item["IS_TRE_KT"])
					$dem_ktxl_tre++;
				
			}else{
				if($item["IS_THEODOI"]){
					$dem_ktxl++;
					$dem_ktxlluutheodoi++;
				}else{
					$dem_dangxl++;
					$dis_hour = QLVBDHCommon::getTreHan($item["DATESEND"],$item["HANXULY"]);
					if($dis_hour > 0){
						$dem_dangxl_tre++;
					}
				}
					
			}*/

			
		
			
?>
<tr>
	<td>
		<?=$stt?>
	</td>	
	<td>
	<?=$item["SOKYHIEU"]?> <br/>
	<i><?=QLVBDHCommon::MysqlDateToVnDate($item["NGAYBANHANH"])?></i>
	</td>
	<td>
		<?=$item["COQUANBANHANH_TEXT"]?>
	</td>
	
	<td>
	<?=$item["TRICHYEU"]?>
	</td>
	
	<td>
		<?=$item["NAME_U"]==""?"không có":$item["NAME_U"]."<br/>"."<!-- (<i>".$item["NAME_DEP"].")</i> -->"?>
	</td>
	<td>
		
		<?php 
		if($item["ID_HSCV"]=="")
		{
			if($item["IS_KHONGXULY"] == 1)
					echo "văn bản không xử lý";
		}
		else if($item["IS_THEODOI"]==1){
			echo "Đang lưu theo dõi";
		}else{
		if($item["IS_FINISH"]==1){
			echo "Đã kết thúc";
		}else{
		
		$dis_hour = QLVBDHCommon::getTreHan($item["DATESEND"],$item["HANXULY"]);
				if($dis_hour > 0){
					
					if($this->id_u == $item_luanchuyen["ID_U_RECEIVE"])
						echo '<font color="Red">đang xử lý (trễ '. (int)($dis_hour/8) .' ngày '.($dis_hour%8).' giờ)</font>';
					else 
						echo 'đang xử lý (trễ '. (int)($dis_hour/8) .' ngày '.($dis_hour%8).' giờ)';
				}
				else{ 
					$con = 0- $dis_hour;
					echo 'đang xử lý (còn '. (int)($con/8) .' ngày '.($con%8).' giờ)';
				}
		}}
		?>
	</td>
	<td><?
		if($item["ID_HSCV"] != "")	{
			$list_vbdi = Ad_XulyvanbandenModel::getListVanbandiByIdHSCV($item["ID_HSCV"]);
			if(count($list_vbdi) > 0){
				//if($item["IS_FINISH"] == 1)
					//$ktxuly_ravbdi++;
				//else
					//$dangxuly_ravbdi++;
				foreach($list_vbdi as $vbdi){
					echo  $vbdi["SOKYHIEU"]."<br/>";
				}
			}
			
			if($item["IS_THEODOI"]==1){
				echo $item["KQ_DEXUAT"];
			}
			
		}

	?></td>
	
</tr>
<?php $stt++;} 
/*$arr_thongke["dem_ktxl"] = $dem_ktxl;
$arr_thongke["dem_ktxl_tre"] = $dem_ktxl_tre;
$arr_thongke["dem_dangxl"] = $dem_dangxl;
$arr_thongke["dem_dangxl_tre"] = $dem_dangxl_tre;
$arr_thongke["dem_ktxlluutheodoi"] = $dem_ktxlluutheodoi;
$arr_thongke["dem_khongxuly"] = $dem_khongxuly;*/
?>
</tbody>

</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
<input type="hidden" name="sel_lcv" value="<?php echo $this->type; ?>">
<input type="hidden" name="todate" value="<?php echo $this->todate; ?>">
<input type="hidden" name="fromdate" value="<?php echo $this->fromdate; ?>">
<input type="hidden" name="type_date" value="<?php echo $this->type_date; ?>">

<?php foreach ($this->sel_lvb as $id_pb){?>
<input type="hidden" name='sel_lvb[]' value="<?=$id_pb?>">
<?php }?>
<input type=hidden name="op_lvb" value="<?=$this->op_lvb?>">

<?php foreach ($this->sel_cqbh as $id_cq){?>
<input type="hidden" name='sel_cqbh[]' value="<?=$id_cq?>">
<?php }?>
<input type=hidden name="op_lvb" value="<?=$this->op_cqbh?>">


<input type="hidden" name='sel_trangthai' value="<?=$this->sel_trangthai?>">

<input type=hidden name="op_trangthai" value="<?=$this->op_trangthai?>">


</form>
</body>
<p id=lasttext></p>
</html>


<script>
var div_thongke = document.getElementById("div_thongke");
var str_thongke ="<font color=blue size=3 ><b>";
str_thongke += "Đã xử lý:&nbsp <?=$arr_thongke["dem_ktxl"]?> <?=$arr_thongke["dem_ktxl_tre"]>0?"(<font color=red> trễ: ".$this->arr_thongke["dem_ktxl_tre"].")</font>":""  ?> " ;
str_thongke+="( ra VB đi:&nbsp <?=$arr_thongke["ktxuly_ravbdi"]?>";
str_thongke+=", không ra VB đi:&nbsp <?=$arr_thongke["dem_ktxlluutheodoi"]?>";
str_thongke+=", không chuyển xử lý:&nbsp <?=$arr_thongke["dem_khongxuly"]?> )";

str_thongke += "; Đang xử lý:&nbsp;<?=$arr_thongke["dem_dangxl"]?>&nbsp;<?=$arr_thongke["dem_dangxl_tre"]>0?"(<font color=red> trễ : ".$arr_thongke["dem_dangxl_tre"].")</font>":""  ?> " ;

str_thongke +="</b></font>";
div_thongke.innerHTML = str_thongke;


var iframeElement = window.parent.document.getElementById('reportview');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 

</script>