<?php
if($this->code=="mini"){
}else{
?>
<h1>Đăng nhập</h1>
<div id="section-box">
	<div class="t">
		<div class="t">
			<div class="t"></div>
		</div>
	</div>
	<div class="m">
		<form action="/" method="post" name="login" id="form-login" style="clear: both;">
			<p id="form-login-username">
				<label for="modlgn_username">Tên đăng nhập</label>
				<input name="username" id="modlgn_username" type="text" class="inputbox" size="15" />
			</p>
			<p id="form-login-password">
				<label for="modlgn_passwd">Mật mã</label>
				<input name="password" id="modlgn_passwd" type="password" class="inputbox" size="15" />
			</p>
		
			<div class="button_holder">
				<div class="button1">
					<div class="next">
						<a onclick="login.submit();">Đăng nhập</a>
					</div>
				</div>
			</div>
			<div class="clr"></div>
			<input type="submit" style="border: 0; padding: 0; margin: 0; width: 0px; height: 0px;" value="Đăng nhập" />
			<input type="hidden" name="option" value="com_login" />
			<input type="hidden" name="task" value="login" />
			</form>
			<div class="clr"></div>
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<div id="lock"></div>
	<div class="clr"></div>
<?php
}
?>