<?php 
//xu ly so di cho truong hop cap nhat\
require_once 'qtht/models/sovanbanModel.php';
require_once 'qtht/models/Vb_nguoikyModel.php';
require_once 'qtht/models/UsersModel.php';
require_once 'qtht/models/CoquanModel.php';
require_once 'hscv/models/gen_tempModel.php';
/* Xu ly du lieu cho so di*/
$arr_col = Common_Sovanban::getColumNameGroup(2);
$len_arr = count($arr_col);
if($this->id > 0)
{
	//var_dump($this->data);
	$old_svb =  $this->data["ID_SVB"];
	$old_lvb = $this->data["ID_LVB"];
	$old_cq = $this->data["ID_CQ"];
	$old_sodi = $this->data["SODI"];
	$old_sodi_in = $this->data["SODI_IN"];
	$aff_type  = 0;
	$col_name = "";
	foreach ($arr_col as $itcol){
	switch ($itcol)
	{
		case 'ID_SVB':
			$aff_type = $old_svb;
			$col_name='ID_SVB';
			break;
		case 'ID_LVB':
			$aff_type =$old_lvb;
			$col_name='ID_LVB';
			break;
		default:
			break; 
	}
}
}

/* Ket thuc xu ly du lieu cho so di*/

/* File dinh kem */
	$url = "";
	$is_new = 0;
	$type = 0;
	$id_objf = $this->id;	
	if((int)$this->id==0){
		$is_new = 1;
		$type = -1;
		if($this->id_pb_duthao){
			$gen_temp = new gen_tempModel();
			$new_object = $gen_temp->getIdTemp();
			filedinhkemModel::copyFile(QLVBDHCommon::getYear(),$this->id_pb_duthao,$new_object,2,-1);
			$id_objf = $new_object;
			$is_new = 0;
			$type = -1;
		}
	}else{
		$is_new = 0;
		$type = 5;
	}
	
	$url ="'/hscv/file?iddiv=idFileDinhKem&idObject=".$id_objf."&is_new=".$is_new."&year=".$this->year."&type=".$type."&pdf=1'" ;
/* Ket thuc file dinh kem */

?>
<script type="text/javascript" src="/js/calendar.js"></script>
<script type="text/javascript" src="/js/validate.js"></script>
<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<script type="text/javascript" src="/js/autocomplete.js"></script>
<script type="text/javascript" src="/js/json/json_parse.js"></script>
<form name=frm method="post" action="/vbdi/banhanh/save">
<table width="100%"  onclick="if(at_container){ if(at_container.style.display!='none')at_Hide(false);}">
	
	<?php 
		$cqnhan = vbdenModel::GetDataCQN((int)$this->data->COQUANNHAN);
	?>
	<script>
		var arr_CQs = new Array();
		<?php foreach($cqnhan as $cq){?>
			arr_CQs["<?=$cq["ID_CQ"]?>"] = "<?=$cq["NAME"]?>";
		<?php }?>
	</script>
	<?php if( count($cqnhan) > 1){?>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Cơ quan ban hành</font>
			<font color="Red" size="3">*</font>
		</td>
		
		<td nowrap="nowrap" valign="top">
			<!-- Co quan ban hanh -->
			<select name="ID_CQ" onchange="changeCQNHAN();updateSKH();" id="ID_CQ" >
				<?php foreach($cqnhan as $cq ){?>
					<option value="<?=$cq["ID_CQ"]?>"><?=$cq["NAME"]?></option>
				<?php } ?>
			</select>
		<input type=hidden name="ID_CQ_TEXT" id="ID_CQ_TEXT" ?>	
			<?php
				/*$data_cq  = CoQuanModel::getData(2);
				$id_cq = 0;
				if($this->id == 0)
					$id_cq = $data_cq[0]["ID_CQ"];
				else 
					$id_cq = $this->data["ID_CQ"];	
				echo QLVBDHCommon::AutoComplete(
				$data_cq,
				"ID_CQ",
				"NAME",
				"ID_CQ",
				"ID_CQ_TEXT",
				true,
				"width:200px",
				"changeCQNHAN();",
				$id_cq,
				'');*/
			?> 

			<div class="clr"></div>
			<span class="box_erro_area" id="ERRID_CQ" ></span>
		</td>
	</tr>
	<?php } else {?>
	<input type=hidden name="ID_CQ" id="ID_CQ" value=<?=(int)$cqnhan[0]["ID_CQ"]?>>
	<input type=hidden name="ID_CQ_TEXT" id="ID_CQ_TEXT" value=<?=(int)$cqnhan[0]["NAME"]?> ?>	
	<span class="box_erro_area" id="ERRID_CQ" ></span>
	<?php }?>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Sổ văn bản</font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<!-- Sổ văn bản -->
			<?php
				$year = QLVBDHCommon::getYear();
				$onok = "";
				foreach($arr_col as $col)
					if($col == 'ID_SVB')
						$onok = "getSodi(document.frm.ID_SVB);";
				echo QLVBDHCommon::AutoComplete(
				SoVanBanModel::getDataByCQ($year,rtrim($this->user->ID_CQ,","),1),
				//SoVanBanModel::getDataByDep($year,1,$this->id_dep_u),
				//vbdenModel::GetDataSVB((int)$this->data->ID_SVB),
				"ID_SVB",
				"NAME",
				"ID_SVB",
				"ID_SVB_TEXT",
				true,
				"width:200px",
				"$onok;selectloaivb();",
				(int)$this->data["ID_SVB"],
				'');
			?>
			<div class="clr"></div>            
			<span class="box_erro_area" id="ERRID_SVB"></span> 			
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo "Loại văn bản" ?></font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<!-- Loại văn bản -->
			<?php
				$onok = "";
				foreach($arr_col as $col)
					if($col == 'ID_LVB')
						$onok = "getSodi(document.frm.ID_SVB);";
				echo QLVBDHCommon::AutoComplete(
				vbdenModel::GetDataLVB((int)$this->data->ID_LVB),
				"ID_LVB",
				"NAME",
				"ID_LVB",
				"ID_LVB_TEXT",
				true,
				"width:200px",
				"$onok;updateSKH();",
				(int)$this->data["ID_LVB"],
				'');
			?>
			<div class="clr"></div>            
			<span class="box_erro_area" id="ERRID_LVB"></span>
		</td>
		<td width="100%"></td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Số ký hiệu</font>
			<font color="Red" size="3">*</font>	
		</td>
		<td nowrap="nowrap" valign="top">
			<!-- Số ký hiệu -->
			<input type=text size="30" class=inputbox name="SOKYHIEU" id="SOKYHIEU" value="<?=$this->data["SOKYHIEU"]?>"  >
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRSOKYHIEU"></span>		
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Số đi</font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<!-- Số đi -->
			<input type=text class=inputbox size="4" name="SODI" id="SODI" 
			value="<?php if($this->id>0) echo $old_sodi?>">
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRSODI"></span>	
		</td>
		<td width="100%"></td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Ngày ban hành</font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<!-- Ngay ban hanh -->
			<?=QLVBDHCommon::calendarFull(QLVBDHCommon::MysqlDateToVnDate($this->data["NGAYBANHANH"]),"NGAYBANHANH","NGAYBANHANH") ?>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRNGAYBANHANH"></span>	
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Người soạn</font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			
			<?php
				echo QLVBDHCommon::AutoComplete(
				UsersModel::getAllNameAndId(1),
				"ID_U",
				"NAME",
				"NGUOISOAN",
				"NGUOISOAN_TEXT",
				true,
				"width:200px",
				"addChuyenDeBiet(3);updateSKH(document.frm.ID_LVB.value,document.frm.NGUOISOAN.value,document.frm.ID_CQ.value);",
				$this->data["NGUOISOAN"],
				'');
			?>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRNGUOISOAN"></span>	
		</td>
		<td width=20 nowrap="nowrap"></td>
		
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Người ký</font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<!-- Nguoi ky-->
			
			<?php
				echo QLVBDHCommon::AutoComplete(
				Vb_nguoikyModel::getData(0),
				"ID_U",
				"NAME",
				"NGUOIKY",
				"NGUOIKY_TEXT",
				true,
				"width:200px",
				"addChuyenDeBiet(1)",
				$this->data["NGUOIKY"],
				'');
			?>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRNGUOIKY"></span>	
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Người trình</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<!-- Nguoi tao == nguoi trinh-->
			<?php
				echo QLVBDHCommon::AutoComplete(
				UsersModel::getAllNameAndId(1),
				"ID_U",
				"NAME",
				"NGUOITAO",
				"NGUOITAO_TEXT",
				true,
				"width:200px",
				"addChuyenDeBiet(2)",
				(int)$this->data["NGUOITAO"],
				'');
			?>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRNGUOITAO"></span>
		</td>
		<td width="100%"></td>
	</tr>
	
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Trích yếu</font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top" colspan="4">
			<!-- Trich yeu -->
			<TEXTAREA NAME="TRICHYEU" ROWS="2" style="width:99%;"><?=$this->data["TRICHYEU"]?></TEXTAREA>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRTRICHYEU"></span>
		</td>
		<td width="100%"></td>
	</tr>
	<?php if($this->isluuthumuc==1 && false){ ?>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Lưu thư mục</font>
			<font color="Red" size="3"></font>
		</td>
		<td nowrap="nowrap" valign="top" colspan="4">
			<?php if($this->isluuthumuc==1){
				?>
			<select name=THUMUC>
				<option value=0>--Chọn thư mục lưu trữ--</option>
			<?php
				foreach($this->thumuc as $row){
			?>
					<option value="<?=$row['ID_THUMUC']?>"><?=str_repeat("--",$row['LEVEL']).htmlspecialchars($row['NAME'])?></option>
			<?php
				}
			?>
				</select>
			<?php
			}
			?>
		</td>
		<td width="100%"></td>
	</tr>
	<?php } ?>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">File đính kèm</font>
		</td>
		<!-- File dinh kem -->
		<td nowrap="nowrap" valign="top" colspan="4" id="idFileDinhKem"></td>
		<script>
			loadDivFromUrl('idFileDinhKem',<?echo $url ?>,0);
		</script> 

		<td width="100%"></td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Chuyển để biết</font>
		</td>
		<!-- Chuyen de biet -->
		<td nowrap="nowrap" valign="top" colspan="3">
			<?php echo QLVBDHCommon::writeMultiSelectDepartmentUser('DEP_NGUOIGUI','NGUOIGUI')?>
			<input type="button" value="Chọn" onclick="InsertIntoArr()" />
			
		</td>
		<td width="100%">
		<div id="listuser"></div>
		</td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Số bản</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<!-- so ban -->
			<input type=text class=inputbox name=SOBAN value="<?=$this->data["SOBAN"]==""?1:$this->data["SOBAN"]?>" size='3'>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRSOBAN"></span>	
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Độ mật</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<!-- Do mat -->
			<select name="DOMAT" id="DOMAT" class="inputbox" >
            	<option value="0"><?php echo '[Chọn độ mật]' ?></option>
            	<option value="1"><?php echo 'Bình thường' ?></option>
            	<option value="2"><?php echo 'Mật' ?></option>
            	<option value="3"><?php echo 'Tối mật' ?></option>
            	<option value="4"><?php echo 'Tuyệt mật' ?></option>                                
             </select>
			<div class="clr"></div>
			<script>document.frm.DOMAT.value=<?=$this->data["DOMAT"]?></script>
			<span class="box_erro_area" id="ERRDOMAT"></span> 
		</td>
		<td width="100%"></td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Số tờ</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<input type=text class=inputbox name=SOTO value="<?=$this->data["SOTO"]==""?1:$this->data["SOTO"]?>" size=3>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRSOTO"></span>	
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Độ khẩn</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<select name="DOKHAN" id="DOKHAN" class="inputbox"  >
            	<option value="0"><?php echo '[Chọn độ khẩn]' ?></option>
            	<option value="1"><?php echo 'Bình thường' ?></option>
            	<option value="2"><?php echo 'Khẩn' ?></option>
            	<option value="3"><?php echo 'Hỏa tốc' ?></option>                                
            </select>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRDOKHAN"></span>  
			<script>document.frm.DOKHAN.value=<?=$this->data["DOKHAN"]?></script>
		</td>
		<td width="100%"></td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			
		</td>
		<td nowrap="nowrap" valign="top">
			
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Lĩnh vực văn bản</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<select name="ID_LVVB" id="ID_LVVB"   >
           	<?php 
            		echo vbdenModel::WriteLVVB((int)$this->data["ID_LVVB"]);
			?> 
		 </select> 
		</td>
		<td width="100%"></td>
	</tr>
</table>

<input type=hidden name="idhscv" value=<?php echo $this->idhscv;?>>
<input type=hidden name="idduthao" value=<?php echo $this->idduthao;?>>
<input type=hidden name="id" value=<?php echo $this->id;?>>
<input type=hidden name="SODI_IN" value=<?php echo (int)$this->data["SODI_IN"];?>>
<input type=hidden name="SOKYHIEU_IN" value=<?php echo (int)$this->data["SOKYHIEU_IN"];?>>
</form>
<script>

function changeCQNHAN(is_begin){
	if (is_begin == 1){
	}else{	
		document.frm.ID_SVB.value = 0;
		document.frm.ID_SVB_TEXT.value = "";
	}
	document.frm.ID_CQ_TEXT.value = arr_CQs[document.frm.ID_CQ.value] + "";
	var submitAjax = new AjaxEngine(); 
			var cqbh = document.frm.ID_CQ.value;
			if(cqbh == "")
				cqbh = 0;	
			var oXmlHttp = submitAjax.createXMLHttp();
			oXmlHttp.open("get", "/vbdi/banhanh/getsvbbycoquanbh?COQUANBH="+cqbh , true); 
			oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); 
			
			oXmlHttp.onreadystatechange = function () { 
				
			if (oXmlHttp.readyState == 4) { 
				//alert(oXmlHttp.responseText);
				if (oXmlHttp.status == 200) { 
					DATA_ID_SVB = new Array();
					var lnc = 0;
					var id_svb = 0;
					var name = "";
					myData = json_parse(oXmlHttp.responseText, function (key, value) {
						var is_valid = 0;
						if(key =="ID_SVB"){
							id_svb = value;
							lnc ++;
						}
						if(key =="NAME"){
							is_valid = 1;
							name = value;
							lnc ++;
						}
						if(lnc%2==0 && is_valid==1)
							DATA_ID_SVB[DATA_ID_SVB.length]= new Array(id_svb,name);
					}	
					);
				
				
            } else { 
               
            } 
        } 
       }; 
   		
		oXmlHttp.send(null);
}
changeCQNHAN(1);
var arrSVB = Array();
<?php 
	foreach($this->svb as $item){
?>
		arrSVB[arrSVB.length] = Array('<?=$item->ID_SVB?>','<?=$item->ID_LVB?>');
<?php
	}
?>
var arrLVB = Array();
<?php 
	foreach($this->lvb as $item){
?>
		arrLVB[arrLVB.length] = Array('<?=$item->ID_LVB?>','<?=$item->KYHIEU?>');
<?php
	}
?>
var arrNS = Array();
<?php 
	foreach($this->ns as $item){
?>
		arrNS[arrNS.length] = Array('<?=$item['ID_U']?>','<?=$item['KYHIEU_PB']?>');
<?php
	}
?>
var arrCQ = Array();
<?php 
	foreach($this->cq as $item){
?>
		arrCQ[arrCQ.length] = Array('<?=$item['ID_CQ']?>','<?=$item['KYHIEU']?>','<?=$item['ID_SVB']?>','<?=$item['NAME']?>');
<?php
	}
?>
/**
Xu ly cac nut Back , Save 
*/
function BackButtonClick()
{
	//document.frm.action = "/vbdi/banhanh/list";
	//document.frm.submit();
	
	window.location = "/vbdi/banhanh/list#vbdi<?=$this->id?>";
}

function SaveButtonClick(){
	
	//validate tai client
	var err = true;
	err = err & validateInput("gt=0",document.frm.ID_SVB,"<?php echo MSG11001017?>");
	err = err & validateInput("gt=0",document.frm.ID_LVB,"<?php echo MSG11001017?>");
	err = err & validateInput("req",document.frm.SOKYHIEU,"<?php echo MSG11001014 ?>");    
	err = err & validateInput("req",document.frm.SODI,"<?php echo MSG11001014 ?>");
	err = err & validateInput("req",document.frm.NGAYBANHANH,"<?php echo MSG11001014 ?>");
	err = err & validateInput("date",document.frm.NGAYBANHANH,"<?php echo MSG11001015 ?>");
	err = err & validateInput("gt=0",document.frm.ID_CQ,"<?php echo MSG11001017?>"); 
	//err = err & validateInput("gt=0",document.frm.NGUOITAO,"<?php echo MSG11001017?>"); 
	err = err & validateInput("gt=0",document.frm.NGUOIKY,"<?php echo MSG11001017?>"); 	
	err = err & validateInput("req",document.frm.TRICHYEU,"<?php echo MSG11001014 ?>");
	if(err == true)
    {
       
    	//Luu van ban di bang ajax
    	var submitAjax = new AjaxEngine(); 
		var oXmlHttp = submitAjax.createXMLHttp();
		oXmlHttp.open("post", "/vbdi/banhanh/save" , true); 
		oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); 
		document.frm.SOKYHIEU_IN.value = getSokyhieuIn();
        if(document.frm.SOKYHIEU_IN.value == -1)
        	document.frm.SOKYHIEU_IN.value = "";
		document.frm.SODI_IN.value = checkdinhdangsodi();
		if(document.frm.SODI_IN.value == -1){
			
			document.getElementById('ERRSODI').innerHTML = "Số đi không hợp lệ";
			return ;
		}
		var post = submitAjax.getDataFromFrm(document.frm);
		oXmlHttp.onreadystatechange = function () { 
		if (oXmlHttp.readyState == 4) { 
			
			if (oXmlHttp.status == 200) { 
				//alert(oXmlHttp.responseText);
				if(oXmlHttp.responseText == 1){
					var is_capnhat = "<?=$this->id?>";
					if(is_capnhat > 0){
						alert("Đã cập nhật văn bản thành công.");
						window.location = "/vbdi/banhanh/list#vbdi<?=$this->id?>";
						return;
					}
					alert("Đã lưu văn bản thành công.");
					document.frm.TRICHYEU.value = "";
					document.frm.SOKYHIEU.value = "";
					document.frm.NGAYBANHANH.value = "";
					
					document.frm.NGUOITAO.value = 0;
					document.frm.NGUOITAO_TEXT.value = "";
					//document.frm.NGUOIKY.value = 0;
					document.frm.NGUOITAO_TEXT.value = "";
					document.frm.SOBAN.value = "1";
					document.frm.SOTO.value = "1";
					document.frm.DOMAT.value = "0";
					document.frm.DOKHAN.value = "0";
					//document.frm.ID_CQ.value = "0";
					document.frm.ID_LVVB.value = "0";
					arr1 = new Array();
					arr_user = new Array();
					arr_user_temp = new Array();
					ShowArr('listuser',arr1,arr_user);
					FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
					//document.frm.COQUANBANHANH_TEXT.value = "";
					loadDivFromUrl('idFileDinhKem',<?=$url?>,1);
					getSodi(null);
				}
				else{
					if(oXmlHttp.responseText == 2){
						//loi so di khong hop le
						document.getElementById('ERRSODI').innerHTML = "Số đi không hợp lệ";
					}
				}
				
	        } else { 
            
        	} 
    	} 
   }; 
   oXmlHttp.send(post);
		
}
    	
    		
    
}

/* Cac ham xu ly khung chon chuyen de biet */
//Ham xu ly chon nhieu nguoi dung cua nguyennd
var arr_user = new Array();
var arr1 = new Array();
var arr_user_temp = new Array();
<?php
	
	if(count($this->data_chuyendebiet)>0)
	{
		$i=0;
		foreach ($this->data_chuyendebiet as $item )
		{
			$i++;
?>
		arr_user.push(new Array("<?php echo $item['DEP_NN']?>","<?php echo $item['NGUOINHAN']?>","<?php echo $item['EMPNN']?>","<? echo $item['EMPNC']?>"
		,"<? echo $item['ID_VBDI_DLC']?>","1"
		));
		arr_user_temp.push( new Array("<?php echo $item['NGUOINHAN']?>"));
<?php
		}
	}
?>

<?php 
if($this->id_duthao){
?>


<?php
	
	if(count($this->cdb_macdinh)>0)
	{
		$i=0;
		foreach ($this->cdb_macdinh as $item )
		{
			$i++;
?>
		arr_user.push(new Array("<?php echo $item['DEP_NN']?>","<?php echo $item['NGUOINHAN']?>","<?php echo $item['EMPNN']?>","<? echo $item['EMPNC']?>"
		,"<? echo $item['ID_VBDI_DLC']?>","0"
		));
		arr_user_temp.push( new Array("<?php echo $item['NGUOINHAN']?>"));
<?php
		}
	}
?>
<?php 	
}
//if( $this->id > 0){ ?>
arr1 = new Array();
arr1[0] = new Array(100,'Tên');
arr1[1] = new Array(0,'Xóa');

ShowArr('listuser',arr1,arr_user);
FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);

<?php //}?>
function InsertIntoArr()
{
	
		var opt = document.frm.NGUOIGUI.options;
		for(var i=0;i<opt.length;i++){
			if(opt[i].selected){
				arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,opt[i].value,opt[i].text,'<?=$this->name_u?>');
				arr_user_temp[arr_user_temp.length] = new Array(opt[i].value);
			}
		}
	    //arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,document.frm.NGUOIGUI.value,document.frm.NGUOIGUI[document.frm.NGUOIGUI.selectedIndex].innerHTML);
	    arr1[0] = new Array(100,'Tên');
	    arr1[1] = new Array(0,'Xóa');
	    ShowArr('listuser',arr1,arr_user,1);
	    FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
	
	/*var check = true;
	for(i=0;i<arr_user.length;i++)
    {
    	if(document.frm.NGUOIGUI.value==arr_user[i][1])  
    	{
    	  check=false;
    	}
    	
    }
    if(check)
    {
    	arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,document.frm.NGUOIGUI.value,document.frm.NGUOIGUI[document.frm.NGUOIGUI.selectedIndex].innerHTML);
    	arr1[0] = new Array(100,'Tên');
    }
    ShowArr('listuser',arr1,arr_user);*/
}
function DeleteFromArr(value)
{
    for(i=0;i<arr_user.length;i++)
    {
    	if(arr_user[i][1]==value)
    	delete arr_user[i][1];    	
    	
    }
    ShowArr('listuser',arr1,arr_user);    
}

/**
 * Tạo lưới từ 2 mảng
 * 
 * @param String idDiv id div hoặc khung chứa lưới
 * @param int Arr1 mảng chứa tên trường và độ rộng tính theo % của trường
 * @param int Arr2 mảng chứa dữ liệu của các trường trên
 * @return html code
 */
function ShowArr(idDiv,Arr1,Arr2){
        var html;
        if(Arr2.length == 0){
        	document.getElementById(idDiv).innerHTML = "";
        	return;
        }
	    html = '<table class="adminlist">';
	    html += '<thead>';
	    html += '<tr>';
	    html += '<th nowrap>#</th>';
	    
	    html += '<th width=100% colspan=2>Người nhận</th>'
	    html += '</tr>';
	    html += '</thead>';
	    html += '<tfoot><tr><th colspan=3 align=left>';
	    html += '</th></tr></tfoot>';
	    html += '<tbody>';
	    	for(i=0;i<Arr2.length;i++){
	    		html += '<tr>';
	    		html += '<td nowrap align="right">' + (i + 1) + '</td>';
	    		html += '<td width=100%>';
	    		html += Arr2[i][2];
	    		if(Arr2[i][5] == 1)
	    			html += "<input type=hidden name=ID_OLD[] value="+Arr2[i][4]+">";
	    		else 
	    			html += "<input type=hidden name=ID_U[] value="+Arr2[i][1]+">";	
	    		
	    		html += '</td>';
	    		
	    		html += '<td nowrap>';
	    		html += '<a href="javascript:;" onclick="arr_user_temp.splice('+i+',1);arr_user.splice('+i+',1);ShowArr(\'listuser\',arr1,arr_user);FastReload();return false;">Xóa</a>';
	    		html += '</td>';
	    		html += '</tr>';
	        }
	    	html += '</tbody>';
	    	html += '</table>';
	    //
		    //alert(html);
	    document.getElementById(idDiv).innerHTML = html;
	}
	function FastReload(){
	    FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
	}

	function addChuyenDeBiet(th){
	//th 1: nguoi ky
	//th 2: nguoi trinh
		
		var user_id =0;
		var user_name = "";
		if(th==1){
			//nguoi ky
			user_id = document.frm.NGUOIKY.value;
			user_name = document.frm.NGUOIKY_TEXT.value;
		}
		if(th==2){
			//nguoi ky
			user_id = document.frm.NGUOITAO.value;
			user_name = document.frm.NGUOITAO_TEXT.value;
		}
		if(th==3){
			//nguoi soan
			user_id = document.frm.NGUOISOAN.value;
			user_name = document.frm.NGUOISOAN_TEXT.value;
		}
		if(user_id >0){
			var ok=true;
			for(var i=0;i<arr_user.length;i++){
				if(arr_user[i][1]==user_id){
					ok = false;
					break;
				}
			}
			if(ok){
				arr_user.push(new Array(ARR_NGUOIGUI[user_id],user_id,user_name,"","","0"));
				arr_user_temp.push( new Array(user_id));
				ShowArr('listuser',arr1,arr_user);
				FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
			}
		}
	}
/* Ket thuc cac ham xu ly chon de biet */


/* Cac ham kiem tra so ky hieu*/
//begin trunglv
function check_sokyhieu(msg)
{
	if(msg=='1')
	{
		document.getElementById('ERRSOKYHIEU').innerHTML ="Giá trị này đã tồn tại";
	}
	else if(msg=='2')
	{
		document.getElementById('ERRSOKYHIEU').innerHTML ="<font color='blue'>Số ký hiệu này hợp lệ</font>";
	}
	else  
	if(msg=='3')
	{
		document.getElementById('ERRSOKYHIEU').innerHTML ="Lỗi server";
	}
	else  
	if(msg=='0')
	{
		document.getElementById('ERRSOKYHIEU').innerHTML ="Vui lòng nhập số ký hiệu";
	}	
}

/* ket thuc cac ham kiem tra so ky hieu*/

/* Cac ham kiem tra so di*/
//
function checkFail(msg)
{
	alert('Kiểm tra dữ liệu gặp lỗi');
}


/**
	Ham goi du lieu ve server de kiem tra so di co hop le hay khong
*/
function checkSodi(){
	//var svb = document.getElementById("id_ID_SVB").value;
	var cq = document.getElementById("id_ID_CQ").value;
	var sodi = document.getElementById("id_SODI").value;
	var err = validateInput("numeric",document.frm.SODI,"(Phải nhập số)");
	if(err == false)
		return;
	if(trim(cq)<=0) return false;
	var checkAjax = new AjaxEngine();     	
	var url="/vbdi/banhanh/getsodi/type/1";
	url=url+"/id_cq/"+document.getElementById("id_ID_CQ").value;		
	url=url+"/id_svb/"+document.getElementById("id_ID_SVB").value;		
	url=url+"/id_lvb/"+document.getElementById("id_ID_LVB").value;	
	url=url+"/sodi/"+sodi;	
	var type_request = "POST";
	if(trim(sodi)!='')
	{
		sendRequestToServer(url,type_request,validate_sodi,checkFail);
	} 
	return false;
}
/**
Sau khi server kiem tra so di va tra ve mot gia tri , ham nay se hien thi thong tin ra man hinh
*/
function validate_sodi(msg){
	var sd = document.frm.SODI.value;
	$err_field = document.getElementById("ERRSODI");
	if(msg == -1){
		$err_field.innerHTML = "Chưa xác định được";
		return;
	}
		
	$st_stt =  "Số đi tiếp theo là "+(msg+1)+" ";
	if(sd < msg)
		$err_field.innerHTML= "("+$st_stt+".Số đi không hợp lệ.)";
	else
		$err_field.innerHTML= "<font color='blue'>"+"("+$st_stt+".Số đi hợp lệ.)"+"</font>";
		
		
}


/**
Ham lay so di tiep theo cua van ban sau khi chon so van  ban hay loai van ban tuy theo cau hinh cua he thong 
*/
getSodi(null);

function getSodi(param){

<?php 


?>
len = <?php echo $len_arr?>;
var arr_col = new Array();
var ln  = 0;

<?php for($i=0;$i<$len_arr;$i++)
		echo "arr_col[$i]='".$arr_col[$i]."';";	?>
var ln2 = 0;

if(len == 0)
	ln = 1;
for(i = 0 ; i< len ; i++)
{
	if(param!=null)
	{
		if(param.name != arr_col[i]){
			ln2 = 1;
			continue;
		}
		switch(arr_col[i]){
			//
			case 'ID_LVB':
				if(document.frm.ID_LVB.value == 0)
				{
					ln = 1;
					break;
					
				}
			break;
			case 'ID_SVB':
				if(document.frm.ID_SVB.value == 0)
				{
					ln = 1;
					break;
					
				}
			break;
			default:
			break;
		}
	}
}



if(ln==0 && ln2==0){
	var checkAjax = new AjaxEngine();     	
	var url="/vbdi/banhanh/getsodi/type/2/id/<?php echo $this->id?>";
	url=url+"/id_cq/"+document.getElementById("ID_CQ").value;		
	url=url+"/id_svb/"+document.getElementById("ID_SVB").value;		
	url=url+"/id_lvb/"+document.getElementById("ID_LVB").value;	
	var type_request = "POST";
	sendRequestToServer(url,type_request,updateSodi,checkFail);
	
}else{
	if(param == null){
		var checkAjax = new AjaxEngine();     	
		var url="/vbdi/banhanh/getsodi/type/2/id/<?php echo $this->id ?>";
		url=url+"/id_cq/"+document.getElementById("ID_CQ").value;		
		url=url+"/id_svb/"+document.getElementById("ID_SVB").value;		
		url=url+"/id_lvb/"+document.getElementById("ID_LVB").value;	
		var type_request = "POST";
		sendRequestToServer(url,type_request,updateSodi,checkFail);
	}
	
}
/**
Ham cap nhat so di cua van ban khi nhan du lieu tu server
*/

function updateSodi(msg){
	
	if(msg == -2)
	{	
		document.frm.SODI.value = '<?=$old_sodi?>';	
		//updateSKH();
		
	}else{
		document.frm.SODI.value = (msg+1);	
		//alert(document.frm.ID_CQ.value);
		updateSKH(document.frm.ID_LVB.value,document.frm.NGUOISOAN.value,document.frm.ID_CQ.value);
	}
	
	var fade = function (node) {
	        var level = 1;
	        var step = function (  ) {
	            var hex = level.toString(16);
	            node.style.backgroundColor = '#FFFF' + hex + hex;
	            if (level < 15) {
	                level += 1;
	                setTimeout(step, 100);
	            }
	        };
	        setTimeout(step, 100);
	    };
	    fade(document.frm.SODI);
	
	}
	
	
}	

/* ket thuc ham kiem tra so di*/

function updateSKH(loaivb,nguoisoan,cq){
	
	loaivb =  document.frm.ID_LVB.value;
	nguoisoan =  document.frm.NGUOISOAN.value;
	cq =  document.frm.ID_CQ.value;
	var kyhieuvb = "";
	var kyhieuns = "";
	var kyhieucq = "";
	for(var i=0;i<arrLVB.length;i++){
		if(arrLVB[i][0]==loaivb){
			kyhieuvb = arrLVB[i][1];
			break;
		}
	}
	for(var i=0;i<arrNS.length;i++){
		if(arrNS[i][0]==nguoisoan){
			kyhieuns = arrNS[i][1];
			break;
		}
	}
	for(var i=0;i<arrCQ.length;i++){
		
		if(arrCQ[i][0]==cq){
			kyhieucq = arrCQ[i][1];
			
			break;
		}
	}

	
	if(kyhieuvb=="CV"){
		document.frm.SOKYHIEU.value = document.frm.SODI.value + "/" + kyhieucq + "-" + kyhieuns;
	}else{
		document.frm.SOKYHIEU.value = document.frm.SODI.value + "/" + kyhieuvb + "-" + kyhieucq;
	}
}

function selectloaivb(){
    var idsvb = document.frm.ID_SVB.value;
    //alert(idsvb);
    //alert(arrSVB.length);
    for(var i=0;i<arrSVB.length;i++){
    	//DATA_ID_LVB
    	//alert(arrSVB[i][0]);
    	if(arrSVB[i][0]==idsvb){
        	
        	for(var j=0;j<DATA_ID_LVB.length;j++){
            	if(DATA_ID_LVB[j][0]==arrSVB[i][1]){
            		document.frm.ID_LVB_TEXT.value = DATA_ID_LVB[j][1];
            		document.frm.ID_LVB.value = DATA_ID_LVB[j][0];
            	}
        	}
			
        	break;
        	
    	}
    }
    for(var i=0;i<arrCQ.length;i++){
      //  alert(document.frm.ID_SVB.value);
          if(arrCQ[i][2]==document.frm.ID_SVB.value)
              {
                document.frm.ID_CQ.value=arrCQ[i][0];
                document.frm.ID_CQ_TEXT.value=arrCQ[i][3];
              }
        }
    updateSKH(document.frm.ID_LVB.value,document.frm.NGUOISOAN.value,document.frm.ID_CQ.value);
}

function checkdinhdangsodi(){
    	var sodi_text = document.frm.SODI.value;
    	var sodi_in = "";
    	
    	for(var i = 0 ; i < sodi_text.length ;i++){
    		c = sodi_text.charAt(i);
    		
    		if(isInteger(sodi_text.charAt(i))){
    			//alert(i);
    			sodi_in += c  ; 
    		}
    		else{
    			break;
    		}
    	}
    	
    	if(i > 5 )
    		return -1;
    	if(i==0)
    		return -1;
    	//var endstr = substring(i,soden_text.length-1);
    	
    	return sodi_in;
    	
    }
    
     function getSokyhieuIn(){
    	var sokyhieu_text = document.frm.SOKYHIEU.value;
    	var sokyhieu_in = "";
    	
    	for(var i = 0 ; i < sokyhieu_text.length ;i++){
    		c = sokyhieu_text.charAt(i);
    		
    		
    		if(isInteger(sokyhieu_text.charAt(i))){
    			//alert(i);
    			sokyhieu_in += c  ; 
    		}
    		else{
    			break;
    		}
    	}
    	
    	
    	return sokyhieu_in;
    }
    addChuyenDeBiet(3);
	 function PressCtrlS(){
    	SaveButtonClick();
    }
</script>

