<?//=//QLVBDHCommon::useDlgConfirm()?>

<style>
#header ul {
	list-style: none;
	padding:0px;
	padding-bottom:20px;
	margin:0;
}

#header li {
	float: left;
	background: none;
	border-bottom-width: 0;
	margin: 0 0.0em 0 0;
	text-align:center;

    padding: 10px 10px 10px 10px;

}
#header li :hover {
	 background: #FFFFFF;
	 color:red;

	 font-style:bold;
}
#content {
	border: 1px solid;
	clear: both;
}
h1 {
	margin: 0;
	padding: 0 0 1em 0;
}
#header #selected {

}
a.tab_trangthaihoso-off:hover
{
	background-position: 0 -50px;
}
a.tab_trangthaihoso-on
{
	 color:red;

	 font-style:bold;
}
/*
#header{
	display:block;
	margin-bottom:10px;

}
.search_button{
	background:url("/images/search_button.gif") no-repeat scroll 60px 3px #FFFFFF;
	padding:5px 30px 5px 5px;
	width:100px;
}
li.tab_trangthaihoso a {
	background-image:url("/images/tab_trangthaihoso.gif");
	background-repeat:repeat-x;
	border-left:1px solid white;
	border-top:1px solid white;
	color:#FFFFFF;
	display:inline;
	float:left;
	font-weight:bold;
	height:20px;
	margin-top:2px;
	overflow:hidden;
	text-align:center;
	width:100%;
}
a.tab_trangthaihoso-off:hover
{
	background-position: 0 -50px;
}
a.tab_trangthaihoso-on
{
	background-position: 0 -100px;
}

li.tab_trangthaihoso:hoer*/
</style>
<?php
require_once 'hscv/models/PhienBanDuThaoModel.php';
require_once 'qtht/models/Vb_nguoikyModel.php';

	require_once 'Common/FileDinhKem.php';
	if(strtoupper($this->code)!=''){
		$disable="/isreadonly/1";
		$disablefile="/isreadonly/1";
	}else{
		$actid = ResourceUserModel::getActionByUrl("hscv","file","vanthu");
		//var_dump($actid);
		//echo "ss".ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0]);
		if(!ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0])){
			$disablefile="/isreadonly/1";
		}
	}
	$script="";
?>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<form name=frm method=post onsubmit="document.frm.page.value = 1;document.frm.action = '/motcua/motcua/index/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';return true;" >

<input type=hidden name="id_tths" value="<?=$this->ID_TTHS?>" >


<div style=" padding-top:20px;">
	<table>
		<tr>
			<td nowrap="nowrap" valign=top>

			Nội dung
			</td>
			<td  nowrap="nowrap" colspan="3">
			<div  >
			<input type=text name=NAMECV value="<?=$this->NAME?>"  style="width:300px">
			</div>
			<br>
			<input type="checkbox" name=INNAME value=1 <?=$this->INNAME==1?"checked":""?>>
			Trong tên hồ sơ
			<!--<input type="checkbox" name=INFILE value=1 <?=$this->INFILE==1?"checked":""?> style="display: none">Trong nội dung dự thảo-->
			</td>
			<td width="100%"></td>
		</tr>
		<!--
		<tr>
			<td nowrap="nowrap">Tên tổ chức cá nhân</td>
			<td nowrap="nowrap">
			<input type=text name=TENTOCHUCCANHAN style="width:300px">
			</td>
			<td width="100%"></td>
		</tr>
		-->
		<tr>
			<td nowrap="nowrap">Phường/xã</td>
			<td nowrap="nowrap">
			<select name="phuong" id="phuong"
			class="inputbox" size="1" onchange="document.frm.submit();">
		        <option value=0>[Chọn phường]</option>
				<?=motcua_hosoModel::toCombophuong($this->phuong)?>

			</select>
			</td>
			<td width="100%"></td>
		</tr>

		<tr>
		<td nowrap="nowrap">Loại hồ sơ</td>
			<td nowrap="nowrap">
				<select name=ID_LOAIHOSO style="width:550px"; onchange="document.frm.submit();">
				<?php

					//$loaihoso = loaiModel::GetAllLoais();

					//echo loaiModel::ToCombo($loaihoso,$this->ID_LOAIHOSO);

					$loaihoso = MotCuaModel::GetAllLoais();
					echo MotCuaModel::ToCombo($loaihoso,$this->ID_LOAIHOSO);
				?>
				</select>
			</td>
			<td width="100%"></td>
		</td>
		</tr>

		<tr>
			<td nowrap="nowrap">Ngày tiếp nhận</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendarFull($this->NHAN_NGAY_BD,"NHAN_NGAY_BD","NHAN_NGAY_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendarFull($this->NHAN_NGAY_KT,"NHAN_NGAY_KT","NHAN_NGAY_KT") ?>
			</td>
			<td width="100%"></td>
		</tr>

		<tr id=FindAdvanced3>
			<td nowrap="nowrap">Ngày hẹn trả</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendarFull($this->NHANLAI_NGAY_BD,"NHANLAI_NGAY_BD","NHANLAI_NGAY_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendarFull($this->NHANLAI_NGAY_KT,"NHANLAI_NGAY_KT","NHANLAI_NGAY_KT") ?>
			</td>
			<td width="100%"></td>
		</tr>


		<tr>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap" colspan="3"><input class=search_button  type=submit value="Tìm kiếm"></td>
			<td width="100%"></td>
		</tr>
	</table>
	</div>




<table class=adminlist>

    <thead>
    <tr>
        <td colspan=4 style="background-color:white;">
        <div class="submenu-box">

<div class="submenu-pad">
		<ul id="submenu" class="configuration">

<?php
$arr_tktths = $this->arr_tktths;
$arr_trangthais = $this->arr_trangthais;
foreach($arr_trangthais as $trangthai){
	if($this->ID_TTHS == $trangthai["ID_TTHS"] )
		$class_tab = "active";
	else
		$class_tab = "";
?>

<li class=tab_trangthaihoso id="<?php if($this->ID_TTHS == $trangthai["ID_TTHS"] ) echo "selected"; ?>">

<a  class=<?=$class_tab?> href="/motcua/motcua/index/id_tths/<?=$trangthai["ID_TTHS"]?>/"
onclick="document.frm.action='/motcua/motcua/index/id_tths/<?=$trangthai["ID_TTHS"]?>/'; document.frm.submit();"
><?=$trangthai["TEN"]?> (<?=(int)$arr_tktths[$trangthai["ID_TTHS"]]?>) </a>

</li>
<?php }?>
<?php

	$class_tab = "";
	if($this->ID_TTHS == -1)
		$class_tab = "active";
?>

<li  class=tab_trangthaihoso >
<a  class=<?=$class_tab?> href="/motcua/motcua/index/id_tths/-1/"
onclick="document.frm.action='/motcua/motcua/index/id_tths/-1/'; document.frm.submit();"
>Đã xử lý(<?=$this->num_daxl?>)</a>
</li>

</ul>
</div>
</div>
        </td>
    </tr>

		<tr>
			<th colspan="4">
				<div>
					<div class="limit" style="float:left;">Hiển thị #
						<select name="limit1"  style="width:60px;" id="limit1" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit2.value = document.frm.limit1.value;
							document.frm.action = '/motcua/motcua/index/id_tths/<?=$this->ID_TTHS?>/id_thumuc/<?=$this->id_thumuc?>/';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>2</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="30" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="30" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div class="limit" style="float:right;"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
		<tr>
			<th nowrap="nowrap">
				#
			</th>
			<th width="100%">
				Tên công việc
			</th>
			<th nowrap="nowrap">
				&nbsp;
			</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3">
				<div class="pagination">
					<div class="limit">Hiển thị #
						<select name="limit2" style="width:60px;" id="limit2" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit1.value = document.frm.limit2.value;
							document.frm.action = '/motcua/motcua/index/id_tths/<?=$this->ID_TTHS?>/id_thumuc/<?=$this->id_thumuc?>/';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="30" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="30" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div style="float:right"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
	</tfoot>
	<tbody>
<?php

	if(count($this->data)<=0){
		echo "<tr><td colspan='3'>Không tìm thấy hồ sơ công việc nào<td></tr>";
	}else{
	$stt=($this->page-1)*$this->limit;
	$i=0;
	$datatre = "";
	foreach($this->data as $row){
		//var_dump(explode(" ",$this->NAME));
		$oldname = $row['NAME'];
		$row['NAME'] = $this->INNAME==1?QLVBDHCommon::highlightWords($row['NAME'],$this->NAME):$row['NAME'];

		if(strtoupper($this->code)!="ZIP"){
			if($row['IS_THEODOI']!=1){
				$tt = hosocongviecModel::getlastlog($row['ID_PI']);
				$datatre .= $row['ID_HSCV'].",".urlencode($tt['DATESEND']).",".$tt['HANXULY'].",".$tt['ID_U_RECEIVE'].",0,";
				$parentlog = WFEngine::GetStartLogIdByProcessItem($row['ID_PI'],$tt['ID_T']);
				//var_dump($parentlog);
				if(is_array($parentlog)){
					/*foreach($parentlog as $itemparent){
						if($itemparent['ID_PL']!=$tt['ID_PL']){
							$datatre = $row['ID_HSCV'].",".urlencode($itemparent['DATESEND']).",".$itemparent['HANXULY'].",".$itemparent['ID_U_RECEIVE'].",";
						}
					}*/
				}
                //echo $datatre."<br>";
			}
			//$script .= "loadDivFromUrl('TREHAN".$row['ID_HSCV']."','/auth/user/delay/date/".urlencode($tt['DATESEND'])."/hanxuly/".$tt['HANXULY']."',1);";
		}
		$stt++;
?>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td valign="top" rowspan="2"><a name="hscv<?=$row['ID_HSCV']?>"></a><?=$stt?></td>
			<td valign="top">
				<?php
						echo "<img src='/images/icon_motcua.jpg'>";

				?>

				<?=$row['NAME']?><?=$row['EXTRA']!=""?" - ".$row['EXTRA']:""?> <span id="TREHAN<?=$row['ID_HSCV']?>"> <?=(int)$row["IS_BOSUNG"]?"(Đang chờ bổ sung)":""?> </span>
				<?php
					if($this->INFILE==1){
						$dt = PhienBanDuThaoModel::getFileContent($row['ID_HSCV']);
						foreach($dt as $itemdt){
							$rfind = QLVBDHCommon::highlightString($itemdt['CONTENT'],$this->NAME);
							if($rfind!=""){
				?>
				<br><a href="/hscv/File/download?year=&maso=<?=$itemdt['MASO']?>"><B><?=$itemdt['FILENAME']?>:</B> <?=$rfind?></a>
				<?php
							}
						}
					}
				?>
				<?php if(strtoupper($this->code)=="PHOIHOP"){

						if($row["IS_NEW_PH"] == 0){

				?>
					<img id='img_new_ph_<?=$row["ID_HSCV"]?>' src='/images/moi.gif'></img>
				<?php		}}
				?>
			</td>


			<td nowrap="nowrap" valign="top" id="NEXTSTEP<?=$row["ID_HSCV"]?>">
				<img src='/images/loading.gif' width='16' height='16' border='0'></img>
				<?php
					$is_dangxuly;
					$code = 'OLD';

					if($this->is_dangxuly)
						$code = '';
					else
						$is_dxldaxl = 1;
						$datanextstep .= $row['ID_HSCV'].",".$code.",".$row['CNTPL'].",".$row["ID_LOAIHSCV"].",".$row["ID_PI"].",".$this->ID_TTHS.",".$row['ID_YEUCAU'].",".$row['PRE_SEQ'].",";


				?>
			</td>

		</tr>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td colspan="2">
				<div>
					<ul class="chitiethscv">
					<?php if(QLVBDHCommon::TabHscv(1,$row["ID_LOAIHSCV"])==1){ ?>
						<li id=groupicon1_<?=$row["ID_HSCV"]?>>
							<img src="/images/icon_chitiet.jpg" border="0" hspace="5" >
							<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/vbden/vbden/detail/type/<?=$row["ID_LOAIHSCV"]?>/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=$disable?>",1);
							<?php if(strtoupper($this->code)=="PHOIHOP"){

								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
							'>Chi tiết</a>
						</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(6,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon6_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_luanchuyen.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/way/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]?>",6);
						<?php if(strtoupper($this->code)=="PHOIHOP"){

								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Luân chuyển</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(5,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon5_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_duthao.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/VanBanDuThao/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>/duthao/"+encodeURIComponent("<?=$oldname?>"),5);
						<?php if(strtoupper($this->code)=="PHOIHOP"){

								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Dự thảo</a>
					</li>
					<?php } ?>

					<?php if(QLVBDHCommon::TabHscv(8,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon8_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<?php $key = array_search($row["ID_HSCV"],$this->arr_idvuabosung);
							if(is_numeric($key)){
								echo "
								<img id='image_newbs_".$row['ID_HSCV']. "' src='/images/moi.gif'>
								";
						}?>
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/bosung/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id/<?=$row["ID_HSCV"]?><?=$disable?>",8);
						<?php if(is_numeric($key)){?>
						updateImageNewBS("image_newbs_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
						<?php }?>
						'>Bổ sung hồ sơ</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(3,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon3_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_phoihop.gif" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/phoihop/index/idhscv/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=strtoupper($this->code)=="PHOIHOP"?"":$disable?>",3);
						<?php if(strtoupper($this->code)=="PHOIHOP"){

								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Phối hợp</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(4,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon4_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_files.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/file/index/iddiv/groupcontent<?=$row["ID_HSCV"]?>/idObject/<?=$row["ID_LOAIHSCV"]==1?$vbden['ID_VBD']:$row["ID_HSCV"]?>/is_new/0/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]==1?"3":"1"?><?=$disablefile?>",4);
						<?php if(strtoupper($this->code)=="PHOIHOP"){

								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Đính kèm</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(7,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon7_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/vanbanlienquan/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>",7);
						<?php if(strtoupper($this->code)=="PHOIHOP"){

								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>VB liên quan</a>
					</li>
					<?php } ?>


					<li id=groupicon9_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/viewresult/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id/<?=$row["ID_HSCV"]?><?=$disable?>/is_khongxuly/<?= $row["KHONGXULY"]?>/lydo/<?= $row["LYDOKHONGXULY"]?>",9);

						'>Kết quả</a>
					</li>

					<?php if($this->id_thumuc>1 || $row["ALIAS"]=="MOTCUA"){
						require_once('motcua/models/dkwebModel.php');
						$data_maso = dkwebModel::GetMasodkquamangByIDHSCV($row["ID_HSCV"]);

						if($data_maso){
					?>
					<li id=groupicon9_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapIframe(<?=$row["ID_HSCV"]?>,"/motcua/dongbohsmc/viewdon/mahoso/<?=$data_maso?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id_hscv/<?=$row["ID_HSCV"]?><?=$disable?>",9);
						<?php if(strtoupper($this->code)=="PHOIHOP"){

								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Đơn xin cấp phép</a>
					</li>
					<?php } }?>
					</ul>
				</div>
				<div class="groupcontent" id="groupcontent<?=$row["ID_HSCV"]?>" style="display:none;background: #ffffff"></div>
			</td>
		</tr>
<?php
		$i = (-1+$i)*-1;
	}
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
<?php if(strtoupper($this->code)=="ZIP"){?>
</td></tr></table>
<?php } ?>
</form>
<script>
	function DeleteHscv(id,type){
		if(confirm("Bạn có muốn xóa công việc này không?")){
			document.location.href = "/hscv/hscv/delete/id_hscv/"+id+"/type/"+type;
		}
	}
	function DeleteHscvForVTBP(id){
		if(confirm("Bạn có muốn xóa công việc này không?")){
			document.location.href = "/hscv/hscv/deletevtbp/id_hscv/"+id;
		}
	}
	function CreateButtonClick(url){
		document.frm.action = url;
		document.frm.submit();
	}
	function SwapDiv(id,url,tab){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(tab!=i){
					if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
						document.getElementById("groupcontent"+id).style.display="none";
						document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
						break;
					}
				}
			}
		}
		if(document.getElementById("groupcontent"+id).style.display==""){
			document.getElementById("groupcontent"+id).style.display="none";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupicon";
		}else{
			document.getElementById("groupcontent"+id).style.display="";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupiconopen";
			document.getElementById("groupcontent"+id).innerHTML="<img src='/images/loading.gif' width='16' height='16' border='0'></img<img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img>";
			loadDivFromUrl("groupcontent"+id,url,1);

	}
	}
	function SwapIframe(id,url){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
					document.getElementById("groupcontent"+id).style.display="none";
					document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
					break;
				}
			}
		}
		if(document.getElementById('groupcontent'+id).style.display == ''){
			document.getElementById('groupcontent'+id).style.display = 'none';
		}else{
			document.getElementById('groupcontent'+id).innerHTML = '<iframe style="overflow-x:visible" height=0 id=iframebutphe'+id+' allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no></iframe>';
			document.getElementById('iframebutphe'+id).src = url;
			document.getElementById('groupcontent'+id).style.display = '';

		}
	}
	function Swap(id,url){
		if(document.getElementById(id).style.display==""){
			document.getElementById(id).style.display="none";
			document.getElementById("groupicon"+id).className = "groupicon";
		}else{
			document.getElementById(id).style.display="";
			document.getElementById("groupicon"+id).className = "groupiconopen";
			loadDivFromUrl(id,url,1);
		}
	}
	<?php if(count($this->data)>0){ ?>
	execfunction("auth","user","getnextstepmc","data/<?=$datanextstep?>");
	execfunction("auth","user","delay","data/<?=$datatre?>");
	<?php
	}
	?>

	function updateImageNew(iddiv,id){
    	var oimg = document.getElementById(iddiv);
    	if(oimg != null){
    		if(oimg.style.display != 'none'){
	    	oimg.style.display = 'none';

	    	var AE = new AjaxEngine();
			var oXmlHttp = AE.createXMLHttp();
		    <?php
		    $authen = Zend_Registry::get('auth');
		    $user = $authen->getIdentity();
		    ?>
			var url = '/hscv/hscv/updatedaxemphoihop?id_hscv='+id+'&id_u=<?=$user->ID_U?>';
			oXmlHttp.open('post', url , true);
		    oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
		    oXmlHttp.onreadystatechange = function () {
		        if (oXmlHttp.readyState == 4) {
		        	if (oXmlHttp.status == 200) {
		            	//alert(oXmlHttp.responseText);
		        	} else {

		            }
		        }
		    };
		    oXmlHttp.send(null);


	    	}
    	}

    }
	function thuhoi(id_hscv){

		var func_ok = 'SwapIframe('+id_hscv+',"/hscv/hscv/thuhoi/year/<?=$this->realyear?>/id/'+ id_hscv+ '");';

		var func_cancel = "";
		displayConfirm("Bạn có muốn thu hồi công việc vừa chuyển không?","","",func_ok,func_cancel);
	}

	function AddNewButtonClick(){
		//document.frm.action="/qtht/DanhMucLoaiVanBan/input";
		//document.frm.method="post";
		//document.frm.submit();
		window.location = "/motcua/motcua/input";

	}

	 function updateImageNewBS(id_img,id_hscv){
    	var oimg = document.getElementById(id_img);
    	if(oimg != null){
    		if(oimg.style.display != 'none'){
	    	oimg.style.display = 'none';

	    	var AE = new AjaxEngine();
			var oXmlHttp = AE.createXMLHttp();
			var url = '/hscv/hscv/updatedaxembosung?id_hscv='+id_hscv;
			oXmlHttp.open('post', url , true);
		    oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
		    oXmlHttp.onreadystatechange = function () {
		        if (oXmlHttp.readyState == 4) {
		        	if (oXmlHttp.status == 200) {

		        	} else {

		            }
		        }
		    };
		    oXmlHttp.send(null);


	    	}
    	}
    }
</script>