<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/calendar.js"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
<link rel="stylesheet" href="/styles/system.css" type="text/css" />
<link rel="stylesheet" type="text/css" href="/styles/rounded.css" />
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
<link rel="stylesheet" type="text/css" href="/styles/template.css" />
</head>
<body style="background-color:transparent">
<form name=frm action="/motcua/motcua/savekhongtrakip">
<fieldset>
<!--
<legend style="color:#0066CC;">Đã nhận hồ sơ của</legend>
<div class="curlycontainer" width=500>
!-->
<div class="curlycontainer" style="width:100%">
<div class="innerdiv">
<div>
<b><u>Giấy biên nhận:</u></b>
<font color="Blue"><b><i><?php echo $this->hsmcInfo->MAHOSO ?></i></b></font>
</div>
<div >
<b><u>Loại hồ sơ:</u></b>
<font><i><?php echo $this->TenLoaiHoSo ?></i></font>
</div>
<div>
<b><u>Tổ chức/cá nhân:</u></b>
<font><i><?php echo $this->hsmcInfo->TENTOCHUCCANHAN ?></i></font>
</div>
<div>
<b><u>Email:</u></b>
<font><i><?php echo $this->hsmcInfo->EMAIL ?></i></font>
</div>
<div>
<b><u>Địa chỉ:</u></b>
<font><i><?php echo $this->hsmcInfo->DIACHI ?></i></font>
</div>
</div>
</div>
</fieldset>
<fieldset>
<legend style="color:#0066CC;">Hồ sơ trễ hẹn giao trả</legend>
<div >
<label>Lý do trễ hẹn:</label>
<textarea name=khongtrakip id=khongtrakip  rows="3" cols="100"> <?php echo $this->hsmcInfo->LYDOKHONGTRAKIP  ?></textarea>
<br>
<span class="box_erro_area" id=ERRkhongtrakip>
</div>
</fieldset>
<input type="button" name="SEND" value="Chuyển" onclick="return Submit();"></input>
<input type=hidden name=id value="<?=$this->ID_HSCV?>">
<input type=hidden name=wf_id_t value="<?=$this->wf_id_t?>">
<input type=hidden name=year value="<?=$this->year?>">
</form>
<p id=lasttext></p>
<script >
var iframeElement = parent.document.getElementById("iframebutphe<?php echo $this->ID_HSCV?>");
iframeElement.style.height = ""+ (document.getElementById("lasttext").offsetTop) +"px";
iframeElement.width = "100%";
</script>
</body>
</html>
<script>

function checkInputData(){
    var err = true;
    err = err & validateInput("req",document.frm.khongtrakip,"Bạn phải nhập lý do trễ hẹn");
    return err;
}
function Submit(){
	if(checkInputData() == true)
		document.frm.submit();
}

</script>
