<form name="frmAddCap"  method="<?php echo $this->form->getAttrib('method');?>" action="/vbpq/cap/input">
<fieldset>
	<div style="text-align:right;width:100%">
		Trường có dấu <font color="red">*</font> là bắt buộc nhập
	</div>
	<div align="center"><span class="box_erro_area"><?php echo $this->error; ?></span></div>
	<div class="required">
		<label id="lblTextIput">Tên cấp<font color="red">*</font></label>
		<?php echo $this->form->getElement('TEN_CAP');?>
    	<span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('TEN_CAP'));			
            ?>
        </span>
	</div>
	<div class="clr"></div>	
</fieldset>
<input type=hidden name="id" value=<?php echo $this->id?> >
</form>

<script>
	function SaveButtonClick()
	{
		document.frmAddCap.submit();
	}
	function BackButtonClick()
	{
		document.frmAddCap.action = "/vbpq/cap/";
		document.frmAddCap.submit();
	}
</script>