<?php
	require_once 'Common/FileDinhKem.php';
	if(strtoupper($this->code)!=''){
		$disable="/isreadonly/1";
		$disablefile="/isreadonly/1";
	}else{
		$actid = ResourceUserModel::getActionByUrl("hscv","file","vanthu");
		//var_dump($actid);
		//echo "ss".ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0]);
		if(!ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0])){
			$disablefile="/isreadonly/1";
		}
	}
	$script="";
?>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse_state.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<form name=frm method=post onsubmit="document.frm.page.value = 1;document.frm.action = '/hscv/hscv/listbosung';return true;">

<?php
if(strtoupper($this->code)=="ZIP"){
?>
<table><tr><td nowrap="nowrap" valign="top" style="border-right: 1px solid">
<ul class=treeview id=treemenu2>
<li>Thư mục hồ sơ công việc
<?php 
$html = "";
echo ThuMucModel::ToTree($this->thumuc,1,"treemenu2",$html,$this->id_thumuc);
?>
</li>
</ul>
<script type="text/javascript" src="/js/simpletreemenu.js">

/***********************************************
* Simple Tree Menu- © Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/

</script>

<link rel="stylesheet" type="text/css" href="/styles/simpletree.css" />
<script type="text/javascript">

//ddtreemenu.createTree(treeid, enablepersist, opt_persist_in_days (default is 1))
ddtreemenu.createTree("treemenu2", true, 5)
ddtreemenu.flatten('treemenu2', 'expand');

</script>

</td>
<td width="100%" valign="top">
<?php } ?>
	<table>
		<!--
		<tr>
			<td nowrap="nowrap">Loại công việc</td>
			<td nowrap="nowrap"><select name="ID_LOAIHSCV" onchange="
						document.frm.page.value = 1;
						if(document.frm.TRANGTHAI!=null)document.frm.TRANGTHAI.value = 0;
						document.frm.action = '/hscv/hscv/list/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
						document.frm.submit();
				">
						<option value=0>--Chọn loại công việc--</option>
						<?=loaihosocongviecModel::ToCombo($this->loaihscv,$this->ID_LOAIHSCV)?>
				</select></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		-->

		<tr>
			<td nowrap="nowrap">Phường</td>
			<td nowrap="nowrap"><select name="ID_PHUONG" onchange="
						document.frm.page.value = 1;
						if(document.frm.TRANGTHAI!=null)document.frm.TRANGTHAI.value = 0;
						document.frm.action ='/hscv/hscv/listbosung';
						document.frm.submit();
				">
						<option value=0>--Tất cả các phường--</option>
						<option value=-1 <?=($this->ID_PHUONG==-1)?"selected":""?>>--Không xác định--</option>
						<?=DanhMucPhuongModel::ToCombo($this->phuong,$this->ID_PHUONG)?>
				</select></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<?php
			if(strtoupper($this->code)!="ZIP"){
		?>
		<tr style="display:none">
			<td nowrap="nowrap">Trạng thái</td>
			<td nowrap="nowrap"><select name="TRANGTHAI" onchange="
						document.frm.page.value = 1;
						document.frm.action = '/hscv/hscv/list/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
						document.frm.submit();
					">
						<option value=0>--Chọn trang thái--</option>
						<?=WFEngine::ToCombo($this->datatrangthai,$this->TRANGTHAI)?>
				</select></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<?php } ?>
		
		<tr>
			<td nowrap="nowrap">Tên công dân</td>
			<td nowrap="nowrap" colspan="3"><input type=text class=inputbox name=NAMECD value="<?=$this->TENTOCHUCCANHAN?>" size=50><input type=hidden name=SCOPE[] value=0 <?=count(array_keys($this->SCOPE,2))>0?"checked":""?>></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap">Mã biên nhận</td>
			<td nowrap="nowrap" colspan="3"><input type=text class=inputbox name=MABIENNHAN value="<?=$this->MAHOSO?>" size=50><input type=hidden name=SCOPE[] value=0 <?=count(array_keys($this->SCOPE,2))>0?"checked":""?>></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap">Từ ngày</td>
			<td nowrap="nowrap"><?=QLVBDHCommon::calendar($this->NGAY_BD,"NGAY_BD","NGAY_BD") ?> Đến ngày <?=QLVBDHCommon::calendar($this->NGAY_KT,"NGAY_KT","NGAY_KT") ?></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap" colspan="3"><input type=submit value="Tìm kiếm"></td>
			<td width="100%"></td>
		</tr>
	</table>

<table class=adminlist>
	<thead>
		<tr>
			<th colspan="4">
				<div>
					<div class="limit" style="float:left;">Hiển thị #
						<select name="limit1"  style="width:60px;" id="limit1" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit2.value = document.frm.limit1.value;
							document.frm.action = '/hscv/hscv/list/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div class="limit" style="float:right;"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
		<tr>
			<th nowrap="nowrap">
				#
			</th>
			<th width="100%">
				Tên công việc
			</th>
			<th nowrap="nowrap">
				&nbsp;
			</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3">
				<div class="pagination">
					<div class="limit">Hiển thị #
						<select name="limit2" style="width:60px;" id="limit2" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit1.value = document.frm.limit2.value;
							document.frm.action = '/hscv/hscv/listbosung?>';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div style="float:right"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
	</tfoot>
	<tbody>
<?php
	if(count($this->data)<=0){
		echo "<tr><td colspan='3'>Không tìm thấy hồ sơ công việc nào<td></tr>";
	}else{
	$stt=($this->page-1)*$this->limit;
	$i=0;
	$datatre = "";
	foreach($this->data as $row){
		$stt++;
?>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td valign="top" rowspan="2"><a name="hscv<?=$row['ID_HSCV']?>"></a><?=$stt?></td>
			<td valign="top">
				<?=$row['NAME']?>
			</td>
			<td nowrap="nowrap"><a href="/motcua/motcua/input/id_hscv/<?=$row['ID_HSCV']?>/id_yeucau/<?=$row['ID_YEUCAU']?>">Bổ sung hồ sơ</a></td>
		</tr>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td colspan="2">
				<div>
					<ul class="chitiethscv">
					<?php if(QLVBDHCommon::TabHscv(1,$row["ID_LOAIHSCV"])==1){ ?>
						<li id=groupicon1_<?=$row["ID_HSCV"]?>>
							<img src="/images/icon_chitiet.jpg" border="0" hspace="5" >
							<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/vbden/vbden/detail/type/<?=$row["ID_LOAIHSCV"]?>/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=$disable?>",1);
							<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
							'>Chi tiết</a>
						</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(6,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon6_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_luanchuyen.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/way/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]?>",6);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Luân chuyển</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(5,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon5_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_duthao.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/VanBanDuThao/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>",5);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Dự thảo</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(8,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon8_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/bosung/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id/<?=$row["ID_HSCV"]?><?=$disable?>",8);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Bổ sung hồ sơ</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(4,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon4_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_files.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/file/index/iddiv/groupcontent<?=$row["ID_HSCV"]?>/idObject/<?=$row["ID_LOAIHSCV"]==1?$vbden['ID_VBD']:$row["ID_HSCV"]?>/is_new/0/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]==1?"3":"1"?><?=$disablefile?>",4);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Đính kèm</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(7,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon7_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/vanbanlienquan/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>",7);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>VB liên quan</a>
					</li>
					<?php } ?>
					</ul>
				</div>
				<div class="groupcontent" id="groupcontent<?=$row["ID_HSCV"]?>" style="display:none;background: #ffffff"></div>
			</td>
		</tr>
<?php
		$i = (-1+$i)*-1;	
	}
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>
<script>
	function SwapDiv(id,url,tab){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(tab!=i){
					if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
						document.getElementById("groupcontent"+id).style.display="none";
						document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
						break;
					}
				}
			}
		}
		if(document.getElementById("groupcontent"+id).style.display==""){
			document.getElementById("groupcontent"+id).style.display="none";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupicon";
		}else{
			document.getElementById("groupcontent"+id).style.display="";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupiconopen";
			document.getElementById("groupcontent"+id).innerHTML="<img src='/images/loading.gif' width='16' height='16' border='0'></img<img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img>";
			loadDivFromUrl("groupcontent"+id,url,1);

	}
	}
	function SwapIframe(id,url){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
					document.getElementById("groupcontent"+id).style.display="none";
					document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
					break;
				}
			}
		}
		if(document.getElementById('groupcontent'+id).style.display == ''){
			document.getElementById('groupcontent'+id).style.display = 'none';
		}else{
			document.getElementById('groupcontent'+id).innerHTML = '<iframe style="overflow-x:visible" height=0 id=iframebutphe'+id+' allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no src="'+url+'"></iframe>';
			document.getElementById('groupcontent'+id).style.display = '';
		}
	}
	function Swap(id,url){
		if(document.getElementById(id).style.display==""){
			document.getElementById(id).style.display="none";
			document.getElementById("groupicon"+id).className = "groupicon";
		}else{
			document.getElementById(id).style.display="";
			document.getElementById("groupicon"+id).className = "groupiconopen";
			loadDivFromUrl(id,url,1);
		}
	}
</script>
