<table class=adminlist>
	<thead>
		<tr>
			<th>#</th>
			<th nowrap="nowrap">Ngày chuyển</th>
			<th nowrap="nowrap">Người chuyển</th>
			<th nowrap="nowrap">Người/phòng/nhóm nhận</th>
			<th width=100%>Nội dung chuyển</th>
			<th nowrap="nowrap">Hạn XL</th>
			<th nowrap="nowrap">Tiến độ</th>
		</tr>
	</thead>
	<tfoot>
		<tr><th colspan="7"></th></tr>
	</tfoot>
	<tbody>
<?php
	$stt=0;
	$i=0;
	$count_pro = count($this->sendprocess);
	
	for($j=0;$j<count($this->sendprocess);$j++){
		$rowsend = $this->sendprocess[$j];
		//var_dump($rowsend );
		$stt++;
		$content = trim($rowsend["NOIDUNG"]);
		if($content!=""){
			$span = "rowspan=2";
		}else{
			$span="";
		}
?>
		<tr class="row<?php echo $i; ?>">
			<td <?=$span?>><?php echo $stt; ?></td>
			<td nowrap="nowrap" <?=$span?>>
				<?=date("d/m/Y",strtotime($rowsend["DATESEND"]))?><br>
				<?=date("H:i:s",strtotime($rowsend["DATESEND"]))?>
			</td>
			<td nowrap="nowrap"><?=$rowsend["EMPNCNAME"]?>&nbsp;</td>
			<td nowrap="nowrap"><?=$rowsend["DEPNAME"].$rowsend["GROUPNAME"].$rowsend["EMPNNNAME"]?>&nbsp;
			
			</td>
			<td width=100%><?=nl2br(htmlspecialchars($rowsend["NAME"]))?>&nbsp;</td>
			<td nowrap="nowrap">
				<span id="HANXULY_<?=$rowsend["ID_PL"]?>"><?=QLVBDHCommon::createTextHanXuLy($rowsend["HANXULY"])?></span>&nbsp;
				<?php if($rowsend["HANXULY"]!=0 && $rowsend["TRE"]=="" && $rowsend["ID_U_NC"]==Zend_Registry::get('auth')->getIdentity()->ID_U){
				?>
				<a href="#" onclick="document.getElementById('GIAHAN_<?=$rowsend["ID_PL"]?>').style.display='';return false;">Gia hạn</a>
				<div style="display:none" id="GIAHAN_<?=$rowsend["ID_PL"]?>">
					<?=QLVBDHCommon::createInputHanxuly("HANXULY1_".$rowsend["ID_PL"],"HANXULY_".$rowsend["ID_PL"],$rowsend["HANXULY"])?>
					<input type=button value="Đồng ý" onclick="
						execfunction('hscv','hscv','giahan','ID_PL/<?=$rowsend["ID_PL"]?>/HANXULY/'+document.frm.HANXULY_<?=$rowsend["ID_PL"]?>.value);
						document.getElementById('GIAHAN_<?=$rowsend["ID_PL"]?>').style.display='none';
						document.getElementById('HANXULY_<?=$rowsend["ID_PL"]?>').innerText=createTextHanXuLy(document.frm.HANXULY_<?=$rowsend["ID_PL"]?>.value);
					">
				</div>
				<?php 
				} 
				?>
			</td>
			<td nowrap="nowrap">
				<?php if(($rowsend["IS_THEODOI"]!=1 || $j!=count($this->sendprocess)-1) && $rowsend["ISLAST"]!=1){ ?>
					<?=$rowsend["TRE"]>0?QLVBDHCommon::trehantostr($rowsend["TRE"],$rowsend["DATESEND"],$rowsend["HANXULY"]):""?>
					<?php 
						if($rowsend["TRE"]=="" && $rowsend["HANXULY"]>0 && $rowsend["IS_THEODOI"]!=1){
					?>
						<?=QLVBDHCommon::trehantostr(QLVBDHCommon::getTreHan($rowsend["DATESEND"],$rowsend["HANXULY"]),$rowsend["DATESEND"],$rowsend["HANXULY"])?>
					<?php 
						}
					?>
				<?php }else if($rowsend["ISLAST"]==1){
				?>
				<font color=blue>Đã xử lý xong</font>
				<?php
				}else{ ?>
					<font color=red>Đã lưu theo dõi</font>
				<?php } ?>
			</td>
		</tr>
		
		
			<?php if($rowsend["IS_BOSUNG"]==1 && ( $j==($count_pro-1) ) ) { ?>
			<tr class="row<?php echo $i; ?>">
			<td colspan="7"><font color=red>Đang chờ bổ sung hồ sơ</font> &nbsp;</td>
			</tr>
			<?php }else{
			if($content!=""){
			?>
			<tr class="row<?php echo $i; ?>">
			<td colspan="7"><b>Ý kiến:</b> <?=nl2br(htmlspecialchars($rowsend["NOIDUNG"]))?>&nbsp;</td>
			</tr>
			<?php }?>
			<?php } ?>
		
<?php
		$i = -1*($i-1);
	}
?>
	</tbody>
</table>
<table class=admintable width="100%">
	<tbody>
		<?php
			if($this->idobject>0){
		?>
		<tr>
			<td class=key nowrap="nowrap">
				Chuyển để biết
			</td>
			<td width="100%">
				<?php
					$currentnc = 0;
					$currentnd = "";
					foreach($this->way as $way){
						if($way['NGUOICHUYEN']!=$currentnc || $way['GHICHU']!=$currentnd){
							if($currentnd!=""){
								echo "<br><font color=blue style='margin-left:80px;'><b>Ý kiến:</b> ".$currentnd."</font>";
							}
							echo $currentnc!=0?"<br>":"";
							echo "<b>".date("d/m/Y H:i:s",strtotime($way["NGAYCHUYEN"]))."</b>: ";
							echo $way["EMPNC"];
							echo " <img src='/images/j_arrow.png'>";
							$currentnc = $way['NGUOICHUYEN'];
						}
						$currentnd = $way['GHICHU'];
						echo $way['EMPNN'].", ";
					}
					if($currentnd!=""){
						echo "<br><font color=blue style='margin-left:80px;'><b>Ý kiến:</b> ".$currentnd."</font>";
					}
				?>
			</td>
		</tr>
		<?php
			}
			if($this->idobject>0){
		?>
		<?php if($this->isCapnhat == 1){ ?>
		<tr>
			<td>
				
			</td>
			<td>
				<a href="javascript:;" onclick="
					document.getElementById('iframesend<?=$this->ID_HSCV?>').style.display='';
					document.getElementById('iframesend<?=$this->ID_HSCV?>').setAttribute('src','/hscv/hscv/send/id/<?=$this->ID_HSCV?>/type/<?=$this->type?>/year/<?=$this->year?>');
				">Chuyển để biết</a>
			</td>
		</tr>
		<?php } ?>
		<?php
			}
		?>
	</tbody>
	<?php
		if($this->idobject>0){
	?>
	<tfoot>
		<tr>
			<th colspan="2">
				<iframe style="overflow-x:visible;display:none" height=0 id=iframesend<?=$this->ID_HSCV?> allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no src=""></iframe>
			</th>
		</tr>
	</tfoot>
	<?php
		}
	?>
</table>
