
<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>#</th>			
			<th >Người mượn</th>
			<th >Người cho mượn</th>			
			<th nowrap>Người trả</th>
			<th nowrap>Ngày Mượn</th>
			<th nowrap>Ngày phải trả</th>
			<th nowrap>Ngày trả thực tế</th>
			<th nowrap></th>
			<th nowrap></th>
		</tr>
	</thead>
	<tfoot>		
	</tfoot>
	<tbody>
<?php
$stt		= 0;
$i			= 0;
$status		= "";
$status2	= "";
$isdelete	= "";
$trahoso	= "";
foreach ($this->data as $row )
{
$stt++;
$status		= $row['NGAYTRA_THUCTE'];
$status2	= $row['ID_MUONTRA'];
?>
		<tr class="row<?=$i?>">
			<td nowrap align="right"><?php echo $stt ?></td>	
			<td nowrap>			<!-- NGƯỜI MƯỢN -->
				
				<?=$row['F_NGUOIMUON'].' '.$row['L_NGUOIMUON'];?>
				
			</td>
			<td nowrap>			<!-- NGƯỜI CHO MƯỢN -->
				
				<?php echo $row['F_NGUOICHOMUON'].' '.$row['L_NGUOICHOMUON'];?>
						
			</td>
			<td nowrap>			<!-- NGƯỜI TRẢ -->
				
				<?php echo $row['F_NGUOITRA'].' '.$row['L_NGUOITRA'];?>
							
			</td>
			<td nowrap>			<!-- NGÀY MƯỢN -->
				
				<?php echo implode("/",array_reverse(explode("-",$row['NGAY_MUON']))) ?>
					
			</td>
			<td nowrap>			<!-- NGÀY TRẢ -->
				
				<?php echo implode("/",array_reverse(explode("-",$row['NGAY_TRA']))) ?>
				
				<input type="hidden" name="id" value='<?php echo $row['ID_MUONTRA'] ?>' />
			</td>
			<td nowrap>			<!-- NGÀY TRẢ THỰC TẾ -->				
				<?php if(($row['NGAYTRA_THUCTE'] == null) && ($row['ID_MUONTRA'] != ""))
				{
					echo 'Chưa trả ';	
					$isdelete = "<a href='#' onclick="."confirmDelete(".$this->id_hoso.",".$row['ID_MUONTRA'].")"."> Xóa</a>";
					
					$trahoso  = "<a href='javascript:;' onclick=\"";
					$trahoso .= "document.getElementById('iframesend";
					$trahoso .= $this->id_hoso;
					$trahoso .= "').style.display='';document.getElementById('iframesend";
					$trahoso .= $this->id_hoso;
					$trahoso .= "').setAttribute('src','/qllt/muontra/update/IdFrame/iframesend";
					$trahoso .= $this->id_hoso;
					$trahoso .= "/id_hoso/";
					$trahoso .= $this->id_hoso;
					$trahoso .= "/last_ngaymuon/";
					$trahoso .= $row['NGAY_MUON'];
					$trahoso .= "/idmt/";
					$trahoso .= $status2;
					$trahoso .="');\">Trả</a>";

				}
				else
				{					
					echo implode("/",array_reverse(explode("-",$row['NGAYTRA_THUCTE'])));					
				}
				;?>
				<input type="hidden" name="id" value='<?php echo $row['ID_MUONTRA'] ?>' />
			</td>	
			<td nowrap align="center"><!-- TRẢ -->
				<?php echo $trahoso ?>
				<input type="hidden" name="id" value='<?php echo $row['ID_MUONTRA'] ?>' />
			</td>
			<td nowrap align="center"><!-- XÓA -->
				<?php echo $isdelete ?>
				<input type="hidden" name="id" value='<?php echo $row['ID_MUONTRA'] ?>' />
			</td>
			
		</tr>
<?php
	$i = (-1+$i)*-1;
}
		if($stt == 0)
		{
		 echo '<tr><td colspan="9">Hồ sơ này chưa có người mượn</td></tr>';
		}
?>

	</tbody>
	<tfoot id="jump<?=$this->id_hoso ?>">                                 
		<tr>
			
			<th colspan="9" align=left>					
					<?php 
					if(($status == "") &&($status2 != ""))
					{
					?>					
						<iframe style="overflow-x:visible;display:none; width:100%" height=0 width=100% id=iframesend<?=$this->id_hoso ?> allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no src=""></iframe>	
					<?php
					}else
					{					
					?>
						<a href="#jump<?=$this->id_hoso ?>" onclick="
						document.getElementById('iframesend<?=$this->id_hoso ?>').style.display='';
						document.getElementById('iframesend<?=$this->id_hoso ?>').setAttribute('src','/qllt/muontra/addnew/IdFrame/iframesend<?=$this->id_hoso ?>/id_hoso/<?=$this->id_hoso ?>/ngaytra_thucte/<?=$status ?>');">Cho mượn
						</a>
						<iframe style="overflow-x:visible;display:none; width:100%" height=0 width=100% id=iframesend<?=$this->id_hoso ?> allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no src=""></iframe>						

					<?php
					} 
					?>

			</th>
		</tr>
</tfoot>

</table>
<input type="hidden" name="comeFrom" value="listForm">


