<?php require_once('qtht/models/DepartmentsModel.php');

$data_departs = DepartmentsModel::getAll();
?>

<!-- Khung lọc dữ liệu -->
<div>
<form name=frm action="/report/xulycongviec/listreport" method="POST" >
<div>
<label><b>Ngày bắt đầu:</b></label>
<?=QLVBDHCommon::calendar($this->fromdate,"fromdate","fromdate") ?>
>>
<?=QLVBDHCommon::calendar($this->todate,"todate","todate") ?>
</div>
<div class=clr></div>
<div>
<div>
<label><b>Tháng:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/1')">1
<?php 
$year = QLVBDHCommon::getYear();
$d = strtotime($year."-3-1") ;
$d = $d - 86400;
$str_cuoi2 =date('d/m',$d); 
 ?>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')" >2
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3','31/3')">3
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4','30/4')" >4
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5','31/5')">5
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6','30/6')">6
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','31/7')" >7
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8','31/8')" >8
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9','30/9')">9
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/10')">10
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11','30/11')">11
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12','31/12')">12
</div>
<div class=clr></div>
<div>
<label><b>Quí:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/3')">I
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4','30/6')">II
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','30/9')">III
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/12')">IV
</div>
<div class=clr></div>

<div>
<label><b>Năm:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/12')">
</div>
</div>
<div class=clr></div>
<br/>
<!--
<div>
<label><b>Chọn phòng ban:</b></label>
<select name="sel_pb[]" id="sel_lvb" multiple="multiple" size=5>
	<option value=0>[Tất cả phòng ban]</option>
	<?php DepartmentsModel::toComboName(); ?>
</select>
</div>
<div class="clr"></div>
<br/>
-->
<div>
<div style="float:left">
<label><b>Sổ văn bản:</b></label>
<select name="sel_svb" id="sel_svb" >
<?php 
	//
	$dep_u = UsersModel::getUserDepId($this->user->ID_U);
	$actid = ResourceUserModel::getActionByUrl("report","xulycongviec","xemtatcasvb");
	if(ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0])){
		echo " <option value=0>[Chọn tất cả]</option> ";
		sovanbanModel::toComboNameMC();
	}else{
		sovanbanModel::toComboNameMCByQuyenUser($dep_u["ID_DEP"]);
		
		
	}
	
?>	
	
</select>
<?php //var_dump($this->user); echo "dddddddd"; exit; ?>
</div>	
</div>
<div class="clr"></div>
<br/>
<div style="display:none">
<label><b>Chọn loại công việc:</b></label>
<select name="sel_lcv[]" id="sel_lcv" multiple="multiple" size=4>
	<option value=0>[Tất cả phòng ban]</option>
	<option value=1>Xử lý văn bản đến</option>
	<option value=2>Soạn thảo công việc</option>
	<option value=3>Hồ sơ một cửa</option>
</select>
</div>
<div class="clr"></div>
</form>
<div>
<input type=hidden id=h_isexel name=h_isexel value=0>

<div title="Hiện thị báo cáo" style="background-color:#C0C0C0;border:1px solid #888888;cursor:pointer;margin:2px;
padding:2px 2px;position:relative;white-space:nowrap;width:100px;height:25px" 
onclick="
document.frm.submit();
return false;">
<img src="/images/report_show.jpg" width="20" height="20"></img>
<b>Hiển thị</b>
</div>

<div class="clr"></div>

<iframe style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no 
id="list_report" 
name="list_report" >
</iframe>


<script>
function setvalueDateD(value_from,value_to){
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
}
</script>