<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form name="frm" method=post action="/hscv/phoihop/addgopy">
<table class=admintable>
	<tr>
		<td class=key>
			Nội dung góp ý
		</td>
		<td>
			<textarea rows="4" cols="100" name="NOIDUNG"></textarea>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<input type="button" value="Góp ý" onclick="document.frm.submit();" />
		</td>
	</tr>
</table>
<input type=hidden name=idhscv value="<?=$this->idhscv?>">
<input type=hidden name=code value="save">
<p id=lasttext></p>
</form>
</body>
</html>
<script>
	function resize(){
		var iframeElement = parent.document.getElementById('phoihop<?=$this->idhscv?>');
		iframeElement.style.height = "" + document.getElementById("lasttext").offsetTop + "px";
		iframeElement.width = "100%";
	}
	resize();
</script>