<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form name="frm" method=post action="/hscv/phoihop/adduser">
<table class=adminlist>
	<thead>
		<tr>
			<th nowrap="nowrap">#</th>
			<th width="50%">Người phối hợp</th>
			<th width="50%">Người yêu cầu</th>
			<th nowrap="nowrap">Xóa</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3" align=left>
				Thêm người phối hợp <?=QLVBDHCommon::writeSelectDepartmentUser("ID_PHONG","ID_U")?>
				<input type=submit value="Thêm"><font color=red><?=$this->error==1?"Đã có người dùng trong danh sách":""?></font>
			</th>
		</tr>
	</tfoot>
	<tbody>
<?php
	$i=0;
	$stt=1;
	foreach($this->data as $row){
?>
		<tr class="row<?=$i?>">
			<td nowrap><?=$stt?></td>
			<td width="50%"><?=htmlspecialchars($row['EMPNAME'])?></td>
			<td width="50%"><?=htmlspecialchars($row['EMPNAMEYC'])?></td>
			<td nowrap><a href="#" onclick="document.frm.action='/hscv/phoihop/delete/id/<?=$row['ID_PHOIHOP']?>/idhscv/<?=$this->idhscv?>';document.frm.submit();return false;">Xóa</a></td>
		</tr>
<?php
		$i = (-1+$i)*-1;
		$stt++;
	}
?>
	</tbody>
</table>
<input type=hidden name=idhscv value="<?=$this->idhscv?>">
<p id=lasttext></p>
</form>
</body>
</html>
<script>
	var arr_user = null;
	function resize(){
		var iframeElement = parent.document.getElementById('phoihop<?=$this->idhscv?>');
		iframeElement.style.height = "" + document.getElementById("lasttext").offsetTop + "px";
		iframeElement.width = "100%";
	}
	resize();
</script>