<?php if($this->type==1){ ?>
<table width="100%" class=adminlist1>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Sổ văn bản</td>
		<td nowrap="nowrap"><?=$this->data['SVBNAME']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Loại văn bản</td>
		<td nowrap="nowrap"><?=$this->data['LVBNAME']?></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Số ký hiệu</td>
		<td nowrap="nowrap"><?=$this->data['SOKYHIEU']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Số đến</td>
		<td nowrap="nowrap"><?=$this->data['SODEN']?></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Ngày ban hành</td>
		<td nowrap="nowrap"><?=date("d/m/Y",strtotime($this->data["NGAYBANHANH"]))?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Ngày đến</td>
		<td nowrap="nowrap"><?=date("d/m/Y",strtotime($this->data["NGAYDEN"]))?></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Cơ quan</td>
		<td><?=$this->data['COQUANBANHANH_TEXT']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Người ký</td>
		<td nowrap="nowrap"><?=$this->data['NGUOIKY']?></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Mã số văn bản</td>
		<td nowrap="nowrap"><?=$this->data['MASOVANBAN']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Lĩnh vực văn bản</td>
		<td nowrap="nowrap"><?=$this->data['LVVBNAME']?></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Số tờ</td>
		<td nowrap="nowrap"><?=$this->data['SOTO']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Độ mật</td>
		<td nowrap="nowrap"><?php
							switch($this->data['DOMAT']){
								case 0:
									echo "Chưa nhập";
									break;
								case 1:
									echo "bình thường";
									break;
								case 2:
									echo "mật";
									break;
								case 3:
									 echo "tuyệt mật";
									break;
								break;
							}
							?></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Số bản</td>
		<td nowrap="nowrap"><?=$this->data['SOBAN']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Độ khẩn</td>
		<td nowrap="nowrap"><?php
							switch($this->data['DOKHAN']){
								case 0:
									echo "Chưa nhập";
									break;
								case 1:
									echo "bình thường";
									break;
								case 2:
									echo "khẩn";
									break;
								case 3:
									 echo "hỏa tốc";
									 break;
								break;
							}
							?></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">File đính kèm</td>
		<td nowrap="nowrap" >
			<?php
				foreach($this->file as $fileitem){
					echo "<a href='/hscv/File/download?year=&maso=".$fileitem['MASO']."'>".$fileitem['FILENAME']."</a>, ";
				}
			?>
		</td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Cơ quan nhận</td>
		<td nowrap="nowrap"><? echo vbdenModel::getcq($this->data['COQUANNHAN']);?></td>
		<td width="100%"></td>
	</tr>
</table>
<?php }else if($this->type==2){ ?>
<table width="100%" class=adminlist1>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Tên công việc</td>
		<td nowrap="nowrap"><?=$this->data['NAME']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Ngày tạo</td>
		<td nowrap="nowrap"><?=QLVBDHCommon::MysqlDateToVnDate($this->data['NGAYTAO']);?></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Người yêu cầu</td>
		<td nowrap="nowrap"><?=$this->data['EMPYCNAME']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Người xử lý</td>
		<td nowrap="nowrap"><?=$this->data['EMPXLNAME']?></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Nội dung</td>
		<td nowrap="nowrap"><?=$this->data['NOIDUNG']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue"></td>
		<td nowrap="nowrap"></td>
		<td width="100%"></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">File đính kèm</td>
		<td width="100%" colspan="5">
			<?php
				foreach($this->file as $fileitem){
					echo "<a href='/hscv/File/download?year=&maso=".$fileitem['MASO']."'>".$fileitem['FILENAME']."</a>, ";
				}
			?>
		</td>
	</tr>
</table>
<?php }else{ ?>
<?php if($this->data['TENPHUONG']!= null){?>
 <table width="100%" class=adminlist1>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Sổ tiếp nhận</td>
		<td><?=SoVanBanModel::getNameById($this->data['ID_STN'])?></td>
		<td width="20" nowrap="nowrap"></td>

		<td nowrap="nowrap" style="color:blue">Số tiếp nhận</td>
		<td nowrap="nowrap"><?=$this->data['SO']?></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Tên hồ sơ</td>
		<td><?=$this->data['TRICHYEU']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Người xử lý</td>
		<td nowrap="nowrap"><?=$this->data['EMPXLNAME']?></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Mã số</td>
		<td nowrap="nowrap"><?=$this->data['MAHOSO']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Loại hồ sơ</td>
		<td><?=$this->data['LHSNAME']?></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Phường</td>
		<td nowrap="nowrap"><?= $this->data['TENPHUONG']?>
		</td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Địa chỉ</td>
		<td nowrap="nowrap"><?=$this->data['DIACHI']?></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Ngày nhận</td>
		<td nowrap="nowrap"><?=QLVBDHCommon::MysqlDateToVnDate($this->data['NHAN_NGAY'])?> <?=$this->data['NHAN_LUC']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Nhận lại ngày</td>
		<td nowrap="nowrap"><?=QLVBDHCommon::MysqlDateToVnDate($this->data['NHANLAI_NGAY']);?></td>
	</tr>
	<tr class=row1>
	    <td style="color:blue">Tên tổ chức / cá nhân</td>
		<td nowrap="nowrap"><?=$this->data['TENTOCHUCCANHAN']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Số ngày xử lý</td>
		<td nowrap="nowrap"><?=$this->data['SONGAYXULY']?> ngày</td>
	</tr>
	<?php require_once 'motcua/models/motcua_hosoModel.php';
		$arr_custom_fields = motcua_hosoModel::Customfields($this->data["ID_LOAIHOSO"]);
		$deme = count($arr_custom_fields);
		$stte = 0;
		foreach ($arr_custom_fields as $cus){
			if($stte%2==0)
				echo "<tr class=row1>";
	?>


		<td nowrap="nowrap" style="color:blue"><?=$cus["NAME_DISPLAY"]?></td>
		<td nowrap="nowrap"><?php
		if($cus["TYPE"] == "DATE"){
			echo implode("/",array_reverse(explode("-",$this->data[$cus["NAME_COLUMN"]])));
		}else{
			echo $this->data[$cus["NAME_COLUMN"]];
		}
		?>
		</td>
		<td width="20" nowrap="nowrap"></td>

	<?php
		if($stte%2==1 || $stte == $deme-1)
			echo "</tr>";
	$stte++;;}?>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">File đính kèm</td>
		<td width="100%" colspan="4">
			<?php
				foreach($this->file as $fileitem){
					echo "<a href='/hscv/File/download?year=&maso=".$fileitem['MASO']."'>".$fileitem['FILENAME']."</a>, ";
				}
			?>
		</td>


	</tr>
</table>
<?php }else {?>
 <table width="100%" class=adminlist1>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Sổ tiếp nhận</td>
		<td><?=SoVanBanModel::getNameById($this->data['ID_STN'])?></td>
		<td width="20" nowrap="nowrap"></td>

		<td nowrap="nowrap" style="color:blue">Số tiếp nhận</td>
		<td nowrap="nowrap"><?=$this->data['SO']?></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Tên hồ sơ</td>
		<td><?=$this->data['TRICHYEU']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Người xử lý</td>
		<td nowrap="nowrap"><?=$this->data['EMPXLNAME']?></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Mã số</td>
		<td nowrap="nowrap"><?=$this->data['MAHOSO']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Loại hồ sơ</td>
		<td><?=$this->data['LHSNAME']?></td>
	</tr>
	<tr class=row1>
		<td style="color:blue">Tên tổ chức / cá nhân</td>
		<td nowrap="nowrap"><?=$this->data['TENTOCHUCCANHAN']?>

		</td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Địa chỉ</td>
		<td nowrap="nowrap"><?=$this->data['DIACHI']?></td>
	</tr>
	<tr class=row1>
		<td nowrap="nowrap" style="color:blue">Ngày nhận</td>
		<td nowrap="nowrap"><?=QLVBDHCommon::MysqlDateToVnDate($this->data['NHAN_NGAY'])?> <?=$this->data['NHAN_LUC']?></td>
		<td width="20" nowrap="nowrap"></td>
		<td nowrap="nowrap" style="color:blue">Nhận lại ngày</td>
		<td nowrap="nowrap"><?=QLVBDHCommon::MysqlDateToVnDate($this->data['NHANLAI_NGAY']);?></td>
	</tr>
	<tr class=row1>


		<td nowrap="nowrap" style="color:blue">File đính kèm</td>
		<td width="100%" colspan="4">
			<?php
				foreach($this->file as $fileitem){
					echo "<a href='/hscv/File/download?year=&maso=".$fileitem['MASO']."'>".$fileitem['FILENAME']."</a>, ";
				}
			?>
		</td>


	</tr>
</table>
<?php }?>
<?php } ?>