<form name=frmListDepartments method="post" action="/qtht/departments">
	<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo $this->search ?>" class="text_area" onchange="document.frmListDepartments.submit();" />
				<button onclick="document.frmListDepartments.submit();">Tìm</button>
				<button onclick="document.getElementById('search').value='';document.frmListDepartments.submit();">Làm lại</button>
			</td>
			<td nowrap="nowrap">				
			</td>
		</tr>
	</table>
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap width="10">#</th>
			<th nowrap width="10"><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th width="10">Mã</th>
			<th width="50">Ký hiệu</th>
			<th width="80%">Tên</th>
			<th nowrap>Kích hoạt</th>
			
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="6">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frmListDepartments.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="50">50</option>
								<option value="100">100</option>
							</select>
							<script>
								document.frmListDepartments.limit.value='<?php echo $this->limit ?>';
							</script>
						</div>
						<div style="float:right"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row ){
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row['ID_DEP'] ?>'>
			</td>
			<td>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_DEP'] ?>);">
				<?php echo htmlspecialchars($row['CODE_DEP']) ?>
				</a>
			</td>
			<td>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_DEP'] ?>);">
				<?php echo htmlspecialchars($row['KYHIEU_PB']) ?>
				</a>
			</td>
			<td width=70%>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_DEP'] ?>);">
				<?php echo str_repeat("---",$row['LEVEL']-1).htmlspecialchars($row['NAME']) ?>
				</a>
			</td>
			<td><a href="<?php echo $this->url(array('controller'=>'departments', 
            'action'=>'save', 'id'=>$row['ID_DEP'],'act'=>$row['ACTIVE']));?>"><?php if($row['ACTIVE']=='1') echo 'Rồi';
			else echo 'Chưa';?></a></td>
			
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
<input type="hidden" name="comeFrom" value="listForm">
</form>
<script>
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","Chọn ít nhất một phòng ban để xoá.");
	if(mess){
		if(confirm("<?php echo 'Bạn muốn xóa mục này!'; ?>")){
			document.frmListDepartments.action = "/qtht/departments/delete";
			document.frmListDepartments.submit();
		}
	}else{
		alert("Chọn ít nhất một phòng ban để xoá.");
	}
}
function AddNewButtonClick()
{
	document.frmListDepartments.action = "/qtht/departments/input";
	document.frmListDepartments.submit();
}
function ItemClick(id)
{
	document.frmListDepartments.action = "/qtht/departments/input/id/"+id;
	document.frmListDepartments.submit();
}
</script>



