<script type="text/javascript">
var ischecked = 0;
</script>
<form id="containerID" action="/qtht/DanhMucChucDanh/save" method="post" enctype="multipart/form-data" name="datacdform" >
<fieldset>
	<legend>Thông tin chức danh</legend>
	<div class="required clearfix">
		<label>Tên chức danh</label>
		<input type="text" name="name" value="<?php echo htmlspecialchars($this->namebefore);?>" class="inputText" size="10" maxlength="100" >
    	<span class="box_erro_area" id="ERRname"></span>
	</div>
	<div class="required clearfix">
		<label>Đã được sử dụng</label>
        <?php
            if($this->activeselect == 1){
                echo '<input type="checkbox" value=1 name="active" class="inputCheckbox" checked=checked>';
            }
            else {
                echo '<input type="checkbox" value=1 name="active" class="inputCheckbox">';
            }
        ?>
	</div>
</fieldset>
<input type=hidden name="idChucDanh" value=<?php echo $this->id?> >
<input type=hidden name="limit" value=<?php echo $this->limit?> >
<input type=hidden name="filter_object" value=<?php echo $this->filter_object?> >
<input type=hidden name="search" value=<?php echo $this->search?> >
<input type=hidden name="page" value=<?php echo $this->page?> >
<fieldset>
	<legend>Chọn nhân viên vào chức danh</legend>
		<table class="adminlist">
            <thead>
                <tr>
                    <th nowrap width=60>STT</th>
                    
                    <th width=100%>Tên Nhân viên</th>
                    <th nowrap width=50>Mã số</th>
                </tr>
            </thead>
		</table>

        <?php 
            foreach($this->data as $it_dep){
        ?>
        <div id="content-pane" class="pane-sliders">
            <div class="panel">
                <h3 class="jpane-toggler title">
                    <span><?php echo 'Phòng Ban : '.$it_dep["DEP_NAME"]?></span>
                </h3>
                <div class="jpane-slider content">
                    <table class="adminlist">
                        
                        <tbody>
                            <?php
                            $stt=0;
                            $i=0;
                            
                            foreach ($it_dep as $row ){
                                $stt++;
                            ?>
                                    <tr class="row<?php echo $i; ?>">
                                        <td nowrap width=30 align="right"><?php echo $stt ?></td>
                                        <td nowrap width=30 align="center">
                                            <input type=checkbox name=SEL_EMP[] value='<?php echo $row["ID_EMP"] ?>' <?php if($row['SEL'] == 1) echo 'checked' ?> onclick=OnChangeCheck()>
                                        </td>
                                        <td width=100%>
                                            <?php echo htmlspecialchars($row["FIRSTNAME"].' '.$row["LASTNAME"]) ?>
                                        </td>
                                        <td nowrap width=50> <?php echo $row["ID_EMP"]?></td>
                                        
                                    </tr>
                            <?php
                                $i = (-1+$i)*-1;
                            }
                            ?>	
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
	<?php }?>
</fieldset>
</form>
<script>

function checkFormData(){

	
	var str = "Bạn phải nhập tên chức danh";
	var strerr = validateInput("required",document.datacdform.name,str);
	if(!strerr){
		document.datacdform.name.focus();
		return false;
	}
	str="Tên chức danh không được quá 128 ký tự";
	strerr = validateInput("maxlen=128",document.datacdform.name,str);
	if(!strerr){
		
		document.datacdform.name.focus();
		return false;
	}
	return true;
}

function SaveButtonClick(){
	
	//window.showModalDialog( '/DialogTemplate/QueryDialog.html',document);
	
	
	if(checkFormData()){
		
			if(ischecked){
				var elehidden =document.createElement("input");
				elehidden.setAttribute("name" , "ischeckchange");
				elehidden.type = "hidden";
				elehidden.value="1";
				document.datacdform.appendChild(elehidden);
			}
		
		//document.datacdform.method ="get";
		document.datacdform.submit();
	}
}
function BackButtonClick(){
	document.datacdform.action = '/qtht/danhmucchucdanh/index';
	document.datacdform.submit();
}
function OnChangeCheck(){
	ischecked = 1;

}
		
	

</script>