<?php
$this->dojo()->enable();
?>
<form name=frm method="post" action="/motcua/linhvucmotcua/">
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>#</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th width="100%">Tên lĩnh vực</th>
			<th nowrap>Người tiếp nhận</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="4">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frm.page.value = 1;document.frm.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="50">50</option>
								<option value="100">100</option>
								<script>
									document.frm.limit.value='<?php echo $this->limit ?>';
								</script>
							</select>
						</div>
						<div style="float:right;"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt_outer=0;
$i=0;
foreach ($this->data as $row ){
     $stt_outer++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt_outer ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row['ID_LV_MC'] ?>'>
			</td>
			<td width=100%>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_LV_MC'] ?>);">
				<?php echo htmlspecialchars($row['NAME']) ?>
				</a>
			</td>
			<td nowrap>
				<?php
					$nguoitiepnhan = $this->model->GetUserById($row['ID_LV_MC']);
					if($nguoitiepnhan){
						$stt = 0;
						foreach($nguoitiepnhan as $item){
							$stt ++;
							echo $stt.". ".$item["NAME"]."<br>";
						}
					}else{
						echo "Chưa có người tiếp nhận";
					}
				?>
			</td>
		</tr>
<?php
	$i = (-1+$i)*-1;

}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>
<script>
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","Chưa chọn mục để xóa.");
	if(mess){
		if(confirm("Bạn có muốn xóa các lĩnh vực được chọn không?")){
			document.frm.action = "/motcua/linhvucmotcua/Delete";
			document.frm.submit();
		}
	}else{
		alert("Chưa chọn mục để xóa.");
	}
}
function AddNewButtonClick(){
	document.frm.action = "/motcua/linhvucmotcua/input";
	document.frm.submit();
}
function ItemClick(id){
	document.frm.action = "/motcua/linhvucmotcua/input/id/"+id;
	document.frm.submit();
}
</script>