<form name=frm method="post" action="/motcua/linhvucmotcua/save" enctype="multipart/form-data" >
<fieldset>
	<div class="required">
		<label>Tên lĩnh vực(*)</label>
		<input type=text class=inputbox name=NAME value="<?=$this->data->NAME?>" class="inputText" size="50" maxlength="100">
    	<span class="box_erro_area" id="ERRNAME"></span>
	</div>
    <div class=clr></div>
	<div class="required">
		<label><b>Nội Dung</b></label>
		<textarea name=NOIDUNG id=NOIDUNG rows="5" size="100"><?=$this->data->NOIDUNG?></textarea>
	</div>
	<div class="required clearfix">
		<label>Được sử dụng(*)</label>
		<input type=checkbox class=inputbox name=ACTIVE value="1" <?php echo $this->data->ACTIVE==1?"checked":"" ?> class="inputText" size="50" maxlength="100">
		<span class="box_erro_area" id="ERRACTIVE"></span>
	</div>
    <div class="optional">
		<label>(*) Bắt buộc nhập liệu.</label>
	</div>
</fieldset>

<fieldset>
	<legend>Người tiếp nhận</legend>
	<table class=adminlist>
		<thead>
			<tr>
				<th nowrap>STT</th>
				<th nowrap><input type=checkbox name=CHECKALL onclick="SelectAll(this,'CHECK')"></th>
				<th width=100%>Nhân viên</th>
			</tr>
		</thead>
		<tbody>
		<?php
			//In danh sách user truy cập
			$i = 0;
			foreach($this->uaccess as $item){
				$i++;
		?>
			<tr>
				<td nowrap><?=$i?></td>
				<td nowrap><input type=checkbox name=CHECK[] value='<?php echo $item['ID_U'] ?>' <?=($item["SEL"]=="1"?"checked":"")?>></td>
				<td width=100%><?=$item["NAME"]?></td>
			</tr>
		<?php
			}
		?>
		</tbody>
		<tfoot><tr><th colspan=3></th></tr></tfoot>
	</table>
</fieldset>
<input type=hidden name=ID_LV_MC value="<?php echo $this->data->ID_LV_MC; ?>">
<input type=hidden name=page value="<?php echo $this->page; ?>">
<input type=hidden name=limit value="<?php echo $this->limit; ?>">
<input type=hidden name=search value="<?php echo $this->search; ?>">
<input type=hidden name=filter_object value="<?php echo $this->filter_object; ?>">
</form>
<script>
	function SaveButtonClick(){
		var err = true;
		err = err & validateInput("req",document.frm.NAME,"Phải nhập tên lĩnh vực");
		err = err & err==true?validateInput("maxlen=512",document.frm.NAME,"Tên lĩnh vực phải ít hơn 512 ký tự"):false;
		if(err==true){
			document.frm.submit();
		}
	}
	function BackButtonClick(){
		document.frm.action = "/motcua/linhvucmotcua/";
		document.frm.submit();
	}
</script>