<?php
	require_once 'Common/FileDinhKem.php';
?>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse_state.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<form name=frmListMotCuas method="post">
	<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo $this->search ?>" class="text_area" onchange="document.frmListMotCuas.submit();" />
				<button onclick="document.frmListMotCuas.submit();">Tìm</button>
				<button onclick="document.getElementById('search').value='';document.frmListMotCuas.submit();">Làm lại</button>
			</td>
			<td nowrap="nowrap">				
			</td>
		</tr>
	</table>
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>#</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th width="100%">Mã hồ sơ</th>			
			<th width="100%">Nhận vào</th>	
			<th width="100%">Tên tổ chức cá nhân</th>	

		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="10">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frmListMotCuas.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="50">50</option>
								<option value="100">100</option>
								<script>
									document.frmListMotCuas.limit.value='<?php echo $this->limit ?>';
								</script>
							</select>
						</div>
						<div style="float:right;"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row )
	{
	$stt++;
?>
		<tr class="row<?php echo $i; ?>" valign="top">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row['ID_HOSO'] ?>'>
			</td>
			<td width=100%>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_HOSO']?>);">
				<b><?php echo $row['SOKYHIEU'];?></b> :<?php echo htmlspecialchars($row['TRICHYEU']) ?>  
				</a>
				<div>
					
					<div id=groupicon1_<?=$row["ID_VBDI"]?> class="groupicon"></div><div class="groupitem">
							<a href='javascript:LoadContentDiv(<?=$row["ID_HOSO"]?>,1)'>
							Chi tiết
							</a>
					</div>
					<div id=groupicon4_<?=$row["ID_HOSO"]?> class="groupicon"></div><div class="groupitem">
						<a href='javascript:SwapDiv(<?=$row["ID_HOSO"]?>,"/hscv/file?iddiv=groupcontent<?=$row["ID_HOSO"]?>&idObject=<?=$row["ID_HOSO"]?>&is_new=0&year=<?=$this->realyear?>&type=30",4)'>File đính kèm</a>
					</div>
					<div id=groupicon6_<?=$row["ID_HOSO"]?> class="groupicon"></div><div class="groupitem">Luân chuyển</div>
				</div>
				<div class="clr"></div>				
				<div class="groupcontent" id="groupcontent<?=$row["ID_HOSO"]?>" style="display:none"></div>				
				<div class="groupcontent" id="detailContent_<?=$row["ID_HOSO"]?>" style="display:none">
					<table class="adminlist">
						<tr>
							<th>Tên trường</th>
							<th>Giá trị</th>
						</tr>				
						<tr>
							<td width="20%">Số đi</td>						
							<td><font color="blue"><?=$row['SODI']?></font></td>
						</tr>
						<tr>
							<td width="20%">Số ký hiệu</td>						
							<td><font color="blue"><?=$row['SOKYHIEU']?></font></td>
						</tr>
						
						<tr>
							<td width="20%">Trích yếu</td>
							<td><font color="blue"><?=$row['TRICHYEU']?></font></td>
						</tr>
						<tr>
							<td width="20%">Loại văn bản</td>
							<td><font color="blue"><?=$row['LOAIVB']?></font></td>
						</tr>
						<tr>
							<td>Lĩnh vực văn bản</td>
							<td><font color="blue"><?=$row['LINHVUCVANBAN']?></font></td>
						</tr>
						<tr>
							<td>Cơ quan</td>
							<td><font color="blue"><?=$row['TENCOQUAN']?></font></td>
						</tr>
						<tr>
							<td>Người tạo</td>
							<td><font color="blue"><?=$row['NGUOITAO']?></font></td>
						</tr>
					</table>
					 
				</div>
			</td>	
			<td><?=$row['NHAN_LUC']?>  <?=$row['NHAN_NGAY']?></td>	
			<td><?=$row['TENTOCHUCCANHAN']?></td>
			
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
<input type="hidden" name="year" value="<?php echo $this->year; ?>">
<input type="hidden" name="comeFrom" value="listForm">
</form>
<script>
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","Chọn ít nhất một mục để xoá.");
	if(mess){
		if(confirm("<?php echo 'Bạn muốn xóa mục này!'; ?>")){
			document.frmListMotCuas.action = "/motcua/hosomotcua/delete";
			document.frmListMotCuas.submit();
		}
	}else{
		alert("Chọn ít nhất một mục để xoá.");
	}
}
function AddNewButtonClick()
{
	document.frmListMotCuas.action = "/motcua/hosomotcua/input";
	document.frmListMotCuas.submit();
}
function ItemClick(id)
{
	document.frmListMotCuas.action = "/motcua/hosomotcua/input/id/"+id;
	document.frmListMotCuas.submit();
}
function SwapDiv(id,url,tab)
{
	for(var i=1;i<11;i++){
		if(document.getElementById("groupicon"+i+"_"+id)){
			if(tab!=i){
				if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
					document.getElementById("groupcontent"+id).style.display="none";
					document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
					break;
				}
			}
		}
	}
	objtemp=document.getElementById("detailContent_"+id);
	visibletemp=(objtemp.style.display!="none")
	if(visibletemp)
	{
		objtemp.style.display="none";
		
	}	
	if(document.getElementById("groupcontent"+id).style.display==""){
		document.getElementById("groupcontent"+id).style.display="none";
		document.getElementById("groupicon"+tab+"_"+id).className = "groupicon";
	}else{
		document.getElementById("groupcontent"+id).style.display="";
		document.getElementById("groupicon"+tab+"_"+id).className = "groupiconopen";
		document.getElementById("groupcontent"+id).innerHTML="<img src='/images/loading.gif' width='20' height='20' border='0'></img<img src='/images/loading.gif' width='20' height='20' border='0'></img><img src='/images/loading.gif' width='20' height='20' border='0'></img><img src='/images/loading.gif' width='20' height='20' border='0'></img><img src='/images/loading.gif' width='20' height='20' border='0'></img>";
		loadDivFromUrl("groupcontent"+id,url,1);
	}
}
function LoadContentDiv(id)
{
	
	objtemp=document.getElementById("detailContent_"+id);
	visibletemp=(objtemp.style.display!="none")
	if(visibletemp)
	{
		objtemp.style.display="none";
		
	}
	else
	{
		document.getElementById("groupcontent"+id).style.display="none";		
		objtemp.style.display="";
	}
	
}
</script>