<form action="" name="frmAddMenu"  method="<?php echo $this->form->getAttrib('method');?>">
	<div style="text-align:right;width:100%">
		Trường có dấu <font color="red">*</font> là bắt buộc nhập
	</div>
	<div align="center"><span class="box_erro_area"><?php echo $this->error; ?></span></div>
	<div class="required clearfix">
		<label id="lblTextIput">Tên menu<font color="red">*</font></label>
		<?php echo $this->form->getElement('NAME');?>
    	<span class="box_erro_area">
        	<?php 
            	echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('NAME')); 
			?>
        </span>
	</div>
	<div class="optional clearfix">
		<label for="SCRIPT" id="lblTextIput">Mã javascript</label>
		<?php echo $this->form->getElement('SCRIPT');?>
	</div>
	<div class="optional clearfix">
		<label for="ICON" id="lblTextIput">Icon</label>
		<?php echo $this->form->getElement('ICON');?>
        (Các file định dạng *.gif,*.png...)
        <span class="box_erro_area">
        	<?php 
            	echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('ICON')); 
            ?>
        </span>
	</div>	
	<div class="optional clearfix">
		<label for="URL" id="lblTextIput">URL </label>
		<?php echo $this->form->getElement('URL');?>
	</div>
	<div class="optional clearfix">
		<label for="ACTID" id="lblTextIput"> Action</label>
            <select name=ACTID>
            <option value="">--Chọn action--</option>
            <?php
            	$idmd=0;
				for($i=0;$i<count($this->act);$i++){
					if($this->act[$i]['ID_MOD']!=$idmd){
						if($idmd>0){
							echo "</optgroup>";
						}
						echo "<optgroup label='".$this->act[$i]['MODNAME']."'>";
						$idmd = $this->act[$i]['ID_MOD'];
						echo "<option value=".$this->act[$i]['ID_ACT']." ".($this->act[$i]['ID_ACT']==$this->ACTID?'selected':'').">".$this->act[$i]['NAME']."</option>";
					}else{
						echo "<option value=".$this->act[$i]['ID_ACT']." ".($this->act[$i]['ID_ACT']==$this->ACTID?'selected':'').">".$this->act[$i]['NAME']."</option>";
					}
				}
				echo "</optgroup>";
            ?>
            </select>
        <span class="box_erro_area">

        </span>
	</div>
	<div class="optional clearfix">
		<label for="ID_MNU_PARENT" id="lblTextIput">Danh sách menu cha</label>
		<?php echo $this->form->getElement('ID_MNU_PARENT');?>
        <span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('ID_MNU_PARENT'));			
            ?>
        </span>
	</div>
	<div class="optional clearfix">
        <label for="ISLASTMENU" id="lblTextIput">Menu cuối cùng</label>
        <?php echo $this->form->getElement('ISLASTMENU');?>
	</div>
    <div class="optional clearfix">
        <label for="POPUP" id="lblTextIput">Có popup</label>
        <?php echo $this->form->getElement('POPUP');?>
	</div>
    <div class="optional clearfix">
        <label for="WIDTH" id="lblTextIput">Chiều rộng Popup</label>
        <?php echo $this->form->getElement('WIDTH');?>
        <span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('WIDTH'));			
            ?>
        </span>
	</div>
    <div class="optional clearfix">
        <label for="HEIGHT" id="lblTextIput">Chiều cao Popup</label>
        <?php echo $this->form->getElement('HEIGHT');?>
        <span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('HEIGHT'));			
            ?>
        </span>
	</div>
    <div class="optional clearfix">
        <label for="TOP" id="lblTextIput">Canh Top</label>
        <?php echo $this->form->getElement('TOP');?>
        <span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('TOP'));			
            ?>
        </span>
	</div>
    <div class="optional clearfix">
        <label for="XLEFT" id="lblTextIput">Canh trái Popup</label>
        <?php echo $this->form->getElement('XLEFT');?>
        <span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('XLEFT'));			
            ?>
        </span>
	</div>
    <div class="optional clearfix">
        <label for="ISCENTER" id="lblTextIput">Canh giữa</label>
        <?php echo $this->form->getElement('ISCENTER');?>
	</div>
</form>

<script>
	function SaveButtonClick()
	{
		document.frmAddMenu.submit();
	}
	function BackButtonClick()
	{
		document.frmAddMenu.action = "/qtht/menus/";
		document.frmAddMenu.submit();
	}
</script>