<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<?php
	foreach($this->sel_lhss as $loai){
		$this->data = TiepnhanhosomotcuaModel::reportHoso($this->trangthai,$loai, $this->fromdate, $this->todate, $this->fromdategt, $this->todategt, "null,0,1", "-1", "", $this->chkLienThong);
			
?>
		<b><?=TiepnhanhosomotcuaModel::getTenLoai($loai);?></b>
		<br>
		<br>
		<table class=adminlist>
		 <thead>
			<?php
				if($this->trangthai==12){
			?>
			<tr>
				<th nowrap >STT</th>
				<th nowrap >Số HS</th>
				<th nowrap >Đơn vị cá nhân</th>
				<th nowrap >Địa chỉ</th>
				<th nowrap >Phường</th>
				<th nowrap >Ngày TN</th>
				<th>Nội dung yêu cầu</th>
				<th nowrap >Ngày bổ sung</th>
			</tr>
			<?php } elseif($this->trangthai==13) {
			
			?>
			<tr>
				<th nowrap >STT</th>
				<th nowrap >Số HS</th>
				<th nowrap >Đơn vị cá nhân</th>
				<th nowrap >Địa chỉ</th>
				<th nowrap >Phường</th>
				<th nowrap >Ngày TN</th>
				<th>Nội dung yêu cầu</th>				
			</tr>
			<?php
				 
			}else{
			?>
			<tr>
				<th nowrap >STT</th>
				<th nowrap >Số HS</th>
				<th nowrap >Đơn vị cá nhân</th>
			<?php
				$arr_custom_fields = motcua_hosoModel::Customfields($loai);
				foreach($arr_custom_fields as $cus){
			?>	
				<th nowrap ><?=$cus["NAME_DISPLAY"]?></th>
			<?php }
			?>
				<th nowrap >Địa chỉ</th>
				<th nowrap >Phường</th>
				<th nowrap >Ngày TN</th>
				<th nowrap >Ngày hẹn trả</th>
				<th nowrap> Ngày chuyển UB</th>
				<th nowrap> Phòng CM trả</th>
				<th nowrap> Ngày trả thực tế</th>
			</tr>
			<?php
				}	
			?>
		 </thead>
		 <tbody>
		
		<?php
		
		require_once 'qtht/models/LoaiVanBanModel.php';
		require_once 'qtht/models/CoquanModel.php'; 
		require_once 'qtht/models/DepartmentsModel.php';
		require_once 'qtht/models/UsersModel.php';
		$stt=1;
		foreach($this->data as $row){ 
			if($this->trangthai==12){
				if($row["TRANGTHAI"] > 0 && $row["TRANGTHAI"] <= 2){
			?>
				<tr>
				<td><?=$stt?></td>
				<td><?=$row["SO"]?></td>
				
				<td  valign=top rowspan=<?php echo $d ?>><?php  echo $row["TENTOCHUCCANHAN"]; ?></td>
				<?php
					foreach($arr_custom_fields as $cus){
				?>	
					<td nowrap >
						<?php 
							if($cus["TYPE"] == "DATE"){
								echo implode("/",array_reverse(explode("-",$row[$cus["NAME_COLUMN"]])));
							}else{
								echo $row[$cus["NAME_COLUMN"]];
							}
							?>
					</td>
				<?php }
				?>
				<td   valign=top rowspan=<?php echo $d ?>><?php  echo $row["DIACHI"]?></td>
				<td   valign=top rowspan=<?php echo $d ?>><?php  echo $row["TENPHUONG"]?></td>
				<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo QLVBDHCommon::MysqlDateToVnDate($row["NHAN_NGAY"])?></td> 	
				<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo nl2br($row["CACGHICHU"])?></td>
				<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo QLVBDHCommon::MysqlDateToVnDate($row["NGAY_BOSUNG"])?></td>	
				</tr>
			<?php  	
				$stt++;
				}
			}
			elseif ($this->trangthai == 13 ) { 			
			if($row["TRANGTHAI"] > 0 && $row["TRANGTHAI"] <= 2){ ?>

			<tr>
				<td><?=$stt?></td>
				<td><?=$row["SO"]?></td>
				
				<td  valign=top rowspan=<?php echo $d ?>><?php  echo $row["TENTOCHUCCANHAN"]; ?></td>
				<?php
					foreach($arr_custom_fields as $cus){
				?>	
					<td nowrap >
						<?php 
							if($cus["TYPE"] == "DATE"){
								echo implode("/",array_reverse(explode("-",$row[$cus["NAME_COLUMN"]])));
							}else{
								echo $row[$cus["NAME_COLUMN"]];
							}
							?>
					</td>
				<?php }
				?>
				<td   valign=top rowspan=<?php echo $d ?>><?php  echo $row["DIACHI"]?></td>
				<td   valign=top rowspan=<?php echo $d ?>><?php  echo $row["TENPHUONG"]?></td>
				<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo QLVBDHCommon::MysqlDateToVnDate($row["NHAN_NGAY"])?></td> 	
				<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo nl2br($row["CACGHICHU"])?></td>				
				</tr>
			<? 
			$stt++;	
			}
			}
			else{
			if($row["TRANGTHAI"] > 0 && $row["TRANGTHAI"] <= 2){
		?>
			<tr>
			<td><?=$stt?></td>
			<td><?=$row["SO"]?></td>
			
			<td  valign=top rowspan=<?php echo $d ?>><?php  echo $row["TENTOCHUCCANHAN"]; ?></td>
			<?php
				foreach($arr_custom_fields as $cus){
			?>	
				<td nowrap >
					<?php 
						if($cus["TYPE"] == "DATE"){
							echo implode("/",array_reverse(explode("-",$row[$cus["NAME_COLUMN"]])));
						}else{
							echo $row[$cus["NAME_COLUMN"]];
						}
						?>
				</td>
			<?php }
			?>
			<td   valign=top rowspan=<?php echo $d ?>><?php  echo $row["DIACHI"]?></td>
			<td   valign=top rowspan=<?php echo $d ?>><?php  echo $row["TENPHUONG"]?></td>
			<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo QLVBDHCommon::MysqlDateToVnDate($row["NHAN_NGAY"])?></td> 	
			<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo QLVBDHCommon::MysqlDateToVnDate($row["NHANLAI_NGAY"])?></td>
			<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo QLVBDHCommon::MysqlDateToVnDate($row["CHUYENUB_NGAY"])?></td>
			<td nowrap valign=top rowspan=<?php echo $d ?>><?php  echo QLVBDHCommon::MysqlDateToVnDate($row["PCMTRA_NGAY"])?></td>
			<td valign=top rowspan=<?php echo $d ?>><?php
				echo QLVBDHCommon::MysqlDateToVnDate($row["TRA_NGAY"]);
				if($row["KHONGXULY"]==1 && $row["LYDOKHONGXULY"]!=""){
					echo "<br><I><B>Lý do không XL:</B></I> ".$row["LYDOKHONGXULY"];
				}
			?>
			
			</td>
			
			</tr>
		<?php  	
			$stt++;
			}
			}
			
		  } ?>
		 </tbody>
		 <?php
			if(count($this->data) == 0){
			echo "<tr><td colspan='10'>Không có hồ sơ nào</td></tr>";
			}
		 ?>
		 <tfoot>
		 </tfoot>
		</table>
		<br>
		<br>
		<br>
<?php 

	}
?>
<p id=lasttext></p>
</body>
</html>
<script>
var iframeElement = window.parent.document.getElementById('reportview');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 

</script>