<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">


<form name="frm" action="/hscv/thumuccanhan/saveluutmcn/" method="post" >
<label><b>Lưu vào thư mục:&nbsp;</b></label>
<select name="ID_TMCN">

	<?php 
		//in ra cac gia tri cua combobox
		
		$count = count($this->datathumuc);
		//echo $count;
		for($i = 0 ; $i< $count  ;$i++){
			
			echo '<option value='.$this->datathumuc[$i]["ID_TMCN"].'>'.htmlspecialchars(str_repeat("--",$this->datathumuc[$i]["LEVEL"]-1).$this->datathumuc[$i]["NAME"]). '</option>';
		}

	?>   		
</select>
<input type="button" value="Lưu thư mục" onclick="document.frm.submit();">
<input type="hidden" name="ID_HSCV" value="<?=$this->ID_HSCV?>" >
</form>
<table class="adminlist">
	<thead> 
		<tr>
			<th>#</th>
			<th colspan=2>Tên thư mục</th>
		</tr>
	</thead>
	<tbody> 
		<?php $stt = 1;foreach($this->thumuclist as $thumucown ) {?>
			<tr>
				<td nowrap><?=$stt?></td>
				<td width=100%><a href="#"><?=$thumucown["NAME"]?></a></td>
				<td><a href="/hscv/thumuccanhan/deleteluutmcn/ID_HSCV/<?=$this->ID_HSCV?>/ID_TMCN/<?=$thumucown["ID_TMCN"]?>">[<b>Xóa</b>]</a></td>
			</tr>
		<?php $stt++;}?>
	</tbody>
</table>

</body>
<p id=lasttext></p>
</html>
<script>
	function resize(){
		var iframeElement = parent.document.getElementById('iframebutphe<?=$this->ID_HSCV?>');
		iframeElement.style.height = "" + document.getElementById("lasttext").offsetTop + "px";
		iframeElement.width = "100%";
	}
	resize();
</script>