<?php
$this->dojo()->enable();
?>
<form name=frm method="post" action="/qtht/Groups">
    <table>
        <tr>
            <td align="left" width="100%">
                Lọc:
                <input type="text" name="search" id="search" value="<?php echo $this->search ?>" class="text_area" onchange="document.frm.submit();" />
                <button onclick="document.frm.submit();">Tìm</button>
                <button onclick="document.getElementById('search').value='';document.frm.submit();">Làm lại</button>
            </td>            
        </tr>
    </table>
    <table class="adminlist">
    <thead>
        <tr>
            <th nowrap>#</th>
            <th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
            <th width="100%"><?php echo MSG11009005 ?></th>
            <th nowrap><?php echo MSG11009006 ?></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="4">
                    <div class="pagination">
                        <div class="limit">Hiển thị #
                            <select name="limit" id="limit" class="inputbox" size="1" onchange="document.frm.submit();" style="width:60px;">
                                <option value="5">5</option>
                                <option value="10">10</option>
                                <option value="15">15</option>
                                <option value="20">20</option>
                                <option value="25">25</option>
                                <option value="30">30</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                                <script>
                                    document.frm.limit.value='<?php echo $this->limit ?>';
                                </script>
                            </select>
                        </div>
                        <div style="float:right;"><?php echo $this->showPage; ?></div>
                    </div>
            </td>
        </tr>
    </tfoot>

    <tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row ){
    $stt++;
?>
        <tr class="row<?php echo $i; ?>">
            <td nowrap align="right"><?php echo $stt ?></td>
            <td nowrap align="center">
                <input type=checkbox name=DEL[] value='<?php echo $row['ID_G'] ?>'>
            </td>
            <td width=100%>
                <a href="#" onclick = "ItemClick(<?php echo $row['ID_G'] ?>);">
                <?php echo htmlspecialchars($row['NAME']) ?>
                </a>
            </td>            
            <td nowrap>
                <?php echo htmlspecialchars($row['ACTIVE']) ?>
            </td>            
        </tr>
<?php
    $i = (-1+$i)*-1;
}
?>        
    </tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>
<script>
function DeleteButtonClick(){
    if(confirm("<?php echo DELETEQUESTION; ?>")){
        document.frm.action = "/qtht/Groups/Delete";
        document.frm.submit();
    }
}
function AddNewButtonClick(){
    document.frm.action = "/qtht/Groups/input";
    document.frm.submit();
}
function ItemClick(id){
    document.frm.action = "/qtht/Groups/input/id/"+id;
    document.frm.submit();
}
</script>